// automatically generated by the FlatBuffers compiler, do not modify

// @generated

use core::cmp::Ordering;
use core::mem;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

pub enum clz_Torappu_MeetingClueData_ClueDataOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct clz_Torappu_MeetingClueData_ClueData<'a> {
    pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for clz_Torappu_MeetingClueData_ClueData<'a> {
    type Inner = clz_Torappu_MeetingClueData_ClueData<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table::new(buf, loc),
        }
    }
}

impl<'a> clz_Torappu_MeetingClueData_ClueData<'a> {
    pub const VT_CLUEID: flatbuffers::VOffsetT = 4;
    pub const VT_CLUENAME: flatbuffers::VOffsetT = 6;
    pub const VT_CLUETYPE: flatbuffers::VOffsetT = 8;
    pub const VT_NUMBER: flatbuffers::VOffsetT = 10;

    #[inline]
    pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        clz_Torappu_MeetingClueData_ClueData { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args clz_Torappu_MeetingClueData_ClueDataArgs<'args>,
    ) -> flatbuffers::WIPOffset<clz_Torappu_MeetingClueData_ClueData<'bldr>> {
        let mut builder = clz_Torappu_MeetingClueData_ClueDataBuilder::new(_fbb);
        builder.add_number(args.number);
        if let Some(x) = args.clueType {
            builder.add_clueType(x);
        }
        if let Some(x) = args.clueName {
            builder.add_clueName(x);
        }
        if let Some(x) = args.clueId {
            builder.add_clueId(x);
        }
        builder.finish()
    }

    #[inline]
    pub fn clueId(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(
                clz_Torappu_MeetingClueData_ClueData::VT_CLUEID,
                None,
            )
        }
    }
    #[inline]
    pub fn clueName(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(
                clz_Torappu_MeetingClueData_ClueData::VT_CLUENAME,
                None,
            )
        }
    }
    #[inline]
    pub fn clueType(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(
                clz_Torappu_MeetingClueData_ClueData::VT_CLUETYPE,
                None,
            )
        }
    }
    #[inline]
    pub fn number(&self) -> i32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<i32>(clz_Torappu_MeetingClueData_ClueData::VT_NUMBER, Some(0))
                .unwrap()
        }
    }
}

impl flatbuffers::Verifiable for clz_Torappu_MeetingClueData_ClueData<'_> {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        use self::flatbuffers::Verifiable;
        v.visit_table(pos)?
            .visit_field::<flatbuffers::ForwardsUOffset<&str>>("clueId", Self::VT_CLUEID, false)?
            .visit_field::<flatbuffers::ForwardsUOffset<&str>>(
                "clueName",
                Self::VT_CLUENAME,
                false,
            )?
            .visit_field::<flatbuffers::ForwardsUOffset<&str>>(
                "clueType",
                Self::VT_CLUETYPE,
                false,
            )?
            .visit_field::<i32>("number", Self::VT_NUMBER, false)?
            .finish();
        Ok(())
    }
}
pub struct clz_Torappu_MeetingClueData_ClueDataArgs<'a> {
    pub clueId: Option<flatbuffers::WIPOffset<&'a str>>,
    pub clueName: Option<flatbuffers::WIPOffset<&'a str>>,
    pub clueType: Option<flatbuffers::WIPOffset<&'a str>>,
    pub number: i32,
}
impl<'a> Default for clz_Torappu_MeetingClueData_ClueDataArgs<'a> {
    #[inline]
    fn default() -> Self {
        clz_Torappu_MeetingClueData_ClueDataArgs {
            clueId: None,
            clueName: None,
            clueType: None,
            number: 0,
        }
    }
}

pub struct clz_Torappu_MeetingClueData_ClueDataBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
    fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a>
    clz_Torappu_MeetingClueData_ClueDataBuilder<'a, 'b, A>
{
    #[inline]
    pub fn add_clueId(&mut self, clueId: flatbuffers::WIPOffset<&'b str>) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            clz_Torappu_MeetingClueData_ClueData::VT_CLUEID,
            clueId,
        );
    }
    #[inline]
    pub fn add_clueName(&mut self, clueName: flatbuffers::WIPOffset<&'b str>) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            clz_Torappu_MeetingClueData_ClueData::VT_CLUENAME,
            clueName,
        );
    }
    #[inline]
    pub fn add_clueType(&mut self, clueType: flatbuffers::WIPOffset<&'b str>) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            clz_Torappu_MeetingClueData_ClueData::VT_CLUETYPE,
            clueType,
        );
    }
    #[inline]
    pub fn add_number(&mut self, number: i32) {
        self.fbb_
            .push_slot::<i32>(clz_Torappu_MeetingClueData_ClueData::VT_NUMBER, number, 0);
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> clz_Torappu_MeetingClueData_ClueDataBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        clz_Torappu_MeetingClueData_ClueDataBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> flatbuffers::WIPOffset<clz_Torappu_MeetingClueData_ClueData<'a>> {
        let o = self.fbb_.end_table(self.start_);
        flatbuffers::WIPOffset::new(o.value())
    }
}

impl core::fmt::Debug for clz_Torappu_MeetingClueData_ClueData<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut ds = f.debug_struct("clz_Torappu_MeetingClueData_ClueData");
        ds.field("clueId", &self.clueId());
        ds.field("clueName", &self.clueName());
        ds.field("clueType", &self.clueType());
        ds.field("number", &self.number());
        ds.finish()
    }
}
pub enum clz_Torappu_MeetingClueData_ClueTypeDataOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct clz_Torappu_MeetingClueData_ClueTypeData<'a> {
    pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for clz_Torappu_MeetingClueData_ClueTypeData<'a> {
    type Inner = clz_Torappu_MeetingClueData_ClueTypeData<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table::new(buf, loc),
        }
    }
}

impl<'a> clz_Torappu_MeetingClueData_ClueTypeData<'a> {
    pub const VT_CLUETYPE: flatbuffers::VOffsetT = 4;
    pub const VT_CLUENUMBER: flatbuffers::VOffsetT = 6;

    #[inline]
    pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        clz_Torappu_MeetingClueData_ClueTypeData { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args clz_Torappu_MeetingClueData_ClueTypeDataArgs<'args>,
    ) -> flatbuffers::WIPOffset<clz_Torappu_MeetingClueData_ClueTypeData<'bldr>> {
        let mut builder = clz_Torappu_MeetingClueData_ClueTypeDataBuilder::new(_fbb);
        builder.add_clueNumber(args.clueNumber);
        if let Some(x) = args.clueType {
            builder.add_clueType(x);
        }
        builder.finish()
    }

    #[inline]
    pub fn clueType(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(
                clz_Torappu_MeetingClueData_ClueTypeData::VT_CLUETYPE,
                None,
            )
        }
    }
    #[inline]
    pub fn clueNumber(&self) -> i32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<i32>(
                    clz_Torappu_MeetingClueData_ClueTypeData::VT_CLUENUMBER,
                    Some(0),
                )
                .unwrap()
        }
    }
}

impl flatbuffers::Verifiable for clz_Torappu_MeetingClueData_ClueTypeData<'_> {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        use self::flatbuffers::Verifiable;
        v.visit_table(pos)?
            .visit_field::<flatbuffers::ForwardsUOffset<&str>>(
                "clueType",
                Self::VT_CLUETYPE,
                false,
            )?
            .visit_field::<i32>("clueNumber", Self::VT_CLUENUMBER, false)?
            .finish();
        Ok(())
    }
}
pub struct clz_Torappu_MeetingClueData_ClueTypeDataArgs<'a> {
    pub clueType: Option<flatbuffers::WIPOffset<&'a str>>,
    pub clueNumber: i32,
}
impl<'a> Default for clz_Torappu_MeetingClueData_ClueTypeDataArgs<'a> {
    #[inline]
    fn default() -> Self {
        clz_Torappu_MeetingClueData_ClueTypeDataArgs {
            clueType: None,
            clueNumber: 0,
        }
    }
}

pub struct clz_Torappu_MeetingClueData_ClueTypeDataBuilder<
    'a: 'b,
    'b,
    A: flatbuffers::Allocator + 'a,
> {
    fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a>
    clz_Torappu_MeetingClueData_ClueTypeDataBuilder<'a, 'b, A>
{
    #[inline]
    pub fn add_clueType(&mut self, clueType: flatbuffers::WIPOffset<&'b str>) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            clz_Torappu_MeetingClueData_ClueTypeData::VT_CLUETYPE,
            clueType,
        );
    }
    #[inline]
    pub fn add_clueNumber(&mut self, clueNumber: i32) {
        self.fbb_.push_slot::<i32>(
            clz_Torappu_MeetingClueData_ClueTypeData::VT_CLUENUMBER,
            clueNumber,
            0,
        );
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> clz_Torappu_MeetingClueData_ClueTypeDataBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        clz_Torappu_MeetingClueData_ClueTypeDataBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> flatbuffers::WIPOffset<clz_Torappu_MeetingClueData_ClueTypeData<'a>> {
        let o = self.fbb_.end_table(self.start_);
        flatbuffers::WIPOffset::new(o.value())
    }
}

impl core::fmt::Debug for clz_Torappu_MeetingClueData_ClueTypeData<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut ds = f.debug_struct("clz_Torappu_MeetingClueData_ClueTypeData");
        ds.field("clueType", &self.clueType());
        ds.field("clueNumber", &self.clueNumber());
        ds.finish()
    }
}
pub enum clz_Torappu_MeetingClueData_ReceiveTimeBonusOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct clz_Torappu_MeetingClueData_ReceiveTimeBonus<'a> {
    pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for clz_Torappu_MeetingClueData_ReceiveTimeBonus<'a> {
    type Inner = clz_Torappu_MeetingClueData_ReceiveTimeBonus<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table::new(buf, loc),
        }
    }
}

impl<'a> clz_Torappu_MeetingClueData_ReceiveTimeBonus<'a> {
    pub const VT_RECEIVETIMES: flatbuffers::VOffsetT = 4;
    pub const VT_RECEIVEBONUS: flatbuffers::VOffsetT = 6;

    #[inline]
    pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        clz_Torappu_MeetingClueData_ReceiveTimeBonus { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args clz_Torappu_MeetingClueData_ReceiveTimeBonusArgs,
    ) -> flatbuffers::WIPOffset<clz_Torappu_MeetingClueData_ReceiveTimeBonus<'bldr>> {
        let mut builder = clz_Torappu_MeetingClueData_ReceiveTimeBonusBuilder::new(_fbb);
        builder.add_receiveBonus(args.receiveBonus);
        builder.add_receiveTimes(args.receiveTimes);
        builder.finish()
    }

    #[inline]
    pub fn receiveTimes(&self) -> i32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<i32>(
                    clz_Torappu_MeetingClueData_ReceiveTimeBonus::VT_RECEIVETIMES,
                    Some(0),
                )
                .unwrap()
        }
    }
    #[inline]
    pub fn receiveBonus(&self) -> i32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<i32>(
                    clz_Torappu_MeetingClueData_ReceiveTimeBonus::VT_RECEIVEBONUS,
                    Some(0),
                )
                .unwrap()
        }
    }
}

impl flatbuffers::Verifiable for clz_Torappu_MeetingClueData_ReceiveTimeBonus<'_> {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        use self::flatbuffers::Verifiable;
        v.visit_table(pos)?
            .visit_field::<i32>("receiveTimes", Self::VT_RECEIVETIMES, false)?
            .visit_field::<i32>("receiveBonus", Self::VT_RECEIVEBONUS, false)?
            .finish();
        Ok(())
    }
}
pub struct clz_Torappu_MeetingClueData_ReceiveTimeBonusArgs {
    pub receiveTimes: i32,
    pub receiveBonus: i32,
}
impl<'a> Default for clz_Torappu_MeetingClueData_ReceiveTimeBonusArgs {
    #[inline]
    fn default() -> Self {
        clz_Torappu_MeetingClueData_ReceiveTimeBonusArgs {
            receiveTimes: 0,
            receiveBonus: 0,
        }
    }
}

pub struct clz_Torappu_MeetingClueData_ReceiveTimeBonusBuilder<
    'a: 'b,
    'b,
    A: flatbuffers::Allocator + 'a,
> {
    fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a>
    clz_Torappu_MeetingClueData_ReceiveTimeBonusBuilder<'a, 'b, A>
{
    #[inline]
    pub fn add_receiveTimes(&mut self, receiveTimes: i32) {
        self.fbb_.push_slot::<i32>(
            clz_Torappu_MeetingClueData_ReceiveTimeBonus::VT_RECEIVETIMES,
            receiveTimes,
            0,
        );
    }
    #[inline]
    pub fn add_receiveBonus(&mut self, receiveBonus: i32) {
        self.fbb_.push_slot::<i32>(
            clz_Torappu_MeetingClueData_ReceiveTimeBonus::VT_RECEIVEBONUS,
            receiveBonus,
            0,
        );
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> clz_Torappu_MeetingClueData_ReceiveTimeBonusBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        clz_Torappu_MeetingClueData_ReceiveTimeBonusBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(
        self,
    ) -> flatbuffers::WIPOffset<clz_Torappu_MeetingClueData_ReceiveTimeBonus<'a>> {
        let o = self.fbb_.end_table(self.start_);
        flatbuffers::WIPOffset::new(o.value())
    }
}

impl core::fmt::Debug for clz_Torappu_MeetingClueData_ReceiveTimeBonus<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut ds = f.debug_struct("clz_Torappu_MeetingClueData_ReceiveTimeBonus");
        ds.field("receiveTimes", &self.receiveTimes());
        ds.field("receiveBonus", &self.receiveBonus());
        ds.finish()
    }
}
pub enum clz_Torappu_MeetingClueData_MessageLeaveBoardConstDataOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct clz_Torappu_MeetingClueData_MessageLeaveBoardConstData<'a> {
    pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for clz_Torappu_MeetingClueData_MessageLeaveBoardConstData<'a> {
    type Inner = clz_Torappu_MeetingClueData_MessageLeaveBoardConstData<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table::new(buf, loc),
        }
    }
}

impl<'a> clz_Torappu_MeetingClueData_MessageLeaveBoardConstData<'a> {
    pub const VT_VISITORBONUS: flatbuffers::VOffsetT = 4;
    pub const VT_VISITORBONUSLIMIT: flatbuffers::VOffsetT = 6;
    pub const VT_VISITORTOWEEK: flatbuffers::VOffsetT = 8;
    pub const VT_VISITORPREWEEK: flatbuffers::VOffsetT = 10;
    pub const VT_BONUSTOAST: flatbuffers::VOffsetT = 12;
    pub const VT_BONUSLIMITTEXT: flatbuffers::VOffsetT = 14;
    pub const VT_RECORDSTEXTBONUS: flatbuffers::VOffsetT = 16;
    pub const VT_RECORDSTEXTTIP: flatbuffers::VOffsetT = 18;

    #[inline]
    pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        clz_Torappu_MeetingClueData_MessageLeaveBoardConstData { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args clz_Torappu_MeetingClueData_MessageLeaveBoardConstDataArgs<'args>,
    ) -> flatbuffers::WIPOffset<clz_Torappu_MeetingClueData_MessageLeaveBoardConstData<'bldr>> {
        let mut builder = clz_Torappu_MeetingClueData_MessageLeaveBoardConstDataBuilder::new(_fbb);
        if let Some(x) = args.recordsTextTip {
            builder.add_recordsTextTip(x);
        }
        if let Some(x) = args.recordsTextBonus {
            builder.add_recordsTextBonus(x);
        }
        if let Some(x) = args.bonusLimitText {
            builder.add_bonusLimitText(x);
        }
        if let Some(x) = args.bonusToast {
            builder.add_bonusToast(x);
        }
        builder.add_visitorPreWeek(args.visitorPreWeek);
        builder.add_visitorToWeek(args.visitorToWeek);
        builder.add_visitorBonusLimit(args.visitorBonusLimit);
        builder.add_visitorBonus(args.visitorBonus);
        builder.finish()
    }

    #[inline]
    pub fn visitorBonus(&self) -> i32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<i32>(
                    clz_Torappu_MeetingClueData_MessageLeaveBoardConstData::VT_VISITORBONUS,
                    Some(0),
                )
                .unwrap()
        }
    }
    #[inline]
    pub fn visitorBonusLimit(&self) -> i32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<i32>(
                    clz_Torappu_MeetingClueData_MessageLeaveBoardConstData::VT_VISITORBONUSLIMIT,
                    Some(0),
                )
                .unwrap()
        }
    }
    #[inline]
    pub fn visitorToWeek(&self) -> i32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<i32>(
                    clz_Torappu_MeetingClueData_MessageLeaveBoardConstData::VT_VISITORTOWEEK,
                    Some(0),
                )
                .unwrap()
        }
    }
    #[inline]
    pub fn visitorPreWeek(&self) -> i32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<i32>(
                    clz_Torappu_MeetingClueData_MessageLeaveBoardConstData::VT_VISITORPREWEEK,
                    Some(0),
                )
                .unwrap()
        }
    }
    #[inline]
    pub fn bonusToast(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(
                clz_Torappu_MeetingClueData_MessageLeaveBoardConstData::VT_BONUSTOAST,
                None,
            )
        }
    }
    #[inline]
    pub fn bonusLimitText(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(
                clz_Torappu_MeetingClueData_MessageLeaveBoardConstData::VT_BONUSLIMITTEXT,
                None,
            )
        }
    }
    #[inline]
    pub fn recordsTextBonus(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(
                clz_Torappu_MeetingClueData_MessageLeaveBoardConstData::VT_RECORDSTEXTBONUS,
                None,
            )
        }
    }
    #[inline]
    pub fn recordsTextTip(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(
                clz_Torappu_MeetingClueData_MessageLeaveBoardConstData::VT_RECORDSTEXTTIP,
                None,
            )
        }
    }
}

impl flatbuffers::Verifiable for clz_Torappu_MeetingClueData_MessageLeaveBoardConstData<'_> {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        use self::flatbuffers::Verifiable;
        v.visit_table(pos)?
            .visit_field::<i32>("visitorBonus", Self::VT_VISITORBONUS, false)?
            .visit_field::<i32>("visitorBonusLimit", Self::VT_VISITORBONUSLIMIT, false)?
            .visit_field::<i32>("visitorToWeek", Self::VT_VISITORTOWEEK, false)?
            .visit_field::<i32>("visitorPreWeek", Self::VT_VISITORPREWEEK, false)?
            .visit_field::<flatbuffers::ForwardsUOffset<&str>>(
                "bonusToast",
                Self::VT_BONUSTOAST,
                false,
            )?
            .visit_field::<flatbuffers::ForwardsUOffset<&str>>(
                "bonusLimitText",
                Self::VT_BONUSLIMITTEXT,
                false,
            )?
            .visit_field::<flatbuffers::ForwardsUOffset<&str>>(
                "recordsTextBonus",
                Self::VT_RECORDSTEXTBONUS,
                false,
            )?
            .visit_field::<flatbuffers::ForwardsUOffset<&str>>(
                "recordsTextTip",
                Self::VT_RECORDSTEXTTIP,
                false,
            )?
            .finish();
        Ok(())
    }
}
pub struct clz_Torappu_MeetingClueData_MessageLeaveBoardConstDataArgs<'a> {
    pub visitorBonus: i32,
    pub visitorBonusLimit: i32,
    pub visitorToWeek: i32,
    pub visitorPreWeek: i32,
    pub bonusToast: Option<flatbuffers::WIPOffset<&'a str>>,
    pub bonusLimitText: Option<flatbuffers::WIPOffset<&'a str>>,
    pub recordsTextBonus: Option<flatbuffers::WIPOffset<&'a str>>,
    pub recordsTextTip: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for clz_Torappu_MeetingClueData_MessageLeaveBoardConstDataArgs<'a> {
    #[inline]
    fn default() -> Self {
        clz_Torappu_MeetingClueData_MessageLeaveBoardConstDataArgs {
            visitorBonus: 0,
            visitorBonusLimit: 0,
            visitorToWeek: 0,
            visitorPreWeek: 0,
            bonusToast: None,
            bonusLimitText: None,
            recordsTextBonus: None,
            recordsTextTip: None,
        }
    }
}

pub struct clz_Torappu_MeetingClueData_MessageLeaveBoardConstDataBuilder<
    'a: 'b,
    'b,
    A: flatbuffers::Allocator + 'a,
> {
    fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a>
    clz_Torappu_MeetingClueData_MessageLeaveBoardConstDataBuilder<'a, 'b, A>
{
    #[inline]
    pub fn add_visitorBonus(&mut self, visitorBonus: i32) {
        self.fbb_.push_slot::<i32>(
            clz_Torappu_MeetingClueData_MessageLeaveBoardConstData::VT_VISITORBONUS,
            visitorBonus,
            0,
        );
    }
    #[inline]
    pub fn add_visitorBonusLimit(&mut self, visitorBonusLimit: i32) {
        self.fbb_.push_slot::<i32>(
            clz_Torappu_MeetingClueData_MessageLeaveBoardConstData::VT_VISITORBONUSLIMIT,
            visitorBonusLimit,
            0,
        );
    }
    #[inline]
    pub fn add_visitorToWeek(&mut self, visitorToWeek: i32) {
        self.fbb_.push_slot::<i32>(
            clz_Torappu_MeetingClueData_MessageLeaveBoardConstData::VT_VISITORTOWEEK,
            visitorToWeek,
            0,
        );
    }
    #[inline]
    pub fn add_visitorPreWeek(&mut self, visitorPreWeek: i32) {
        self.fbb_.push_slot::<i32>(
            clz_Torappu_MeetingClueData_MessageLeaveBoardConstData::VT_VISITORPREWEEK,
            visitorPreWeek,
            0,
        );
    }
    #[inline]
    pub fn add_bonusToast(&mut self, bonusToast: flatbuffers::WIPOffset<&'b str>) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            clz_Torappu_MeetingClueData_MessageLeaveBoardConstData::VT_BONUSTOAST,
            bonusToast,
        );
    }
    #[inline]
    pub fn add_bonusLimitText(&mut self, bonusLimitText: flatbuffers::WIPOffset<&'b str>) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            clz_Torappu_MeetingClueData_MessageLeaveBoardConstData::VT_BONUSLIMITTEXT,
            bonusLimitText,
        );
    }
    #[inline]
    pub fn add_recordsTextBonus(&mut self, recordsTextBonus: flatbuffers::WIPOffset<&'b str>) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            clz_Torappu_MeetingClueData_MessageLeaveBoardConstData::VT_RECORDSTEXTBONUS,
            recordsTextBonus,
        );
    }
    #[inline]
    pub fn add_recordsTextTip(&mut self, recordsTextTip: flatbuffers::WIPOffset<&'b str>) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            clz_Torappu_MeetingClueData_MessageLeaveBoardConstData::VT_RECORDSTEXTTIP,
            recordsTextTip,
        );
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> clz_Torappu_MeetingClueData_MessageLeaveBoardConstDataBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        clz_Torappu_MeetingClueData_MessageLeaveBoardConstDataBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(
        self,
    ) -> flatbuffers::WIPOffset<clz_Torappu_MeetingClueData_MessageLeaveBoardConstData<'a>> {
        let o = self.fbb_.end_table(self.start_);
        flatbuffers::WIPOffset::new(o.value())
    }
}

impl core::fmt::Debug for clz_Torappu_MeetingClueData_MessageLeaveBoardConstData<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut ds = f.debug_struct("clz_Torappu_MeetingClueData_MessageLeaveBoardConstData");
        ds.field("visitorBonus", &self.visitorBonus());
        ds.field("visitorBonusLimit", &self.visitorBonusLimit());
        ds.field("visitorToWeek", &self.visitorToWeek());
        ds.field("visitorPreWeek", &self.visitorPreWeek());
        ds.field("bonusToast", &self.bonusToast());
        ds.field("bonusLimitText", &self.bonusLimitText());
        ds.field("recordsTextBonus", &self.recordsTextBonus());
        ds.field("recordsTextTip", &self.recordsTextTip());
        ds.finish()
    }
}
pub enum clz_Torappu_MeetingClueDataOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct clz_Torappu_MeetingClueData<'a> {
    pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for clz_Torappu_MeetingClueData<'a> {
    type Inner = clz_Torappu_MeetingClueData<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table::new(buf, loc),
        }
    }
}

impl<'a> clz_Torappu_MeetingClueData<'a> {
    pub const VT_CLUES: flatbuffers::VOffsetT = 4;
    pub const VT_CLUETYPES: flatbuffers::VOffsetT = 6;
    pub const VT_RECEIVETIMEBONUS: flatbuffers::VOffsetT = 8;
    pub const VT_MESSAGELEAVEBOARDCONSTDATA: flatbuffers::VOffsetT = 10;
    pub const VT_INVENTORYLIMIT: flatbuffers::VOffsetT = 12;
    pub const VT_OUTPUTBASICBONUS: flatbuffers::VOffsetT = 14;
    pub const VT_OUTPUTOPERATORSBONUS: flatbuffers::VOffsetT = 16;
    pub const VT_CLUEPOINTLIMIT: flatbuffers::VOffsetT = 18;
    pub const VT_EXPIREDDAYS: flatbuffers::VOffsetT = 20;
    pub const VT_TRANSFERBONUS: flatbuffers::VOffsetT = 22;
    pub const VT_RECYCLEBONUS: flatbuffers::VOffsetT = 24;
    pub const VT_EXPIREDBONUS: flatbuffers::VOffsetT = 26;
    pub const VT_COMMUNICATIONDURATION: flatbuffers::VOffsetT = 28;
    pub const VT_INITIATORBONUS: flatbuffers::VOffsetT = 30;
    pub const VT_PARTICIPANTSBONUS: flatbuffers::VOffsetT = 32;
    pub const VT_COMMUFOLDDURATION: flatbuffers::VOffsetT = 34;

    #[inline]
    pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        clz_Torappu_MeetingClueData { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args clz_Torappu_MeetingClueDataArgs<'args>,
    ) -> flatbuffers::WIPOffset<clz_Torappu_MeetingClueData<'bldr>> {
        let mut builder = clz_Torappu_MeetingClueDataBuilder::new(_fbb);
        builder.add_commuFoldDuration(args.commuFoldDuration);
        builder.add_participantsBonus(args.participantsBonus);
        builder.add_initiatorBonus(args.initiatorBonus);
        builder.add_communicationDuration(args.communicationDuration);
        builder.add_expiredBonus(args.expiredBonus);
        builder.add_recycleBonus(args.recycleBonus);
        builder.add_transferBonus(args.transferBonus);
        builder.add_expiredDays(args.expiredDays);
        builder.add_cluePointLimit(args.cluePointLimit);
        builder.add_outputOperatorsBonus(args.outputOperatorsBonus);
        builder.add_outputBasicBonus(args.outputBasicBonus);
        builder.add_inventoryLimit(args.inventoryLimit);
        if let Some(x) = args.messageLeaveBoardConstData {
            builder.add_messageLeaveBoardConstData(x);
        }
        if let Some(x) = args.receiveTimeBonus {
            builder.add_receiveTimeBonus(x);
        }
        if let Some(x) = args.clueTypes {
            builder.add_clueTypes(x);
        }
        if let Some(x) = args.clues {
            builder.add_clues(x);
        }
        builder.finish()
    }

    #[inline]
    pub fn clues(
        &self,
    ) -> Option<
        flatbuffers::Vector<
            'a,
            flatbuffers::ForwardsUOffset<clz_Torappu_MeetingClueData_ClueData<'a>>,
        >,
    > {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<
                    'a,
                    flatbuffers::ForwardsUOffset<clz_Torappu_MeetingClueData_ClueData>,
                >,
            >>(clz_Torappu_MeetingClueData::VT_CLUES, None)
        }
    }
    #[inline]
    pub fn clueTypes(
        &self,
    ) -> Option<
        flatbuffers::Vector<
            'a,
            flatbuffers::ForwardsUOffset<clz_Torappu_MeetingClueData_ClueTypeData<'a>>,
        >,
    > {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<
                    'a,
                    flatbuffers::ForwardsUOffset<clz_Torappu_MeetingClueData_ClueTypeData>,
                >,
            >>(clz_Torappu_MeetingClueData::VT_CLUETYPES, None)
        }
    }
    #[inline]
    pub fn receiveTimeBonus(
        &self,
    ) -> Option<
        flatbuffers::Vector<
            'a,
            flatbuffers::ForwardsUOffset<clz_Torappu_MeetingClueData_ReceiveTimeBonus<'a>>,
        >,
    > {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<
                    'a,
                    flatbuffers::ForwardsUOffset<clz_Torappu_MeetingClueData_ReceiveTimeBonus>,
                >,
            >>(clz_Torappu_MeetingClueData::VT_RECEIVETIMEBONUS, None)
        }
    }
    #[inline]
    pub fn messageLeaveBoardConstData(
        &self,
    ) -> Option<clz_Torappu_MeetingClueData_MessageLeaveBoardConstData<'a>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<
                clz_Torappu_MeetingClueData_MessageLeaveBoardConstData,
            >>(
                clz_Torappu_MeetingClueData::VT_MESSAGELEAVEBOARDCONSTDATA,
                None,
            )
        }
    }
    #[inline]
    pub fn inventoryLimit(&self) -> i32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<i32>(clz_Torappu_MeetingClueData::VT_INVENTORYLIMIT, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn outputBasicBonus(&self) -> i32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<i32>(clz_Torappu_MeetingClueData::VT_OUTPUTBASICBONUS, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn outputOperatorsBonus(&self) -> i32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<i32>(
                    clz_Torappu_MeetingClueData::VT_OUTPUTOPERATORSBONUS,
                    Some(0),
                )
                .unwrap()
        }
    }
    #[inline]
    pub fn cluePointLimit(&self) -> i32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<i32>(clz_Torappu_MeetingClueData::VT_CLUEPOINTLIMIT, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn expiredDays(&self) -> i32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<i32>(clz_Torappu_MeetingClueData::VT_EXPIREDDAYS, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn transferBonus(&self) -> i32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<i32>(clz_Torappu_MeetingClueData::VT_TRANSFERBONUS, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn recycleBonus(&self) -> i32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<i32>(clz_Torappu_MeetingClueData::VT_RECYCLEBONUS, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn expiredBonus(&self) -> i32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<i32>(clz_Torappu_MeetingClueData::VT_EXPIREDBONUS, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn communicationDuration(&self) -> i32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<i32>(
                    clz_Torappu_MeetingClueData::VT_COMMUNICATIONDURATION,
                    Some(0),
                )
                .unwrap()
        }
    }
    #[inline]
    pub fn initiatorBonus(&self) -> i32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<i32>(clz_Torappu_MeetingClueData::VT_INITIATORBONUS, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn participantsBonus(&self) -> i32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<i32>(clz_Torappu_MeetingClueData::VT_PARTICIPANTSBONUS, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn commuFoldDuration(&self) -> f32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<f32>(clz_Torappu_MeetingClueData::VT_COMMUFOLDDURATION, Some(0.0))
                .unwrap()
        }
    }
}

impl flatbuffers::Verifiable for clz_Torappu_MeetingClueData<'_> {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        use self::flatbuffers::Verifiable;
        v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<clz_Torappu_MeetingClueData_ClueData>>>>("clues", Self::VT_CLUES, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<clz_Torappu_MeetingClueData_ClueTypeData>>>>("clueTypes", Self::VT_CLUETYPES, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<clz_Torappu_MeetingClueData_ReceiveTimeBonus>>>>("receiveTimeBonus", Self::VT_RECEIVETIMEBONUS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<clz_Torappu_MeetingClueData_MessageLeaveBoardConstData>>("messageLeaveBoardConstData", Self::VT_MESSAGELEAVEBOARDCONSTDATA, false)?
     .visit_field::<i32>("inventoryLimit", Self::VT_INVENTORYLIMIT, false)?
     .visit_field::<i32>("outputBasicBonus", Self::VT_OUTPUTBASICBONUS, false)?
     .visit_field::<i32>("outputOperatorsBonus", Self::VT_OUTPUTOPERATORSBONUS, false)?
     .visit_field::<i32>("cluePointLimit", Self::VT_CLUEPOINTLIMIT, false)?
     .visit_field::<i32>("expiredDays", Self::VT_EXPIREDDAYS, false)?
     .visit_field::<i32>("transferBonus", Self::VT_TRANSFERBONUS, false)?
     .visit_field::<i32>("recycleBonus", Self::VT_RECYCLEBONUS, false)?
     .visit_field::<i32>("expiredBonus", Self::VT_EXPIREDBONUS, false)?
     .visit_field::<i32>("communicationDuration", Self::VT_COMMUNICATIONDURATION, false)?
     .visit_field::<i32>("initiatorBonus", Self::VT_INITIATORBONUS, false)?
     .visit_field::<i32>("participantsBonus", Self::VT_PARTICIPANTSBONUS, false)?
     .visit_field::<f32>("commuFoldDuration", Self::VT_COMMUFOLDDURATION, false)?
     .finish();
        Ok(())
    }
}
pub struct clz_Torappu_MeetingClueDataArgs<'a> {
    pub clues: Option<
        flatbuffers::WIPOffset<
            flatbuffers::Vector<
                'a,
                flatbuffers::ForwardsUOffset<clz_Torappu_MeetingClueData_ClueData<'a>>,
            >,
        >,
    >,
    pub clueTypes: Option<
        flatbuffers::WIPOffset<
            flatbuffers::Vector<
                'a,
                flatbuffers::ForwardsUOffset<clz_Torappu_MeetingClueData_ClueTypeData<'a>>,
            >,
        >,
    >,
    pub receiveTimeBonus: Option<
        flatbuffers::WIPOffset<
            flatbuffers::Vector<
                'a,
                flatbuffers::ForwardsUOffset<clz_Torappu_MeetingClueData_ReceiveTimeBonus<'a>>,
            >,
        >,
    >,
    pub messageLeaveBoardConstData:
        Option<flatbuffers::WIPOffset<clz_Torappu_MeetingClueData_MessageLeaveBoardConstData<'a>>>,
    pub inventoryLimit: i32,
    pub outputBasicBonus: i32,
    pub outputOperatorsBonus: i32,
    pub cluePointLimit: i32,
    pub expiredDays: i32,
    pub transferBonus: i32,
    pub recycleBonus: i32,
    pub expiredBonus: i32,
    pub communicationDuration: i32,
    pub initiatorBonus: i32,
    pub participantsBonus: i32,
    pub commuFoldDuration: f32,
}
impl<'a> Default for clz_Torappu_MeetingClueDataArgs<'a> {
    #[inline]
    fn default() -> Self {
        clz_Torappu_MeetingClueDataArgs {
            clues: None,
            clueTypes: None,
            receiveTimeBonus: None,
            messageLeaveBoardConstData: None,
            inventoryLimit: 0,
            outputBasicBonus: 0,
            outputOperatorsBonus: 0,
            cluePointLimit: 0,
            expiredDays: 0,
            transferBonus: 0,
            recycleBonus: 0,
            expiredBonus: 0,
            communicationDuration: 0,
            initiatorBonus: 0,
            participantsBonus: 0,
            commuFoldDuration: 0.0,
        }
    }
}

pub struct clz_Torappu_MeetingClueDataBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
    fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> clz_Torappu_MeetingClueDataBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_clues(
        &mut self,
        clues: flatbuffers::WIPOffset<
            flatbuffers::Vector<
                'b,
                flatbuffers::ForwardsUOffset<clz_Torappu_MeetingClueData_ClueData<'b>>,
            >,
        >,
    ) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            clz_Torappu_MeetingClueData::VT_CLUES,
            clues,
        );
    }
    #[inline]
    pub fn add_clueTypes(
        &mut self,
        clueTypes: flatbuffers::WIPOffset<
            flatbuffers::Vector<
                'b,
                flatbuffers::ForwardsUOffset<clz_Torappu_MeetingClueData_ClueTypeData<'b>>,
            >,
        >,
    ) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            clz_Torappu_MeetingClueData::VT_CLUETYPES,
            clueTypes,
        );
    }
    #[inline]
    pub fn add_receiveTimeBonus(
        &mut self,
        receiveTimeBonus: flatbuffers::WIPOffset<
            flatbuffers::Vector<
                'b,
                flatbuffers::ForwardsUOffset<clz_Torappu_MeetingClueData_ReceiveTimeBonus<'b>>,
            >,
        >,
    ) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            clz_Torappu_MeetingClueData::VT_RECEIVETIMEBONUS,
            receiveTimeBonus,
        );
    }
    #[inline]
    pub fn add_messageLeaveBoardConstData(
        &mut self,
        messageLeaveBoardConstData: flatbuffers::WIPOffset<
            clz_Torappu_MeetingClueData_MessageLeaveBoardConstData<'b>,
        >,
    ) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<clz_Torappu_MeetingClueData_MessageLeaveBoardConstData>>(clz_Torappu_MeetingClueData::VT_MESSAGELEAVEBOARDCONSTDATA, messageLeaveBoardConstData);
    }
    #[inline]
    pub fn add_inventoryLimit(&mut self, inventoryLimit: i32) {
        self.fbb_.push_slot::<i32>(
            clz_Torappu_MeetingClueData::VT_INVENTORYLIMIT,
            inventoryLimit,
            0,
        );
    }
    #[inline]
    pub fn add_outputBasicBonus(&mut self, outputBasicBonus: i32) {
        self.fbb_.push_slot::<i32>(
            clz_Torappu_MeetingClueData::VT_OUTPUTBASICBONUS,
            outputBasicBonus,
            0,
        );
    }
    #[inline]
    pub fn add_outputOperatorsBonus(&mut self, outputOperatorsBonus: i32) {
        self.fbb_.push_slot::<i32>(
            clz_Torappu_MeetingClueData::VT_OUTPUTOPERATORSBONUS,
            outputOperatorsBonus,
            0,
        );
    }
    #[inline]
    pub fn add_cluePointLimit(&mut self, cluePointLimit: i32) {
        self.fbb_.push_slot::<i32>(
            clz_Torappu_MeetingClueData::VT_CLUEPOINTLIMIT,
            cluePointLimit,
            0,
        );
    }
    #[inline]
    pub fn add_expiredDays(&mut self, expiredDays: i32) {
        self.fbb_
            .push_slot::<i32>(clz_Torappu_MeetingClueData::VT_EXPIREDDAYS, expiredDays, 0);
    }
    #[inline]
    pub fn add_transferBonus(&mut self, transferBonus: i32) {
        self.fbb_.push_slot::<i32>(
            clz_Torappu_MeetingClueData::VT_TRANSFERBONUS,
            transferBonus,
            0,
        );
    }
    #[inline]
    pub fn add_recycleBonus(&mut self, recycleBonus: i32) {
        self.fbb_.push_slot::<i32>(
            clz_Torappu_MeetingClueData::VT_RECYCLEBONUS,
            recycleBonus,
            0,
        );
    }
    #[inline]
    pub fn add_expiredBonus(&mut self, expiredBonus: i32) {
        self.fbb_.push_slot::<i32>(
            clz_Torappu_MeetingClueData::VT_EXPIREDBONUS,
            expiredBonus,
            0,
        );
    }
    #[inline]
    pub fn add_communicationDuration(&mut self, communicationDuration: i32) {
        self.fbb_.push_slot::<i32>(
            clz_Torappu_MeetingClueData::VT_COMMUNICATIONDURATION,
            communicationDuration,
            0,
        );
    }
    #[inline]
    pub fn add_initiatorBonus(&mut self, initiatorBonus: i32) {
        self.fbb_.push_slot::<i32>(
            clz_Torappu_MeetingClueData::VT_INITIATORBONUS,
            initiatorBonus,
            0,
        );
    }
    #[inline]
    pub fn add_participantsBonus(&mut self, participantsBonus: i32) {
        self.fbb_.push_slot::<i32>(
            clz_Torappu_MeetingClueData::VT_PARTICIPANTSBONUS,
            participantsBonus,
            0,
        );
    }
    #[inline]
    pub fn add_commuFoldDuration(&mut self, commuFoldDuration: f32) {
        self.fbb_.push_slot::<f32>(
            clz_Torappu_MeetingClueData::VT_COMMUFOLDDURATION,
            commuFoldDuration,
            0.0,
        );
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> clz_Torappu_MeetingClueDataBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        clz_Torappu_MeetingClueDataBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> flatbuffers::WIPOffset<clz_Torappu_MeetingClueData<'a>> {
        let o = self.fbb_.end_table(self.start_);
        flatbuffers::WIPOffset::new(o.value())
    }
}

impl core::fmt::Debug for clz_Torappu_MeetingClueData<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut ds = f.debug_struct("clz_Torappu_MeetingClueData");
        ds.field("clues", &self.clues());
        ds.field("clueTypes", &self.clueTypes());
        ds.field("receiveTimeBonus", &self.receiveTimeBonus());
        ds.field(
            "messageLeaveBoardConstData",
            &self.messageLeaveBoardConstData(),
        );
        ds.field("inventoryLimit", &self.inventoryLimit());
        ds.field("outputBasicBonus", &self.outputBasicBonus());
        ds.field("outputOperatorsBonus", &self.outputOperatorsBonus());
        ds.field("cluePointLimit", &self.cluePointLimit());
        ds.field("expiredDays", &self.expiredDays());
        ds.field("transferBonus", &self.transferBonus());
        ds.field("recycleBonus", &self.recycleBonus());
        ds.field("expiredBonus", &self.expiredBonus());
        ds.field("communicationDuration", &self.communicationDuration());
        ds.field("initiatorBonus", &self.initiatorBonus());
        ds.field("participantsBonus", &self.participantsBonus());
        ds.field("commuFoldDuration", &self.commuFoldDuration());
        ds.finish()
    }
}
#[inline]
/// Verifies that a buffer of bytes contains a `clz_Torappu_MeetingClueData`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_clz_torappu_meeting_clue_data_unchecked`.
pub fn root_as_clz_torappu_meeting_clue_data(
    buf: &[u8],
) -> Result<clz_Torappu_MeetingClueData, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::root::<clz_Torappu_MeetingClueData>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `clz_Torappu_MeetingClueData` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_clz_torappu_meeting_clue_data_unchecked`.
pub fn size_prefixed_root_as_clz_torappu_meeting_clue_data(
    buf: &[u8],
) -> Result<clz_Torappu_MeetingClueData, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::size_prefixed_root::<clz_Torappu_MeetingClueData>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `clz_Torappu_MeetingClueData` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_clz_torappu_meeting_clue_data_unchecked`.
pub fn root_as_clz_torappu_meeting_clue_data_with_opts<'b, 'o>(
    opts: &'o flatbuffers::VerifierOptions,
    buf: &'b [u8],
) -> Result<clz_Torappu_MeetingClueData<'b>, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::root_with_opts::<clz_Torappu_MeetingClueData<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `clz_Torappu_MeetingClueData` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_clz_torappu_meeting_clue_data_unchecked`.
pub fn size_prefixed_root_as_clz_torappu_meeting_clue_data_with_opts<'b, 'o>(
    opts: &'o flatbuffers::VerifierOptions,
    buf: &'b [u8],
) -> Result<clz_Torappu_MeetingClueData<'b>, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::size_prefixed_root_with_opts::<clz_Torappu_MeetingClueData<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a clz_Torappu_MeetingClueData and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `clz_Torappu_MeetingClueData`.
pub unsafe fn root_as_clz_torappu_meeting_clue_data_unchecked(
    buf: &[u8],
) -> clz_Torappu_MeetingClueData {
    flatbuffers::root_unchecked::<clz_Torappu_MeetingClueData>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed clz_Torappu_MeetingClueData and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `clz_Torappu_MeetingClueData`.
pub unsafe fn size_prefixed_root_as_clz_torappu_meeting_clue_data_unchecked(
    buf: &[u8],
) -> clz_Torappu_MeetingClueData {
    flatbuffers::size_prefixed_root_unchecked::<clz_Torappu_MeetingClueData>(buf)
}
#[inline]
pub fn finish_clz_torappu_meeting_clue_data_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<clz_Torappu_MeetingClueData<'a>>,
) {
    fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_clz_torappu_meeting_clue_data_buffer<
    'a,
    'b,
    A: flatbuffers::Allocator + 'a,
>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<clz_Torappu_MeetingClueData<'a>>,
) {
    fbb.finish_size_prefixed(root, None);
}
