// automatically generated by the FlatBuffers compiler, do not modify

// @generated

use core::cmp::Ordering;
use core::mem;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(
    since = "2.0.0",
    note = "Use associated constants instead. This will no longer be generated in 2021."
)]
pub const ENUM_MIN_ENUM__TORAPPU_STORY_DATA_TRIGGER_TRIGGER_TYPE: i32 = 0;
#[deprecated(
    since = "2.0.0",
    note = "Use associated constants instead. This will no longer be generated in 2021."
)]
pub const ENUM_MAX_ENUM__TORAPPU_STORY_DATA_TRIGGER_TRIGGER_TYPE: i32 = 12;
#[deprecated(
    since = "2.0.0",
    note = "Use associated constants instead. This will no longer be generated in 2021."
)]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_ENUM__TORAPPU_STORY_DATA_TRIGGER_TRIGGER_TYPE:
    [enum__Torappu_StoryData_Trigger_TriggerType; 13] = [
    enum__Torappu_StoryData_Trigger_TriggerType::GAME_START,
    enum__Torappu_StoryData_Trigger_TriggerType::BEFORE_BATTLE,
    enum__Torappu_StoryData_Trigger_TriggerType::AFTER_BATTLE,
    enum__Torappu_StoryData_Trigger_TriggerType::SWITCH_TO_SCENE,
    enum__Torappu_StoryData_Trigger_TriggerType::PAGE_LOADED,
    enum__Torappu_StoryData_Trigger_TriggerType::STORY_FINISH,
    enum__Torappu_StoryData_Trigger_TriggerType::CUSTOM_OPERATION,
    enum__Torappu_StoryData_Trigger_TriggerType::STORY_FINISH_OR_PAGE_LOADED,
    enum__Torappu_StoryData_Trigger_TriggerType::ACTIVITY_LOADED,
    enum__Torappu_StoryData_Trigger_TriggerType::ACTIVITY_ANNOUNCE,
    enum__Torappu_StoryData_Trigger_TriggerType::CRISIS_SEASON_LOADED,
    enum__Torappu_StoryData_Trigger_TriggerType::STORY_FINISH_OR_CUSTOM_OPERATION,
    enum__Torappu_StoryData_Trigger_TriggerType::E_NUM,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct enum__Torappu_StoryData_Trigger_TriggerType(pub i32);
#[allow(non_upper_case_globals)]
impl enum__Torappu_StoryData_Trigger_TriggerType {
    pub const GAME_START: Self = Self(0);
    pub const BEFORE_BATTLE: Self = Self(1);
    pub const AFTER_BATTLE: Self = Self(2);
    pub const SWITCH_TO_SCENE: Self = Self(3);
    pub const PAGE_LOADED: Self = Self(4);
    pub const STORY_FINISH: Self = Self(5);
    pub const CUSTOM_OPERATION: Self = Self(6);
    pub const STORY_FINISH_OR_PAGE_LOADED: Self = Self(7);
    pub const ACTIVITY_LOADED: Self = Self(8);
    pub const ACTIVITY_ANNOUNCE: Self = Self(9);
    pub const CRISIS_SEASON_LOADED: Self = Self(10);
    pub const STORY_FINISH_OR_CUSTOM_OPERATION: Self = Self(11);
    pub const E_NUM: Self = Self(12);

    pub const ENUM_MIN: i32 = 0;
    pub const ENUM_MAX: i32 = 12;
    pub const ENUM_VALUES: &'static [Self] = &[
        Self::GAME_START,
        Self::BEFORE_BATTLE,
        Self::AFTER_BATTLE,
        Self::SWITCH_TO_SCENE,
        Self::PAGE_LOADED,
        Self::STORY_FINISH,
        Self::CUSTOM_OPERATION,
        Self::STORY_FINISH_OR_PAGE_LOADED,
        Self::ACTIVITY_LOADED,
        Self::ACTIVITY_ANNOUNCE,
        Self::CRISIS_SEASON_LOADED,
        Self::STORY_FINISH_OR_CUSTOM_OPERATION,
        Self::E_NUM,
    ];
    /// Returns the variant's name or "" if unknown.
    pub fn variant_name(self) -> Option<&'static str> {
        match self {
            Self::GAME_START => Some("GAME_START"),
            Self::BEFORE_BATTLE => Some("BEFORE_BATTLE"),
            Self::AFTER_BATTLE => Some("AFTER_BATTLE"),
            Self::SWITCH_TO_SCENE => Some("SWITCH_TO_SCENE"),
            Self::PAGE_LOADED => Some("PAGE_LOADED"),
            Self::STORY_FINISH => Some("STORY_FINISH"),
            Self::CUSTOM_OPERATION => Some("CUSTOM_OPERATION"),
            Self::STORY_FINISH_OR_PAGE_LOADED => Some("STORY_FINISH_OR_PAGE_LOADED"),
            Self::ACTIVITY_LOADED => Some("ACTIVITY_LOADED"),
            Self::ACTIVITY_ANNOUNCE => Some("ACTIVITY_ANNOUNCE"),
            Self::CRISIS_SEASON_LOADED => Some("CRISIS_SEASON_LOADED"),
            Self::STORY_FINISH_OR_CUSTOM_OPERATION => Some("STORY_FINISH_OR_CUSTOM_OPERATION"),
            Self::E_NUM => Some("E_NUM"),
            _ => None,
        }
    }
}
impl core::fmt::Debug for enum__Torappu_StoryData_Trigger_TriggerType {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        if let Some(name) = self.variant_name() {
            f.write_str(name)
        } else {
            f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
        }
    }
}
impl<'a> flatbuffers::Follow<'a> for enum__Torappu_StoryData_Trigger_TriggerType {
    type Inner = Self;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        let b = flatbuffers::read_scalar_at::<i32>(buf, loc);
        Self(b)
    }
}

impl flatbuffers::Push for enum__Torappu_StoryData_Trigger_TriggerType {
    type Output = enum__Torappu_StoryData_Trigger_TriggerType;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<i32>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for enum__Torappu_StoryData_Trigger_TriggerType {
    type Scalar = i32;
    #[inline]
    fn to_little_endian(self) -> i32 {
        self.0.to_le()
    }
    #[inline]
    #[allow(clippy::wrong_self_convention)]
    fn from_little_endian(v: i32) -> Self {
        let b = i32::from_le(v);
        Self(b)
    }
}

impl<'a> flatbuffers::Verifiable for enum__Torappu_StoryData_Trigger_TriggerType {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        use self::flatbuffers::Verifiable;
        i32::run_verifier(v, pos)
    }
}

impl flatbuffers::SimpleToVerifyInSlice for enum__Torappu_StoryData_Trigger_TriggerType {}
#[deprecated(
    since = "2.0.0",
    note = "Use associated constants instead. This will no longer be generated in 2021."
)]
pub const ENUM_MIN_ENUM__TORAPPU_PLAYER_STAGE_STATE: i32 = 0;
#[deprecated(
    since = "2.0.0",
    note = "Use associated constants instead. This will no longer be generated in 2021."
)]
pub const ENUM_MAX_ENUM__TORAPPU_PLAYER_STAGE_STATE: i32 = 3;
#[deprecated(
    since = "2.0.0",
    note = "Use associated constants instead. This will no longer be generated in 2021."
)]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_ENUM__TORAPPU_PLAYER_STAGE_STATE: [enum__Torappu_PlayerStageState; 4] = [
    enum__Torappu_PlayerStageState::UNLOCKED,
    enum__Torappu_PlayerStageState::PLAYED,
    enum__Torappu_PlayerStageState::PASS,
    enum__Torappu_PlayerStageState::COMPLETE,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct enum__Torappu_PlayerStageState(pub i32);
#[allow(non_upper_case_globals)]
impl enum__Torappu_PlayerStageState {
    pub const UNLOCKED: Self = Self(0);
    pub const PLAYED: Self = Self(1);
    pub const PASS: Self = Self(2);
    pub const COMPLETE: Self = Self(3);

    pub const ENUM_MIN: i32 = 0;
    pub const ENUM_MAX: i32 = 3;
    pub const ENUM_VALUES: &'static [Self] =
        &[Self::UNLOCKED, Self::PLAYED, Self::PASS, Self::COMPLETE];
    /// Returns the variant's name or "" if unknown.
    pub fn variant_name(self) -> Option<&'static str> {
        match self {
            Self::UNLOCKED => Some("UNLOCKED"),
            Self::PLAYED => Some("PLAYED"),
            Self::PASS => Some("PASS"),
            Self::COMPLETE => Some("COMPLETE"),
            _ => None,
        }
    }
}
impl core::fmt::Debug for enum__Torappu_PlayerStageState {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        if let Some(name) = self.variant_name() {
            f.write_str(name)
        } else {
            f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
        }
    }
}
impl<'a> flatbuffers::Follow<'a> for enum__Torappu_PlayerStageState {
    type Inner = Self;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        let b = flatbuffers::read_scalar_at::<i32>(buf, loc);
        Self(b)
    }
}

impl flatbuffers::Push for enum__Torappu_PlayerStageState {
    type Output = enum__Torappu_PlayerStageState;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<i32>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for enum__Torappu_PlayerStageState {
    type Scalar = i32;
    #[inline]
    fn to_little_endian(self) -> i32 {
        self.0.to_le()
    }
    #[inline]
    #[allow(clippy::wrong_self_convention)]
    fn from_little_endian(v: i32) -> Self {
        let b = i32::from_le(v);
        Self(b)
    }
}

impl<'a> flatbuffers::Verifiable for enum__Torappu_PlayerStageState {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        use self::flatbuffers::Verifiable;
        i32::run_verifier(v, pos)
    }
}

impl flatbuffers::SimpleToVerifyInSlice for enum__Torappu_PlayerStageState {}
#[deprecated(
    since = "2.0.0",
    note = "Use associated constants instead. This will no longer be generated in 2021."
)]
pub const ENUM_MIN_ENUM__TORAPPU_ITEM_TYPE: i32 = 0;
#[deprecated(
    since = "2.0.0",
    note = "Use associated constants instead. This will no longer be generated in 2021."
)]
pub const ENUM_MAX_ENUM__TORAPPU_ITEM_TYPE: i32 = 90;
#[deprecated(
    since = "2.0.0",
    note = "Use associated constants instead. This will no longer be generated in 2021."
)]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_ENUM__TORAPPU_ITEM_TYPE: [enum__Torappu_ItemType; 91] = [
    enum__Torappu_ItemType::NONE,
    enum__Torappu_ItemType::CHAR,
    enum__Torappu_ItemType::CARD_EXP,
    enum__Torappu_ItemType::MATERIAL,
    enum__Torappu_ItemType::GOLD,
    enum__Torappu_ItemType::EXP_PLAYER,
    enum__Torappu_ItemType::TKT_TRY,
    enum__Torappu_ItemType::TKT_RECRUIT,
    enum__Torappu_ItemType::TKT_INST_FIN,
    enum__Torappu_ItemType::TKT_GACHA,
    enum__Torappu_ItemType::ACTIVITY_COIN,
    enum__Torappu_ItemType::DIAMOND,
    enum__Torappu_ItemType::DIAMOND_SHD,
    enum__Torappu_ItemType::HGG_SHD,
    enum__Torappu_ItemType::LGG_SHD,
    enum__Torappu_ItemType::FURN,
    enum__Torappu_ItemType::AP_GAMEPLAY,
    enum__Torappu_ItemType::AP_BASE,
    enum__Torappu_ItemType::SOCIAL_PT,
    enum__Torappu_ItemType::CHAR_SKIN,
    enum__Torappu_ItemType::TKT_GACHA_10,
    enum__Torappu_ItemType::TKT_GACHA_PRSV,
    enum__Torappu_ItemType::AP_ITEM,
    enum__Torappu_ItemType::AP_SUPPLY,
    enum__Torappu_ItemType::RENAMING_CARD,
    enum__Torappu_ItemType::RENAMING_CARD_2,
    enum__Torappu_ItemType::ET_STAGE,
    enum__Torappu_ItemType::ACTIVITY_ITEM,
    enum__Torappu_ItemType::VOUCHER_PICK,
    enum__Torappu_ItemType::VOUCHER_CGACHA,
    enum__Torappu_ItemType::VOUCHER_MGACHA,
    enum__Torappu_ItemType::CRS_SHOP_COIN,
    enum__Torappu_ItemType::CRS_RUNE_COIN,
    enum__Torappu_ItemType::LMTGS_COIN,
    enum__Torappu_ItemType::EPGS_COIN,
    enum__Torappu_ItemType::LIMITED_TKT_GACHA_10,
    enum__Torappu_ItemType::LIMITED_FREE_GACHA,
    enum__Torappu_ItemType::REP_COIN,
    enum__Torappu_ItemType::ROGUELIKE,
    enum__Torappu_ItemType::LINKAGE_TKT_GACHA_10,
    enum__Torappu_ItemType::VOUCHER_ELITE_II_4,
    enum__Torappu_ItemType::VOUCHER_ELITE_II_5,
    enum__Torappu_ItemType::VOUCHER_ELITE_II_6,
    enum__Torappu_ItemType::VOUCHER_SKIN,
    enum__Torappu_ItemType::RETRO_COIN,
    enum__Torappu_ItemType::PLAYER_AVATAR,
    enum__Torappu_ItemType::UNI_COLLECTION,
    enum__Torappu_ItemType::VOUCHER_FULL_POTENTIAL,
    enum__Torappu_ItemType::RL_COIN,
    enum__Torappu_ItemType::RETURN_CREDIT,
    enum__Torappu_ItemType::MEDAL,
    enum__Torappu_ItemType::CHARM,
    enum__Torappu_ItemType::HOME_BACKGROUND,
    enum__Torappu_ItemType::EXTERMINATION_AGENT,
    enum__Torappu_ItemType::OPTIONAL_VOUCHER_PICK,
    enum__Torappu_ItemType::ACT_CART_COMPONENT,
    enum__Torappu_ItemType::VOUCHER_LEVELMAX_6,
    enum__Torappu_ItemType::VOUCHER_LEVELMAX_5,
    enum__Torappu_ItemType::VOUCHER_LEVELMAX_4,
    enum__Torappu_ItemType::VOUCHER_SKILL_SPECIALLEVELMAX_6,
    enum__Torappu_ItemType::VOUCHER_SKILL_SPECIALLEVELMAX_5,
    enum__Torappu_ItemType::VOUCHER_SKILL_SPECIALLEVELMAX_4,
    enum__Torappu_ItemType::ACTIVITY_POTENTIAL,
    enum__Torappu_ItemType::ITEM_PACK,
    enum__Torappu_ItemType::SANDBOX,
    enum__Torappu_ItemType::FAVOR_ADD_ITEM,
    enum__Torappu_ItemType::CLASSIC_SHD,
    enum__Torappu_ItemType::CLASSIC_TKT_GACHA,
    enum__Torappu_ItemType::CLASSIC_TKT_GACHA_10,
    enum__Torappu_ItemType::LIMITED_BUFF,
    enum__Torappu_ItemType::CLASSIC_FES_PICK_TIER_5,
    enum__Torappu_ItemType::CLASSIC_FES_PICK_TIER_6,
    enum__Torappu_ItemType::RETURN_PROGRESS,
    enum__Torappu_ItemType::NEW_PROGRESS,
    enum__Torappu_ItemType::MCARD_VOUCHER,
    enum__Torappu_ItemType::MATERIAL_ISSUE_VOUCHER,
    enum__Torappu_ItemType::CRS_SHOP_COIN_V2,
    enum__Torappu_ItemType::HOME_THEME,
    enum__Torappu_ItemType::SANDBOX_PERM,
    enum__Torappu_ItemType::SANDBOX_TOKEN,
    enum__Torappu_ItemType::TEMPLATE_TRAP,
    enum__Torappu_ItemType::NAME_CARD_SKIN,
    enum__Torappu_ItemType::EMOTICON_SET,
    enum__Torappu_ItemType::EXCLUSIVE_TKT_GACHA,
    enum__Torappu_ItemType::EXCLUSIVE_TKT_GACHA_10,
    enum__Torappu_ItemType::SO_CHAR_EXP,
    enum__Torappu_ItemType::GIFTPACKAGE_TKT,
    enum__Torappu_ItemType::VOUCHER_SKIN_V2,
    enum__Torappu_ItemType::RANDOM_VOUCHER_SKIN,
    enum__Torappu_ItemType::ACT1VHALFIDLE_ITEM,
    enum__Torappu_ItemType::PLOT_ITEM,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct enum__Torappu_ItemType(pub i32);
#[allow(non_upper_case_globals)]
impl enum__Torappu_ItemType {
    pub const NONE: Self = Self(0);
    pub const CHAR: Self = Self(1);
    pub const CARD_EXP: Self = Self(2);
    pub const MATERIAL: Self = Self(3);
    pub const GOLD: Self = Self(4);
    pub const EXP_PLAYER: Self = Self(5);
    pub const TKT_TRY: Self = Self(6);
    pub const TKT_RECRUIT: Self = Self(7);
    pub const TKT_INST_FIN: Self = Self(8);
    pub const TKT_GACHA: Self = Self(9);
    pub const ACTIVITY_COIN: Self = Self(10);
    pub const DIAMOND: Self = Self(11);
    pub const DIAMOND_SHD: Self = Self(12);
    pub const HGG_SHD: Self = Self(13);
    pub const LGG_SHD: Self = Self(14);
    pub const FURN: Self = Self(15);
    pub const AP_GAMEPLAY: Self = Self(16);
    pub const AP_BASE: Self = Self(17);
    pub const SOCIAL_PT: Self = Self(18);
    pub const CHAR_SKIN: Self = Self(19);
    pub const TKT_GACHA_10: Self = Self(20);
    pub const TKT_GACHA_PRSV: Self = Self(21);
    pub const AP_ITEM: Self = Self(22);
    pub const AP_SUPPLY: Self = Self(23);
    pub const RENAMING_CARD: Self = Self(24);
    pub const RENAMING_CARD_2: Self = Self(25);
    pub const ET_STAGE: Self = Self(26);
    pub const ACTIVITY_ITEM: Self = Self(27);
    pub const VOUCHER_PICK: Self = Self(28);
    pub const VOUCHER_CGACHA: Self = Self(29);
    pub const VOUCHER_MGACHA: Self = Self(30);
    pub const CRS_SHOP_COIN: Self = Self(31);
    pub const CRS_RUNE_COIN: Self = Self(32);
    pub const LMTGS_COIN: Self = Self(33);
    pub const EPGS_COIN: Self = Self(34);
    pub const LIMITED_TKT_GACHA_10: Self = Self(35);
    pub const LIMITED_FREE_GACHA: Self = Self(36);
    pub const REP_COIN: Self = Self(37);
    pub const ROGUELIKE: Self = Self(38);
    pub const LINKAGE_TKT_GACHA_10: Self = Self(39);
    pub const VOUCHER_ELITE_II_4: Self = Self(40);
    pub const VOUCHER_ELITE_II_5: Self = Self(41);
    pub const VOUCHER_ELITE_II_6: Self = Self(42);
    pub const VOUCHER_SKIN: Self = Self(43);
    pub const RETRO_COIN: Self = Self(44);
    pub const PLAYER_AVATAR: Self = Self(45);
    pub const UNI_COLLECTION: Self = Self(46);
    pub const VOUCHER_FULL_POTENTIAL: Self = Self(47);
    pub const RL_COIN: Self = Self(48);
    pub const RETURN_CREDIT: Self = Self(49);
    pub const MEDAL: Self = Self(50);
    pub const CHARM: Self = Self(51);
    pub const HOME_BACKGROUND: Self = Self(52);
    pub const EXTERMINATION_AGENT: Self = Self(53);
    pub const OPTIONAL_VOUCHER_PICK: Self = Self(54);
    pub const ACT_CART_COMPONENT: Self = Self(55);
    pub const VOUCHER_LEVELMAX_6: Self = Self(56);
    pub const VOUCHER_LEVELMAX_5: Self = Self(57);
    pub const VOUCHER_LEVELMAX_4: Self = Self(58);
    pub const VOUCHER_SKILL_SPECIALLEVELMAX_6: Self = Self(59);
    pub const VOUCHER_SKILL_SPECIALLEVELMAX_5: Self = Self(60);
    pub const VOUCHER_SKILL_SPECIALLEVELMAX_4: Self = Self(61);
    pub const ACTIVITY_POTENTIAL: Self = Self(62);
    pub const ITEM_PACK: Self = Self(63);
    pub const SANDBOX: Self = Self(64);
    pub const FAVOR_ADD_ITEM: Self = Self(65);
    pub const CLASSIC_SHD: Self = Self(66);
    pub const CLASSIC_TKT_GACHA: Self = Self(67);
    pub const CLASSIC_TKT_GACHA_10: Self = Self(68);
    pub const LIMITED_BUFF: Self = Self(69);
    pub const CLASSIC_FES_PICK_TIER_5: Self = Self(70);
    pub const CLASSIC_FES_PICK_TIER_6: Self = Self(71);
    pub const RETURN_PROGRESS: Self = Self(72);
    pub const NEW_PROGRESS: Self = Self(73);
    pub const MCARD_VOUCHER: Self = Self(74);
    pub const MATERIAL_ISSUE_VOUCHER: Self = Self(75);
    pub const CRS_SHOP_COIN_V2: Self = Self(76);
    pub const HOME_THEME: Self = Self(77);
    pub const SANDBOX_PERM: Self = Self(78);
    pub const SANDBOX_TOKEN: Self = Self(79);
    pub const TEMPLATE_TRAP: Self = Self(80);
    pub const NAME_CARD_SKIN: Self = Self(81);
    pub const EMOTICON_SET: Self = Self(82);
    pub const EXCLUSIVE_TKT_GACHA: Self = Self(83);
    pub const EXCLUSIVE_TKT_GACHA_10: Self = Self(84);
    pub const SO_CHAR_EXP: Self = Self(85);
    pub const GIFTPACKAGE_TKT: Self = Self(86);
    pub const VOUCHER_SKIN_V2: Self = Self(87);
    pub const RANDOM_VOUCHER_SKIN: Self = Self(88);
    pub const ACT1VHALFIDLE_ITEM: Self = Self(89);
    pub const PLOT_ITEM: Self = Self(90);

    pub const ENUM_MIN: i32 = 0;
    pub const ENUM_MAX: i32 = 90;
    pub const ENUM_VALUES: &'static [Self] = &[
        Self::NONE,
        Self::CHAR,
        Self::CARD_EXP,
        Self::MATERIAL,
        Self::GOLD,
        Self::EXP_PLAYER,
        Self::TKT_TRY,
        Self::TKT_RECRUIT,
        Self::TKT_INST_FIN,
        Self::TKT_GACHA,
        Self::ACTIVITY_COIN,
        Self::DIAMOND,
        Self::DIAMOND_SHD,
        Self::HGG_SHD,
        Self::LGG_SHD,
        Self::FURN,
        Self::AP_GAMEPLAY,
        Self::AP_BASE,
        Self::SOCIAL_PT,
        Self::CHAR_SKIN,
        Self::TKT_GACHA_10,
        Self::TKT_GACHA_PRSV,
        Self::AP_ITEM,
        Self::AP_SUPPLY,
        Self::RENAMING_CARD,
        Self::RENAMING_CARD_2,
        Self::ET_STAGE,
        Self::ACTIVITY_ITEM,
        Self::VOUCHER_PICK,
        Self::VOUCHER_CGACHA,
        Self::VOUCHER_MGACHA,
        Self::CRS_SHOP_COIN,
        Self::CRS_RUNE_COIN,
        Self::LMTGS_COIN,
        Self::EPGS_COIN,
        Self::LIMITED_TKT_GACHA_10,
        Self::LIMITED_FREE_GACHA,
        Self::REP_COIN,
        Self::ROGUELIKE,
        Self::LINKAGE_TKT_GACHA_10,
        Self::VOUCHER_ELITE_II_4,
        Self::VOUCHER_ELITE_II_5,
        Self::VOUCHER_ELITE_II_6,
        Self::VOUCHER_SKIN,
        Self::RETRO_COIN,
        Self::PLAYER_AVATAR,
        Self::UNI_COLLECTION,
        Self::VOUCHER_FULL_POTENTIAL,
        Self::RL_COIN,
        Self::RETURN_CREDIT,
        Self::MEDAL,
        Self::CHARM,
        Self::HOME_BACKGROUND,
        Self::EXTERMINATION_AGENT,
        Self::OPTIONAL_VOUCHER_PICK,
        Self::ACT_CART_COMPONENT,
        Self::VOUCHER_LEVELMAX_6,
        Self::VOUCHER_LEVELMAX_5,
        Self::VOUCHER_LEVELMAX_4,
        Self::VOUCHER_SKILL_SPECIALLEVELMAX_6,
        Self::VOUCHER_SKILL_SPECIALLEVELMAX_5,
        Self::VOUCHER_SKILL_SPECIALLEVELMAX_4,
        Self::ACTIVITY_POTENTIAL,
        Self::ITEM_PACK,
        Self::SANDBOX,
        Self::FAVOR_ADD_ITEM,
        Self::CLASSIC_SHD,
        Self::CLASSIC_TKT_GACHA,
        Self::CLASSIC_TKT_GACHA_10,
        Self::LIMITED_BUFF,
        Self::CLASSIC_FES_PICK_TIER_5,
        Self::CLASSIC_FES_PICK_TIER_6,
        Self::RETURN_PROGRESS,
        Self::NEW_PROGRESS,
        Self::MCARD_VOUCHER,
        Self::MATERIAL_ISSUE_VOUCHER,
        Self::CRS_SHOP_COIN_V2,
        Self::HOME_THEME,
        Self::SANDBOX_PERM,
        Self::SANDBOX_TOKEN,
        Self::TEMPLATE_TRAP,
        Self::NAME_CARD_SKIN,
        Self::EMOTICON_SET,
        Self::EXCLUSIVE_TKT_GACHA,
        Self::EXCLUSIVE_TKT_GACHA_10,
        Self::SO_CHAR_EXP,
        Self::GIFTPACKAGE_TKT,
        Self::VOUCHER_SKIN_V2,
        Self::RANDOM_VOUCHER_SKIN,
        Self::ACT1VHALFIDLE_ITEM,
        Self::PLOT_ITEM,
    ];
    /// Returns the variant's name or "" if unknown.
    pub fn variant_name(self) -> Option<&'static str> {
        match self {
            Self::NONE => Some("NONE"),
            Self::CHAR => Some("CHAR"),
            Self::CARD_EXP => Some("CARD_EXP"),
            Self::MATERIAL => Some("MATERIAL"),
            Self::GOLD => Some("GOLD"),
            Self::EXP_PLAYER => Some("EXP_PLAYER"),
            Self::TKT_TRY => Some("TKT_TRY"),
            Self::TKT_RECRUIT => Some("TKT_RECRUIT"),
            Self::TKT_INST_FIN => Some("TKT_INST_FIN"),
            Self::TKT_GACHA => Some("TKT_GACHA"),
            Self::ACTIVITY_COIN => Some("ACTIVITY_COIN"),
            Self::DIAMOND => Some("DIAMOND"),
            Self::DIAMOND_SHD => Some("DIAMOND_SHD"),
            Self::HGG_SHD => Some("HGG_SHD"),
            Self::LGG_SHD => Some("LGG_SHD"),
            Self::FURN => Some("FURN"),
            Self::AP_GAMEPLAY => Some("AP_GAMEPLAY"),
            Self::AP_BASE => Some("AP_BASE"),
            Self::SOCIAL_PT => Some("SOCIAL_PT"),
            Self::CHAR_SKIN => Some("CHAR_SKIN"),
            Self::TKT_GACHA_10 => Some("TKT_GACHA_10"),
            Self::TKT_GACHA_PRSV => Some("TKT_GACHA_PRSV"),
            Self::AP_ITEM => Some("AP_ITEM"),
            Self::AP_SUPPLY => Some("AP_SUPPLY"),
            Self::RENAMING_CARD => Some("RENAMING_CARD"),
            Self::RENAMING_CARD_2 => Some("RENAMING_CARD_2"),
            Self::ET_STAGE => Some("ET_STAGE"),
            Self::ACTIVITY_ITEM => Some("ACTIVITY_ITEM"),
            Self::VOUCHER_PICK => Some("VOUCHER_PICK"),
            Self::VOUCHER_CGACHA => Some("VOUCHER_CGACHA"),
            Self::VOUCHER_MGACHA => Some("VOUCHER_MGACHA"),
            Self::CRS_SHOP_COIN => Some("CRS_SHOP_COIN"),
            Self::CRS_RUNE_COIN => Some("CRS_RUNE_COIN"),
            Self::LMTGS_COIN => Some("LMTGS_COIN"),
            Self::EPGS_COIN => Some("EPGS_COIN"),
            Self::LIMITED_TKT_GACHA_10 => Some("LIMITED_TKT_GACHA_10"),
            Self::LIMITED_FREE_GACHA => Some("LIMITED_FREE_GACHA"),
            Self::REP_COIN => Some("REP_COIN"),
            Self::ROGUELIKE => Some("ROGUELIKE"),
            Self::LINKAGE_TKT_GACHA_10 => Some("LINKAGE_TKT_GACHA_10"),
            Self::VOUCHER_ELITE_II_4 => Some("VOUCHER_ELITE_II_4"),
            Self::VOUCHER_ELITE_II_5 => Some("VOUCHER_ELITE_II_5"),
            Self::VOUCHER_ELITE_II_6 => Some("VOUCHER_ELITE_II_6"),
            Self::VOUCHER_SKIN => Some("VOUCHER_SKIN"),
            Self::RETRO_COIN => Some("RETRO_COIN"),
            Self::PLAYER_AVATAR => Some("PLAYER_AVATAR"),
            Self::UNI_COLLECTION => Some("UNI_COLLECTION"),
            Self::VOUCHER_FULL_POTENTIAL => Some("VOUCHER_FULL_POTENTIAL"),
            Self::RL_COIN => Some("RL_COIN"),
            Self::RETURN_CREDIT => Some("RETURN_CREDIT"),
            Self::MEDAL => Some("MEDAL"),
            Self::CHARM => Some("CHARM"),
            Self::HOME_BACKGROUND => Some("HOME_BACKGROUND"),
            Self::EXTERMINATION_AGENT => Some("EXTERMINATION_AGENT"),
            Self::OPTIONAL_VOUCHER_PICK => Some("OPTIONAL_VOUCHER_PICK"),
            Self::ACT_CART_COMPONENT => Some("ACT_CART_COMPONENT"),
            Self::VOUCHER_LEVELMAX_6 => Some("VOUCHER_LEVELMAX_6"),
            Self::VOUCHER_LEVELMAX_5 => Some("VOUCHER_LEVELMAX_5"),
            Self::VOUCHER_LEVELMAX_4 => Some("VOUCHER_LEVELMAX_4"),
            Self::VOUCHER_SKILL_SPECIALLEVELMAX_6 => Some("VOUCHER_SKILL_SPECIALLEVELMAX_6"),
            Self::VOUCHER_SKILL_SPECIALLEVELMAX_5 => Some("VOUCHER_SKILL_SPECIALLEVELMAX_5"),
            Self::VOUCHER_SKILL_SPECIALLEVELMAX_4 => Some("VOUCHER_SKILL_SPECIALLEVELMAX_4"),
            Self::ACTIVITY_POTENTIAL => Some("ACTIVITY_POTENTIAL"),
            Self::ITEM_PACK => Some("ITEM_PACK"),
            Self::SANDBOX => Some("SANDBOX"),
            Self::FAVOR_ADD_ITEM => Some("FAVOR_ADD_ITEM"),
            Self::CLASSIC_SHD => Some("CLASSIC_SHD"),
            Self::CLASSIC_TKT_GACHA => Some("CLASSIC_TKT_GACHA"),
            Self::CLASSIC_TKT_GACHA_10 => Some("CLASSIC_TKT_GACHA_10"),
            Self::LIMITED_BUFF => Some("LIMITED_BUFF"),
            Self::CLASSIC_FES_PICK_TIER_5 => Some("CLASSIC_FES_PICK_TIER_5"),
            Self::CLASSIC_FES_PICK_TIER_6 => Some("CLASSIC_FES_PICK_TIER_6"),
            Self::RETURN_PROGRESS => Some("RETURN_PROGRESS"),
            Self::NEW_PROGRESS => Some("NEW_PROGRESS"),
            Self::MCARD_VOUCHER => Some("MCARD_VOUCHER"),
            Self::MATERIAL_ISSUE_VOUCHER => Some("MATERIAL_ISSUE_VOUCHER"),
            Self::CRS_SHOP_COIN_V2 => Some("CRS_SHOP_COIN_V2"),
            Self::HOME_THEME => Some("HOME_THEME"),
            Self::SANDBOX_PERM => Some("SANDBOX_PERM"),
            Self::SANDBOX_TOKEN => Some("SANDBOX_TOKEN"),
            Self::TEMPLATE_TRAP => Some("TEMPLATE_TRAP"),
            Self::NAME_CARD_SKIN => Some("NAME_CARD_SKIN"),
            Self::EMOTICON_SET => Some("EMOTICON_SET"),
            Self::EXCLUSIVE_TKT_GACHA => Some("EXCLUSIVE_TKT_GACHA"),
            Self::EXCLUSIVE_TKT_GACHA_10 => Some("EXCLUSIVE_TKT_GACHA_10"),
            Self::SO_CHAR_EXP => Some("SO_CHAR_EXP"),
            Self::GIFTPACKAGE_TKT => Some("GIFTPACKAGE_TKT"),
            Self::VOUCHER_SKIN_V2 => Some("VOUCHER_SKIN_V2"),
            Self::RANDOM_VOUCHER_SKIN => Some("RANDOM_VOUCHER_SKIN"),
            Self::ACT1VHALFIDLE_ITEM => Some("ACT1VHALFIDLE_ITEM"),
            Self::PLOT_ITEM => Some("PLOT_ITEM"),
            _ => None,
        }
    }
}
impl core::fmt::Debug for enum__Torappu_ItemType {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        if let Some(name) = self.variant_name() {
            f.write_str(name)
        } else {
            f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
        }
    }
}
impl<'a> flatbuffers::Follow<'a> for enum__Torappu_ItemType {
    type Inner = Self;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        let b = flatbuffers::read_scalar_at::<i32>(buf, loc);
        Self(b)
    }
}

impl flatbuffers::Push for enum__Torappu_ItemType {
    type Output = enum__Torappu_ItemType;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<i32>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for enum__Torappu_ItemType {
    type Scalar = i32;
    #[inline]
    fn to_little_endian(self) -> i32 {
        self.0.to_le()
    }
    #[inline]
    #[allow(clippy::wrong_self_convention)]
    fn from_little_endian(v: i32) -> Self {
        let b = i32::from_le(v);
        Self(b)
    }
}

impl<'a> flatbuffers::Verifiable for enum__Torappu_ItemType {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        use self::flatbuffers::Verifiable;
        i32::run_verifier(v, pos)
    }
}

impl flatbuffers::SimpleToVerifyInSlice for enum__Torappu_ItemType {}
pub enum clz_Torappu_StoryData_TriggerOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct clz_Torappu_StoryData_Trigger<'a> {
    pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for clz_Torappu_StoryData_Trigger<'a> {
    type Inner = clz_Torappu_StoryData_Trigger<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table::new(buf, loc),
        }
    }
}

impl<'a> clz_Torappu_StoryData_Trigger<'a> {
    pub const VT_TYPE_: flatbuffers::VOffsetT = 4;
    pub const VT_KEY: flatbuffers::VOffsetT = 6;
    pub const VT_USEREGEX: flatbuffers::VOffsetT = 8;

    #[inline]
    pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        clz_Torappu_StoryData_Trigger { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args clz_Torappu_StoryData_TriggerArgs<'args>,
    ) -> flatbuffers::WIPOffset<clz_Torappu_StoryData_Trigger<'bldr>> {
        let mut builder = clz_Torappu_StoryData_TriggerBuilder::new(_fbb);
        if let Some(x) = args.key {
            builder.add_key(x);
        }
        builder.add_type_(args.type_);
        builder.add_useRegex(args.useRegex);
        builder.finish()
    }

    #[inline]
    pub fn type_(&self) -> enum__Torappu_StoryData_Trigger_TriggerType {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<enum__Torappu_StoryData_Trigger_TriggerType>(
                    clz_Torappu_StoryData_Trigger::VT_TYPE_,
                    Some(enum__Torappu_StoryData_Trigger_TriggerType::GAME_START),
                )
                .unwrap()
        }
    }
    #[inline]
    pub fn key(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(
                clz_Torappu_StoryData_Trigger::VT_KEY,
                None,
            )
        }
    }
    #[inline]
    pub fn useRegex(&self) -> bool {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<bool>(clz_Torappu_StoryData_Trigger::VT_USEREGEX, Some(false))
                .unwrap()
        }
    }
}

impl flatbuffers::Verifiable for clz_Torappu_StoryData_Trigger<'_> {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        use self::flatbuffers::Verifiable;
        v.visit_table(pos)?
            .visit_field::<enum__Torappu_StoryData_Trigger_TriggerType>(
                "type_",
                Self::VT_TYPE_,
                false,
            )?
            .visit_field::<flatbuffers::ForwardsUOffset<&str>>("key", Self::VT_KEY, false)?
            .visit_field::<bool>("useRegex", Self::VT_USEREGEX, false)?
            .finish();
        Ok(())
    }
}
pub struct clz_Torappu_StoryData_TriggerArgs<'a> {
    pub type_: enum__Torappu_StoryData_Trigger_TriggerType,
    pub key: Option<flatbuffers::WIPOffset<&'a str>>,
    pub useRegex: bool,
}
impl<'a> Default for clz_Torappu_StoryData_TriggerArgs<'a> {
    #[inline]
    fn default() -> Self {
        clz_Torappu_StoryData_TriggerArgs {
            type_: enum__Torappu_StoryData_Trigger_TriggerType::GAME_START,
            key: None,
            useRegex: false,
        }
    }
}

pub struct clz_Torappu_StoryData_TriggerBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
    fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> clz_Torappu_StoryData_TriggerBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_type_(&mut self, type_: enum__Torappu_StoryData_Trigger_TriggerType) {
        self.fbb_
            .push_slot::<enum__Torappu_StoryData_Trigger_TriggerType>(
                clz_Torappu_StoryData_Trigger::VT_TYPE_,
                type_,
                enum__Torappu_StoryData_Trigger_TriggerType::GAME_START,
            );
    }
    #[inline]
    pub fn add_key(&mut self, key: flatbuffers::WIPOffset<&'b str>) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            clz_Torappu_StoryData_Trigger::VT_KEY,
            key,
        );
    }
    #[inline]
    pub fn add_useRegex(&mut self, useRegex: bool) {
        self.fbb_
            .push_slot::<bool>(clz_Torappu_StoryData_Trigger::VT_USEREGEX, useRegex, false);
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> clz_Torappu_StoryData_TriggerBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        clz_Torappu_StoryData_TriggerBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> flatbuffers::WIPOffset<clz_Torappu_StoryData_Trigger<'a>> {
        let o = self.fbb_.end_table(self.start_);
        flatbuffers::WIPOffset::new(o.value())
    }
}

impl core::fmt::Debug for clz_Torappu_StoryData_Trigger<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut ds = f.debug_struct("clz_Torappu_StoryData_Trigger");
        ds.field("type_", &self.type_());
        ds.field("key", &self.key());
        ds.field("useRegex", &self.useRegex());
        ds.finish()
    }
}
pub enum clz_Torappu_StoryData_Condition_StageConditionOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct clz_Torappu_StoryData_Condition_StageCondition<'a> {
    pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for clz_Torappu_StoryData_Condition_StageCondition<'a> {
    type Inner = clz_Torappu_StoryData_Condition_StageCondition<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table::new(buf, loc),
        }
    }
}

impl<'a> clz_Torappu_StoryData_Condition_StageCondition<'a> {
    pub const VT_STAGEID: flatbuffers::VOffsetT = 4;
    pub const VT_MINSTATE: flatbuffers::VOffsetT = 6;
    pub const VT_MAXSTATE: flatbuffers::VOffsetT = 8;

    #[inline]
    pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        clz_Torappu_StoryData_Condition_StageCondition { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args clz_Torappu_StoryData_Condition_StageConditionArgs<'args>,
    ) -> flatbuffers::WIPOffset<clz_Torappu_StoryData_Condition_StageCondition<'bldr>> {
        let mut builder = clz_Torappu_StoryData_Condition_StageConditionBuilder::new(_fbb);
        builder.add_maxState(args.maxState);
        builder.add_minState(args.minState);
        if let Some(x) = args.stageId {
            builder.add_stageId(x);
        }
        builder.finish()
    }

    #[inline]
    pub fn stageId(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(
                clz_Torappu_StoryData_Condition_StageCondition::VT_STAGEID,
                None,
            )
        }
    }
    #[inline]
    pub fn minState(&self) -> enum__Torappu_PlayerStageState {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<enum__Torappu_PlayerStageState>(
                    clz_Torappu_StoryData_Condition_StageCondition::VT_MINSTATE,
                    Some(enum__Torappu_PlayerStageState::UNLOCKED),
                )
                .unwrap()
        }
    }
    #[inline]
    pub fn maxState(&self) -> enum__Torappu_PlayerStageState {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<enum__Torappu_PlayerStageState>(
                    clz_Torappu_StoryData_Condition_StageCondition::VT_MAXSTATE,
                    Some(enum__Torappu_PlayerStageState::UNLOCKED),
                )
                .unwrap()
        }
    }
}

impl flatbuffers::Verifiable for clz_Torappu_StoryData_Condition_StageCondition<'_> {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        use self::flatbuffers::Verifiable;
        v.visit_table(pos)?
            .visit_field::<flatbuffers::ForwardsUOffset<&str>>("stageId", Self::VT_STAGEID, false)?
            .visit_field::<enum__Torappu_PlayerStageState>("minState", Self::VT_MINSTATE, false)?
            .visit_field::<enum__Torappu_PlayerStageState>("maxState", Self::VT_MAXSTATE, false)?
            .finish();
        Ok(())
    }
}
pub struct clz_Torappu_StoryData_Condition_StageConditionArgs<'a> {
    pub stageId: Option<flatbuffers::WIPOffset<&'a str>>,
    pub minState: enum__Torappu_PlayerStageState,
    pub maxState: enum__Torappu_PlayerStageState,
}
impl<'a> Default for clz_Torappu_StoryData_Condition_StageConditionArgs<'a> {
    #[inline]
    fn default() -> Self {
        clz_Torappu_StoryData_Condition_StageConditionArgs {
            stageId: None,
            minState: enum__Torappu_PlayerStageState::UNLOCKED,
            maxState: enum__Torappu_PlayerStageState::UNLOCKED,
        }
    }
}

pub struct clz_Torappu_StoryData_Condition_StageConditionBuilder<
    'a: 'b,
    'b,
    A: flatbuffers::Allocator + 'a,
> {
    fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a>
    clz_Torappu_StoryData_Condition_StageConditionBuilder<'a, 'b, A>
{
    #[inline]
    pub fn add_stageId(&mut self, stageId: flatbuffers::WIPOffset<&'b str>) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            clz_Torappu_StoryData_Condition_StageCondition::VT_STAGEID,
            stageId,
        );
    }
    #[inline]
    pub fn add_minState(&mut self, minState: enum__Torappu_PlayerStageState) {
        self.fbb_.push_slot::<enum__Torappu_PlayerStageState>(
            clz_Torappu_StoryData_Condition_StageCondition::VT_MINSTATE,
            minState,
            enum__Torappu_PlayerStageState::UNLOCKED,
        );
    }
    #[inline]
    pub fn add_maxState(&mut self, maxState: enum__Torappu_PlayerStageState) {
        self.fbb_.push_slot::<enum__Torappu_PlayerStageState>(
            clz_Torappu_StoryData_Condition_StageCondition::VT_MAXSTATE,
            maxState,
            enum__Torappu_PlayerStageState::UNLOCKED,
        );
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> clz_Torappu_StoryData_Condition_StageConditionBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        clz_Torappu_StoryData_Condition_StageConditionBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(
        self,
    ) -> flatbuffers::WIPOffset<clz_Torappu_StoryData_Condition_StageCondition<'a>> {
        let o = self.fbb_.end_table(self.start_);
        flatbuffers::WIPOffset::new(o.value())
    }
}

impl core::fmt::Debug for clz_Torappu_StoryData_Condition_StageCondition<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut ds = f.debug_struct("clz_Torappu_StoryData_Condition_StageCondition");
        ds.field("stageId", &self.stageId());
        ds.field("minState", &self.minState());
        ds.field("maxState", &self.maxState());
        ds.finish()
    }
}
pub enum clz_Torappu_StoryData_ConditionOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct clz_Torappu_StoryData_Condition<'a> {
    pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for clz_Torappu_StoryData_Condition<'a> {
    type Inner = clz_Torappu_StoryData_Condition<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table::new(buf, loc),
        }
    }
}

impl<'a> clz_Torappu_StoryData_Condition<'a> {
    pub const VT_MINPROGRESS: flatbuffers::VOffsetT = 4;
    pub const VT_MAXPROGRESS: flatbuffers::VOffsetT = 6;
    pub const VT_MINPLAYERLEVEL: flatbuffers::VOffsetT = 8;
    pub const VT_REQUIREDFLAGS: flatbuffers::VOffsetT = 10;
    pub const VT_EXCLUDEDFLAGS: flatbuffers::VOffsetT = 12;
    pub const VT_REQUIREDSTAGES: flatbuffers::VOffsetT = 14;

    #[inline]
    pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        clz_Torappu_StoryData_Condition { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args clz_Torappu_StoryData_ConditionArgs<'args>,
    ) -> flatbuffers::WIPOffset<clz_Torappu_StoryData_Condition<'bldr>> {
        let mut builder = clz_Torappu_StoryData_ConditionBuilder::new(_fbb);
        if let Some(x) = args.requiredStages {
            builder.add_requiredStages(x);
        }
        if let Some(x) = args.excludedFlags {
            builder.add_excludedFlags(x);
        }
        if let Some(x) = args.requiredFlags {
            builder.add_requiredFlags(x);
        }
        builder.add_minPlayerLevel(args.minPlayerLevel);
        builder.add_maxProgress(args.maxProgress);
        builder.add_minProgress(args.minProgress);
        builder.finish()
    }

    #[inline]
    pub fn minProgress(&self) -> i32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<i32>(clz_Torappu_StoryData_Condition::VT_MINPROGRESS, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn maxProgress(&self) -> i32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<i32>(clz_Torappu_StoryData_Condition::VT_MAXPROGRESS, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn minPlayerLevel(&self) -> i32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<i32>(clz_Torappu_StoryData_Condition::VT_MINPLAYERLEVEL, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn requiredFlags(
        &self,
    ) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>,
            >>(clz_Torappu_StoryData_Condition::VT_REQUIREDFLAGS, None)
        }
    }
    #[inline]
    pub fn excludedFlags(
        &self,
    ) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>,
            >>(clz_Torappu_StoryData_Condition::VT_EXCLUDEDFLAGS, None)
        }
    }
    #[inline]
    pub fn requiredStages(
        &self,
    ) -> Option<
        flatbuffers::Vector<
            'a,
            flatbuffers::ForwardsUOffset<clz_Torappu_StoryData_Condition_StageCondition<'a>>,
        >,
    > {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<
                    'a,
                    flatbuffers::ForwardsUOffset<clz_Torappu_StoryData_Condition_StageCondition>,
                >,
            >>(clz_Torappu_StoryData_Condition::VT_REQUIREDSTAGES, None)
        }
    }
}

impl flatbuffers::Verifiable for clz_Torappu_StoryData_Condition<'_> {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        use self::flatbuffers::Verifiable;
        v.visit_table(pos)?
            .visit_field::<i32>("minProgress", Self::VT_MINPROGRESS, false)?
            .visit_field::<i32>("maxProgress", Self::VT_MAXPROGRESS, false)?
            .visit_field::<i32>("minPlayerLevel", Self::VT_MINPLAYERLEVEL, false)?
            .visit_field::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<&'_ str>>,
            >>("requiredFlags", Self::VT_REQUIREDFLAGS, false)?
            .visit_field::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<&'_ str>>,
            >>("excludedFlags", Self::VT_EXCLUDEDFLAGS, false)?
            .visit_field::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<
                    '_,
                    flatbuffers::ForwardsUOffset<clz_Torappu_StoryData_Condition_StageCondition>,
                >,
            >>("requiredStages", Self::VT_REQUIREDSTAGES, false)?
            .finish();
        Ok(())
    }
}
pub struct clz_Torappu_StoryData_ConditionArgs<'a> {
    pub minProgress: i32,
    pub maxProgress: i32,
    pub minPlayerLevel: i32,
    pub requiredFlags: Option<
        flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>>,
    >,
    pub excludedFlags: Option<
        flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>>,
    >,
    pub requiredStages: Option<
        flatbuffers::WIPOffset<
            flatbuffers::Vector<
                'a,
                flatbuffers::ForwardsUOffset<clz_Torappu_StoryData_Condition_StageCondition<'a>>,
            >,
        >,
    >,
}
impl<'a> Default for clz_Torappu_StoryData_ConditionArgs<'a> {
    #[inline]
    fn default() -> Self {
        clz_Torappu_StoryData_ConditionArgs {
            minProgress: 0,
            maxProgress: 0,
            minPlayerLevel: 0,
            requiredFlags: None,
            excludedFlags: None,
            requiredStages: None,
        }
    }
}

pub struct clz_Torappu_StoryData_ConditionBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
    fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> clz_Torappu_StoryData_ConditionBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_minProgress(&mut self, minProgress: i32) {
        self.fbb_.push_slot::<i32>(
            clz_Torappu_StoryData_Condition::VT_MINPROGRESS,
            minProgress,
            0,
        );
    }
    #[inline]
    pub fn add_maxProgress(&mut self, maxProgress: i32) {
        self.fbb_.push_slot::<i32>(
            clz_Torappu_StoryData_Condition::VT_MAXPROGRESS,
            maxProgress,
            0,
        );
    }
    #[inline]
    pub fn add_minPlayerLevel(&mut self, minPlayerLevel: i32) {
        self.fbb_.push_slot::<i32>(
            clz_Torappu_StoryData_Condition::VT_MINPLAYERLEVEL,
            minPlayerLevel,
            0,
        );
    }
    #[inline]
    pub fn add_requiredFlags(
        &mut self,
        requiredFlags: flatbuffers::WIPOffset<
            flatbuffers::Vector<'b, flatbuffers::ForwardsUOffset<&'b str>>,
        >,
    ) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            clz_Torappu_StoryData_Condition::VT_REQUIREDFLAGS,
            requiredFlags,
        );
    }
    #[inline]
    pub fn add_excludedFlags(
        &mut self,
        excludedFlags: flatbuffers::WIPOffset<
            flatbuffers::Vector<'b, flatbuffers::ForwardsUOffset<&'b str>>,
        >,
    ) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            clz_Torappu_StoryData_Condition::VT_EXCLUDEDFLAGS,
            excludedFlags,
        );
    }
    #[inline]
    pub fn add_requiredStages(
        &mut self,
        requiredStages: flatbuffers::WIPOffset<
            flatbuffers::Vector<
                'b,
                flatbuffers::ForwardsUOffset<clz_Torappu_StoryData_Condition_StageCondition<'b>>,
            >,
        >,
    ) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            clz_Torappu_StoryData_Condition::VT_REQUIREDSTAGES,
            requiredStages,
        );
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> clz_Torappu_StoryData_ConditionBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        clz_Torappu_StoryData_ConditionBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> flatbuffers::WIPOffset<clz_Torappu_StoryData_Condition<'a>> {
        let o = self.fbb_.end_table(self.start_);
        flatbuffers::WIPOffset::new(o.value())
    }
}

impl core::fmt::Debug for clz_Torappu_StoryData_Condition<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut ds = f.debug_struct("clz_Torappu_StoryData_Condition");
        ds.field("minProgress", &self.minProgress());
        ds.field("maxProgress", &self.maxProgress());
        ds.field("minPlayerLevel", &self.minPlayerLevel());
        ds.field("requiredFlags", &self.requiredFlags());
        ds.field("excludedFlags", &self.excludedFlags());
        ds.field("requiredStages", &self.requiredStages());
        ds.finish()
    }
}
pub enum clz_Torappu_ItemBundleOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct clz_Torappu_ItemBundle<'a> {
    pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for clz_Torappu_ItemBundle<'a> {
    type Inner = clz_Torappu_ItemBundle<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table::new(buf, loc),
        }
    }
}

impl<'a> clz_Torappu_ItemBundle<'a> {
    pub const VT_ID: flatbuffers::VOffsetT = 4;
    pub const VT_COUNT: flatbuffers::VOffsetT = 6;
    pub const VT_TYPE_: flatbuffers::VOffsetT = 8;

    #[inline]
    pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        clz_Torappu_ItemBundle { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args clz_Torappu_ItemBundleArgs<'args>,
    ) -> flatbuffers::WIPOffset<clz_Torappu_ItemBundle<'bldr>> {
        let mut builder = clz_Torappu_ItemBundleBuilder::new(_fbb);
        builder.add_type_(args.type_);
        builder.add_count(args.count);
        if let Some(x) = args.id {
            builder.add_id(x);
        }
        builder.finish()
    }

    #[inline]
    pub fn id(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<&str>>(clz_Torappu_ItemBundle::VT_ID, None)
        }
    }
    #[inline]
    pub fn count(&self) -> i32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<i32>(clz_Torappu_ItemBundle::VT_COUNT, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn type_(&self) -> enum__Torappu_ItemType {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<enum__Torappu_ItemType>(
                    clz_Torappu_ItemBundle::VT_TYPE_,
                    Some(enum__Torappu_ItemType::NONE),
                )
                .unwrap()
        }
    }
}

impl flatbuffers::Verifiable for clz_Torappu_ItemBundle<'_> {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        use self::flatbuffers::Verifiable;
        v.visit_table(pos)?
            .visit_field::<flatbuffers::ForwardsUOffset<&str>>("id", Self::VT_ID, false)?
            .visit_field::<i32>("count", Self::VT_COUNT, false)?
            .visit_field::<enum__Torappu_ItemType>("type_", Self::VT_TYPE_, false)?
            .finish();
        Ok(())
    }
}
pub struct clz_Torappu_ItemBundleArgs<'a> {
    pub id: Option<flatbuffers::WIPOffset<&'a str>>,
    pub count: i32,
    pub type_: enum__Torappu_ItemType,
}
impl<'a> Default for clz_Torappu_ItemBundleArgs<'a> {
    #[inline]
    fn default() -> Self {
        clz_Torappu_ItemBundleArgs {
            id: None,
            count: 0,
            type_: enum__Torappu_ItemType::NONE,
        }
    }
}

pub struct clz_Torappu_ItemBundleBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
    fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> clz_Torappu_ItemBundleBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_id(&mut self, id: flatbuffers::WIPOffset<&'b str>) {
        self.fbb_
            .push_slot_always::<flatbuffers::WIPOffset<_>>(clz_Torappu_ItemBundle::VT_ID, id);
    }
    #[inline]
    pub fn add_count(&mut self, count: i32) {
        self.fbb_
            .push_slot::<i32>(clz_Torappu_ItemBundle::VT_COUNT, count, 0);
    }
    #[inline]
    pub fn add_type_(&mut self, type_: enum__Torappu_ItemType) {
        self.fbb_.push_slot::<enum__Torappu_ItemType>(
            clz_Torappu_ItemBundle::VT_TYPE_,
            type_,
            enum__Torappu_ItemType::NONE,
        );
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> clz_Torappu_ItemBundleBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        clz_Torappu_ItemBundleBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> flatbuffers::WIPOffset<clz_Torappu_ItemBundle<'a>> {
        let o = self.fbb_.end_table(self.start_);
        flatbuffers::WIPOffset::new(o.value())
    }
}

impl core::fmt::Debug for clz_Torappu_ItemBundle<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut ds = f.debug_struct("clz_Torappu_ItemBundle");
        ds.field("id", &self.id());
        ds.field("count", &self.count());
        ds.field("type_", &self.type_());
        ds.finish()
    }
}
pub enum clz_Torappu_StoryDataOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct clz_Torappu_StoryData<'a> {
    pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for clz_Torappu_StoryData<'a> {
    type Inner = clz_Torappu_StoryData<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table::new(buf, loc),
        }
    }
}

impl<'a> clz_Torappu_StoryData<'a> {
    pub const VT_ID: flatbuffers::VOffsetT = 4;
    pub const VT_NEEDCOMMIT: flatbuffers::VOffsetT = 6;
    pub const VT_REPEATABLE: flatbuffers::VOffsetT = 8;
    pub const VT_DISABLED: flatbuffers::VOffsetT = 10;
    pub const VT_VIDEORESOURCE: flatbuffers::VOffsetT = 12;
    pub const VT_TRIGGER: flatbuffers::VOffsetT = 14;
    pub const VT_CONDITION: flatbuffers::VOffsetT = 16;
    pub const VT_SETPROGRESS: flatbuffers::VOffsetT = 18;
    pub const VT_SETFLAGS: flatbuffers::VOffsetT = 20;
    pub const VT_COMPLETEDREWARDS: flatbuffers::VOffsetT = 22;

    #[inline]
    pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        clz_Torappu_StoryData { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args clz_Torappu_StoryDataArgs<'args>,
    ) -> flatbuffers::WIPOffset<clz_Torappu_StoryData<'bldr>> {
        let mut builder = clz_Torappu_StoryDataBuilder::new(_fbb);
        if let Some(x) = args.completedRewards {
            builder.add_completedRewards(x);
        }
        if let Some(x) = args.setFlags {
            builder.add_setFlags(x);
        }
        builder.add_setProgress(args.setProgress);
        if let Some(x) = args.condition {
            builder.add_condition(x);
        }
        if let Some(x) = args.trigger {
            builder.add_trigger(x);
        }
        if let Some(x) = args.id {
            builder.add_id(x);
        }
        builder.add_videoResource(args.videoResource);
        builder.add_disabled(args.disabled);
        builder.add_repeatable(args.repeatable);
        builder.add_needCommit(args.needCommit);
        builder.finish()
    }

    #[inline]
    pub fn id(&self) -> Option<&'a str> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<&str>>(clz_Torappu_StoryData::VT_ID, None)
        }
    }
    #[inline]
    pub fn needCommit(&self) -> bool {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<bool>(clz_Torappu_StoryData::VT_NEEDCOMMIT, Some(false))
                .unwrap()
        }
    }
    #[inline]
    pub fn repeatable(&self) -> bool {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<bool>(clz_Torappu_StoryData::VT_REPEATABLE, Some(false))
                .unwrap()
        }
    }
    #[inline]
    pub fn disabled(&self) -> bool {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<bool>(clz_Torappu_StoryData::VT_DISABLED, Some(false))
                .unwrap()
        }
    }
    #[inline]
    pub fn videoResource(&self) -> bool {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<bool>(clz_Torappu_StoryData::VT_VIDEORESOURCE, Some(false))
                .unwrap()
        }
    }
    #[inline]
    pub fn trigger(&self) -> Option<clz_Torappu_StoryData_Trigger<'a>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<clz_Torappu_StoryData_Trigger>>(
                    clz_Torappu_StoryData::VT_TRIGGER,
                    None,
                )
        }
    }
    #[inline]
    pub fn condition(&self) -> Option<clz_Torappu_StoryData_Condition<'a>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<clz_Torappu_StoryData_Condition>>(
                    clz_Torappu_StoryData::VT_CONDITION,
                    None,
                )
        }
    }
    #[inline]
    pub fn setProgress(&self) -> i32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<i32>(clz_Torappu_StoryData::VT_SETPROGRESS, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn setFlags(
        &self,
    ) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>,
            >>(clz_Torappu_StoryData::VT_SETFLAGS, None)
        }
    }
    #[inline]
    pub fn completedRewards(
        &self,
    ) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<clz_Torappu_ItemBundle<'a>>>>
    {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<clz_Torappu_ItemBundle>>,
            >>(clz_Torappu_StoryData::VT_COMPLETEDREWARDS, None)
        }
    }
}

impl flatbuffers::Verifiable for clz_Torappu_StoryData<'_> {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        use self::flatbuffers::Verifiable;
        v.visit_table(pos)?
            .visit_field::<flatbuffers::ForwardsUOffset<&str>>("id", Self::VT_ID, false)?
            .visit_field::<bool>("needCommit", Self::VT_NEEDCOMMIT, false)?
            .visit_field::<bool>("repeatable", Self::VT_REPEATABLE, false)?
            .visit_field::<bool>("disabled", Self::VT_DISABLED, false)?
            .visit_field::<bool>("videoResource", Self::VT_VIDEORESOURCE, false)?
            .visit_field::<flatbuffers::ForwardsUOffset<clz_Torappu_StoryData_Trigger>>(
                "trigger",
                Self::VT_TRIGGER,
                false,
            )?
            .visit_field::<flatbuffers::ForwardsUOffset<clz_Torappu_StoryData_Condition>>(
                "condition",
                Self::VT_CONDITION,
                false,
            )?
            .visit_field::<i32>("setProgress", Self::VT_SETPROGRESS, false)?
            .visit_field::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<&'_ str>>,
            >>("setFlags", Self::VT_SETFLAGS, false)?
            .visit_field::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<clz_Torappu_ItemBundle>>,
            >>("completedRewards", Self::VT_COMPLETEDREWARDS, false)?
            .finish();
        Ok(())
    }
}
pub struct clz_Torappu_StoryDataArgs<'a> {
    pub id: Option<flatbuffers::WIPOffset<&'a str>>,
    pub needCommit: bool,
    pub repeatable: bool,
    pub disabled: bool,
    pub videoResource: bool,
    pub trigger: Option<flatbuffers::WIPOffset<clz_Torappu_StoryData_Trigger<'a>>>,
    pub condition: Option<flatbuffers::WIPOffset<clz_Torappu_StoryData_Condition<'a>>>,
    pub setProgress: i32,
    pub setFlags: Option<
        flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>>,
    >,
    pub completedRewards: Option<
        flatbuffers::WIPOffset<
            flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<clz_Torappu_ItemBundle<'a>>>,
        >,
    >,
}
impl<'a> Default for clz_Torappu_StoryDataArgs<'a> {
    #[inline]
    fn default() -> Self {
        clz_Torappu_StoryDataArgs {
            id: None,
            needCommit: false,
            repeatable: false,
            disabled: false,
            videoResource: false,
            trigger: None,
            condition: None,
            setProgress: 0,
            setFlags: None,
            completedRewards: None,
        }
    }
}

pub struct clz_Torappu_StoryDataBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
    fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> clz_Torappu_StoryDataBuilder<'a, 'b, A> {
    #[inline]
    pub fn add_id(&mut self, id: flatbuffers::WIPOffset<&'b str>) {
        self.fbb_
            .push_slot_always::<flatbuffers::WIPOffset<_>>(clz_Torappu_StoryData::VT_ID, id);
    }
    #[inline]
    pub fn add_needCommit(&mut self, needCommit: bool) {
        self.fbb_
            .push_slot::<bool>(clz_Torappu_StoryData::VT_NEEDCOMMIT, needCommit, false);
    }
    #[inline]
    pub fn add_repeatable(&mut self, repeatable: bool) {
        self.fbb_
            .push_slot::<bool>(clz_Torappu_StoryData::VT_REPEATABLE, repeatable, false);
    }
    #[inline]
    pub fn add_disabled(&mut self, disabled: bool) {
        self.fbb_
            .push_slot::<bool>(clz_Torappu_StoryData::VT_DISABLED, disabled, false);
    }
    #[inline]
    pub fn add_videoResource(&mut self, videoResource: bool) {
        self.fbb_.push_slot::<bool>(
            clz_Torappu_StoryData::VT_VIDEORESOURCE,
            videoResource,
            false,
        );
    }
    #[inline]
    pub fn add_trigger(
        &mut self,
        trigger: flatbuffers::WIPOffset<clz_Torappu_StoryData_Trigger<'b>>,
    ) {
        self.fbb_
            .push_slot_always::<flatbuffers::WIPOffset<clz_Torappu_StoryData_Trigger>>(
                clz_Torappu_StoryData::VT_TRIGGER,
                trigger,
            );
    }
    #[inline]
    pub fn add_condition(
        &mut self,
        condition: flatbuffers::WIPOffset<clz_Torappu_StoryData_Condition<'b>>,
    ) {
        self.fbb_
            .push_slot_always::<flatbuffers::WIPOffset<clz_Torappu_StoryData_Condition>>(
                clz_Torappu_StoryData::VT_CONDITION,
                condition,
            );
    }
    #[inline]
    pub fn add_setProgress(&mut self, setProgress: i32) {
        self.fbb_
            .push_slot::<i32>(clz_Torappu_StoryData::VT_SETPROGRESS, setProgress, 0);
    }
    #[inline]
    pub fn add_setFlags(
        &mut self,
        setFlags: flatbuffers::WIPOffset<
            flatbuffers::Vector<'b, flatbuffers::ForwardsUOffset<&'b str>>,
        >,
    ) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            clz_Torappu_StoryData::VT_SETFLAGS,
            setFlags,
        );
    }
    #[inline]
    pub fn add_completedRewards(
        &mut self,
        completedRewards: flatbuffers::WIPOffset<
            flatbuffers::Vector<'b, flatbuffers::ForwardsUOffset<clz_Torappu_ItemBundle<'b>>>,
        >,
    ) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            clz_Torappu_StoryData::VT_COMPLETEDREWARDS,
            completedRewards,
        );
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> clz_Torappu_StoryDataBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        clz_Torappu_StoryDataBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> flatbuffers::WIPOffset<clz_Torappu_StoryData<'a>> {
        let o = self.fbb_.end_table(self.start_);
        flatbuffers::WIPOffset::new(o.value())
    }
}

impl core::fmt::Debug for clz_Torappu_StoryData<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut ds = f.debug_struct("clz_Torappu_StoryData");
        ds.field("id", &self.id());
        ds.field("needCommit", &self.needCommit());
        ds.field("repeatable", &self.repeatable());
        ds.field("disabled", &self.disabled());
        ds.field("videoResource", &self.videoResource());
        ds.field("trigger", &self.trigger());
        ds.field("condition", &self.condition());
        ds.field("setProgress", &self.setProgress());
        ds.field("setFlags", &self.setFlags());
        ds.field("completedRewards", &self.completedRewards());
        ds.finish()
    }
}
pub enum dict__string__clz_Torappu_StoryDataOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct dict__string__clz_Torappu_StoryData<'a> {
    pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for dict__string__clz_Torappu_StoryData<'a> {
    type Inner = dict__string__clz_Torappu_StoryData<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table::new(buf, loc),
        }
    }
}

impl<'a> dict__string__clz_Torappu_StoryData<'a> {
    pub const VT_KEY: flatbuffers::VOffsetT = 4;
    pub const VT_VALUE: flatbuffers::VOffsetT = 6;

    #[inline]
    pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        dict__string__clz_Torappu_StoryData { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args dict__string__clz_Torappu_StoryDataArgs<'args>,
    ) -> flatbuffers::WIPOffset<dict__string__clz_Torappu_StoryData<'bldr>> {
        let mut builder = dict__string__clz_Torappu_StoryDataBuilder::new(_fbb);
        if let Some(x) = args.value {
            builder.add_value(x);
        }
        if let Some(x) = args.key {
            builder.add_key(x);
        }
        builder.finish()
    }

    #[inline]
    pub fn key(&self) -> &'a str {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<&str>>(
                    dict__string__clz_Torappu_StoryData::VT_KEY,
                    None,
                )
                .unwrap()
        }
    }
    #[inline]
    pub fn key_compare_less_than(&self, o: &dict__string__clz_Torappu_StoryData) -> bool {
        self.key() < o.key()
    }

    #[inline]
    pub fn key_compare_with_value(&self, val: &str) -> ::core::cmp::Ordering {
        let key = self.key();
        key.cmp(val)
    }
    #[inline]
    pub fn value(&self) -> Option<clz_Torappu_StoryData<'a>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<clz_Torappu_StoryData>>(
                    dict__string__clz_Torappu_StoryData::VT_VALUE,
                    None,
                )
        }
    }
}

impl flatbuffers::Verifiable for dict__string__clz_Torappu_StoryData<'_> {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        use self::flatbuffers::Verifiable;
        v.visit_table(pos)?
            .visit_field::<flatbuffers::ForwardsUOffset<&str>>("key", Self::VT_KEY, true)?
            .visit_field::<flatbuffers::ForwardsUOffset<clz_Torappu_StoryData>>(
                "value",
                Self::VT_VALUE,
                false,
            )?
            .finish();
        Ok(())
    }
}
pub struct dict__string__clz_Torappu_StoryDataArgs<'a> {
    pub key: Option<flatbuffers::WIPOffset<&'a str>>,
    pub value: Option<flatbuffers::WIPOffset<clz_Torappu_StoryData<'a>>>,
}
impl<'a> Default for dict__string__clz_Torappu_StoryDataArgs<'a> {
    #[inline]
    fn default() -> Self {
        dict__string__clz_Torappu_StoryDataArgs {
            key: None, // required field
            value: None,
        }
    }
}

pub struct dict__string__clz_Torappu_StoryDataBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
    fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a>
    dict__string__clz_Torappu_StoryDataBuilder<'a, 'b, A>
{
    #[inline]
    pub fn add_key(&mut self, key: flatbuffers::WIPOffset<&'b str>) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            dict__string__clz_Torappu_StoryData::VT_KEY,
            key,
        );
    }
    #[inline]
    pub fn add_value(&mut self, value: flatbuffers::WIPOffset<clz_Torappu_StoryData<'b>>) {
        self.fbb_
            .push_slot_always::<flatbuffers::WIPOffset<clz_Torappu_StoryData>>(
                dict__string__clz_Torappu_StoryData::VT_VALUE,
                value,
            );
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> dict__string__clz_Torappu_StoryDataBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        dict__string__clz_Torappu_StoryDataBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> flatbuffers::WIPOffset<dict__string__clz_Torappu_StoryData<'a>> {
        let o = self.fbb_.end_table(self.start_);
        self.fbb_
            .required(o, dict__string__clz_Torappu_StoryData::VT_KEY, "key");
        flatbuffers::WIPOffset::new(o.value())
    }
}

impl core::fmt::Debug for dict__string__clz_Torappu_StoryData<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut ds = f.debug_struct("dict__string__clz_Torappu_StoryData");
        ds.field("key", &self.key());
        ds.field("value", &self.value());
        ds.finish()
    }
}
pub enum clz_Torappu_SimpleKVTable_clz_Torappu_StoryDataOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct clz_Torappu_SimpleKVTable_clz_Torappu_StoryData<'a> {
    pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for clz_Torappu_SimpleKVTable_clz_Torappu_StoryData<'a> {
    type Inner = clz_Torappu_SimpleKVTable_clz_Torappu_StoryData<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table::new(buf, loc),
        }
    }
}

impl<'a> clz_Torappu_SimpleKVTable_clz_Torappu_StoryData<'a> {
    pub const VT_STORIES: flatbuffers::VOffsetT = 4;

    #[inline]
    pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        clz_Torappu_SimpleKVTable_clz_Torappu_StoryData { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
        args: &'args clz_Torappu_SimpleKVTable_clz_Torappu_StoryDataArgs<'args>,
    ) -> flatbuffers::WIPOffset<clz_Torappu_SimpleKVTable_clz_Torappu_StoryData<'bldr>> {
        let mut builder = clz_Torappu_SimpleKVTable_clz_Torappu_StoryDataBuilder::new(_fbb);
        if let Some(x) = args.stories {
            builder.add_stories(x);
        }
        builder.finish()
    }

    #[inline]
    pub fn stories(
        &self,
    ) -> Option<
        flatbuffers::Vector<
            'a,
            flatbuffers::ForwardsUOffset<dict__string__clz_Torappu_StoryData<'a>>,
        >,
    > {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<
                    'a,
                    flatbuffers::ForwardsUOffset<dict__string__clz_Torappu_StoryData>,
                >,
            >>(
                clz_Torappu_SimpleKVTable_clz_Torappu_StoryData::VT_STORIES,
                None,
            )
        }
    }
}

impl flatbuffers::Verifiable for clz_Torappu_SimpleKVTable_clz_Torappu_StoryData<'_> {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        use self::flatbuffers::Verifiable;
        v.visit_table(pos)?
            .visit_field::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<
                    '_,
                    flatbuffers::ForwardsUOffset<dict__string__clz_Torappu_StoryData>,
                >,
            >>("stories", Self::VT_STORIES, false)?
            .finish();
        Ok(())
    }
}
pub struct clz_Torappu_SimpleKVTable_clz_Torappu_StoryDataArgs<'a> {
    pub stories: Option<
        flatbuffers::WIPOffset<
            flatbuffers::Vector<
                'a,
                flatbuffers::ForwardsUOffset<dict__string__clz_Torappu_StoryData<'a>>,
            >,
        >,
    >,
}
impl<'a> Default for clz_Torappu_SimpleKVTable_clz_Torappu_StoryDataArgs<'a> {
    #[inline]
    fn default() -> Self {
        clz_Torappu_SimpleKVTable_clz_Torappu_StoryDataArgs { stories: None }
    }
}

pub struct clz_Torappu_SimpleKVTable_clz_Torappu_StoryDataBuilder<
    'a: 'b,
    'b,
    A: flatbuffers::Allocator + 'a,
> {
    fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a>
    clz_Torappu_SimpleKVTable_clz_Torappu_StoryDataBuilder<'a, 'b, A>
{
    #[inline]
    pub fn add_stories(
        &mut self,
        stories: flatbuffers::WIPOffset<
            flatbuffers::Vector<
                'b,
                flatbuffers::ForwardsUOffset<dict__string__clz_Torappu_StoryData<'b>>,
            >,
        >,
    ) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            clz_Torappu_SimpleKVTable_clz_Torappu_StoryData::VT_STORIES,
            stories,
        );
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    ) -> clz_Torappu_SimpleKVTable_clz_Torappu_StoryDataBuilder<'a, 'b, A> {
        let start = _fbb.start_table();
        clz_Torappu_SimpleKVTable_clz_Torappu_StoryDataBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(
        self,
    ) -> flatbuffers::WIPOffset<clz_Torappu_SimpleKVTable_clz_Torappu_StoryData<'a>> {
        let o = self.fbb_.end_table(self.start_);
        flatbuffers::WIPOffset::new(o.value())
    }
}

impl core::fmt::Debug for clz_Torappu_SimpleKVTable_clz_Torappu_StoryData<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut ds = f.debug_struct("clz_Torappu_SimpleKVTable_clz_Torappu_StoryData");
        ds.field("stories", &self.stories());
        ds.finish()
    }
}
#[inline]
/// Verifies that a buffer of bytes contains a `clz_Torappu_SimpleKVTable_clz_Torappu_StoryData`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_clz_torappu_simple_kvtable_clz_torappu_story_data_unchecked`.
pub fn root_as_clz_torappu_simple_kvtable_clz_torappu_story_data(
    buf: &[u8],
) -> Result<clz_Torappu_SimpleKVTable_clz_Torappu_StoryData, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::root::<clz_Torappu_SimpleKVTable_clz_Torappu_StoryData>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `clz_Torappu_SimpleKVTable_clz_Torappu_StoryData` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_clz_torappu_simple_kvtable_clz_torappu_story_data_unchecked`.
pub fn size_prefixed_root_as_clz_torappu_simple_kvtable_clz_torappu_story_data(
    buf: &[u8],
) -> Result<clz_Torappu_SimpleKVTable_clz_Torappu_StoryData, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::size_prefixed_root::<clz_Torappu_SimpleKVTable_clz_Torappu_StoryData>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `clz_Torappu_SimpleKVTable_clz_Torappu_StoryData` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_clz_torappu_simple_kvtable_clz_torappu_story_data_unchecked`.
pub fn root_as_clz_torappu_simple_kvtable_clz_torappu_story_data_with_opts<'b, 'o>(
    opts: &'o flatbuffers::VerifierOptions,
    buf: &'b [u8],
) -> Result<clz_Torappu_SimpleKVTable_clz_Torappu_StoryData<'b>, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::root_with_opts::<clz_Torappu_SimpleKVTable_clz_Torappu_StoryData<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `clz_Torappu_SimpleKVTable_clz_Torappu_StoryData` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_clz_torappu_simple_kvtable_clz_torappu_story_data_unchecked`.
pub fn size_prefixed_root_as_clz_torappu_simple_kvtable_clz_torappu_story_data_with_opts<'b, 'o>(
    opts: &'o flatbuffers::VerifierOptions,
    buf: &'b [u8],
) -> Result<clz_Torappu_SimpleKVTable_clz_Torappu_StoryData<'b>, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::size_prefixed_root_with_opts::<clz_Torappu_SimpleKVTable_clz_Torappu_StoryData<'b>>(
        opts, buf,
    )
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a clz_Torappu_SimpleKVTable_clz_Torappu_StoryData and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `clz_Torappu_SimpleKVTable_clz_Torappu_StoryData`.
pub unsafe fn root_as_clz_torappu_simple_kvtable_clz_torappu_story_data_unchecked(
    buf: &[u8],
) -> clz_Torappu_SimpleKVTable_clz_Torappu_StoryData {
    flatbuffers::root_unchecked::<clz_Torappu_SimpleKVTable_clz_Torappu_StoryData>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed clz_Torappu_SimpleKVTable_clz_Torappu_StoryData and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `clz_Torappu_SimpleKVTable_clz_Torappu_StoryData`.
pub unsafe fn size_prefixed_root_as_clz_torappu_simple_kvtable_clz_torappu_story_data_unchecked(
    buf: &[u8],
) -> clz_Torappu_SimpleKVTable_clz_Torappu_StoryData {
    flatbuffers::size_prefixed_root_unchecked::<clz_Torappu_SimpleKVTable_clz_Torappu_StoryData>(
        buf,
    )
}
#[inline]
pub fn finish_clz_torappu_simple_kvtable_clz_torappu_story_data_buffer<
    'a,
    'b,
    A: flatbuffers::Allocator + 'a,
>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<clz_Torappu_SimpleKVTable_clz_Torappu_StoryData<'a>>,
) {
    fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_clz_torappu_simple_kvtable_clz_torappu_story_data_buffer<
    'a,
    'b,
    A: flatbuffers::Allocator + 'a,
>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<clz_Torappu_SimpleKVTable_clz_Torappu_StoryData<'a>>,
) {
    fbb.finish_size_prefixed(root, None);
}
