//! Shared table metadata for the `user-data` binary (single-user export/import).
//!
//! This is the per-user counterpart to [`crate::db_export`], which moves the whole
//! database. The set below is deliberately narrower than "every table mentioning
//! `user_id`": it is the data whose existence depends solely on the user, i.e. the
//! rows a `DELETE FROM users WHERE id = $1` would take with it via `ON DELETE
//! CASCADE`, plus the join table that hangs off the user's operator plans.
//!
//! Deliberately EXCLUDED, and why:
//!   - `tier_lists` / `tiers` / `tier_placements` / `tier_list_versions` - authored
//!     content, not account data. `created_by` is ON DELETE SET NULL, so these
//!     survive the user and belong to a separate content export.
//!   - `tier_list_permissions` - a grant on someone else's list; `granted_by` is a
//!     NO ACTION FK to a third user that will not resolve in another database.
//!   - `tier_list_view_events` - telemetry (ON DELETE SET NULL).
//!   - `leaderboard_snapshot_entries` - derived, regenerated by the snapshot job.
//!   - `audit_log` / `operator_notes_audit_log` - moderation trail, not user data.
//!   - `operator_ownership_stats` and friends - server-wide aggregates recomputed by
//!     the `refresh-stats` binary.

/// One user-owned table, with everything the export and import passes need.
pub struct UserTable {
    /// Table name. Interpolated into SQL, so this must stay a hard-coded literal.
    pub name: &'static str,

    /// The column carrying the owning user's id, rewritten to the target user on
    /// import. `None` for pure join tables, which reach the user only through their
    /// parents and whose keys are uuids that travel unchanged.
    pub owner_column: Option<&'static str>,

    /// Predicate selecting this table's rows for one user, with `$1` bound to
    /// `users.id`. Aliased as `t`.
    pub filter: &'static str,

    /// Surrogate keys dropped on import so the database reassigns them. A serial id
    /// is meaningful only within the database that issued it and would collide on
    /// restore into a different one.
    pub regenerate: &'static [&'static str],

    /// Rows failing this predicate are skipped on import rather than aborting it.
    /// Used where a row points at an entity outside the export's scope, which may
    /// simply not exist in the target database.
    pub import_guard: Option<&'static str>,
}

const fn owned(name: &'static str) -> UserTable {
    UserTable {
        name,
        owner_column: Some("user_id"),
        filter: "t.user_id = $1",
        regenerate: &[],
        import_guard: None,
    }
}

/// User-owned tables in FK-topological order: parents first, so a straight replay
/// never dangles. Import deletes in the exact reverse.
///
/// `users` itself is not here - it is the anchor row and is handled separately,
/// because it is matched on its natural key rather than replaced wholesale.
pub const USER_TABLES: &[UserTable] = &[
    owned("user_status"),
    owned("user_settings"),
    // user_operator_skills/_modules carry a composite FK to user_operators
    // (user_id, operator_id), so the parent rows must land first.
    owned("user_operators"),
    owned("user_operator_skills"),
    owned("user_operator_modules"),
    owned("user_items"),
    owned("user_skins"),
    owned("user_stage_progress"),
    owned("user_roguelike_progress"),
    owned("user_sandbox_progress"),
    owned("user_enemy_progress"),
    owned("user_medals"),
    owned("user_building"),
    owned("user_checkin"),
    owned("user_scores"),
    owned("user_support_units"),
    UserTable {
        // `id` is a bigserial surrogate; the rows are identified by their content.
        regenerate: &["id"],
        ..owned("gacha_records")
    },
    owned("operator_plans"),
    owned("plan_groups"),
    UserTable {
        name: "plan_group_members",
        owner_column: None,
        filter: "t.plan_group_id IN (SELECT id FROM plan_groups WHERE user_id = $1)",
        regenerate: &[],
        import_guard: None,
    },
    UserTable {
        // A favourite points at a tier list that is outside this export. Restoring
        // into a database that lacks the list drops the row instead of failing.
        import_guard: Some("tier_list_id IN (SELECT id FROM tier_lists)"),
        ..owned("tier_list_favorites")
    },
];

/// Encrypted game credentials, exported only under `--include-credentials`.
///
/// Held apart from [`USER_TABLES`] for two reasons. It is a live credential: the
/// plaintext is a Yostar uid + token. And it is sealed with the row's `user_id` as
/// additional authenticated data, so a row whose `user_id` is remapped on import
/// can never be decrypted again - it is portable only to a database that both
/// shares `GAME_CREDENTIAL_KEY` and keeps the same `users.id`.
pub const CREDENTIALS_TABLE: UserTable = owned("user_game_credentials");

/// Marker identifying an export envelope, so a wrong file fails loudly.
pub const EXPORT_KIND: &str = "myrtle-user-export";

pub const FORMAT_VERSION: u32 = 1;
