#!/usr/bin/env python3
"""
DPS Comparison Test Runner

This script runs DPS calculations for all configured operators and outputs
reference values that can be used in Rust tests.

Usage:
    python run_comparison.py [--output results.json]
"""

import sys
import os
import json
import argparse

# Add paths
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BACKEND_DIR = os.path.dirname(os.path.dirname(SCRIPT_DIR))
sys.path.insert(0, os.path.join(BACKEND_DIR, 'scripts'))

from python_dps_harness import calculate_dps, list_operators

TEST_CASES = [
    {"operator": "twelveF", "defense": 0.0, "res": 0.0, "skill": 0, "module": -1},
    {"operator": "twelveF", "defense": 300.0, "res": 0.0, "skill": 0, "module": -1},
    {"operator": "twelveF", "defense": 0.0, "res": 20.0, "skill": 0, "module": -1},
    {"operator": "twelveF", "defense": 500.0, "res": 30.0, "skill": 0, "module": -1},
    {"operator": "twelveF", "defense": 1000.0, "res": 50.0, "skill": 0, "module": -1},
    {"operator": "Aak", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Aak", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Aak", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "Aak", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "Aak", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "Aak", "defense": 0.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Aak", "defense": 300.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Aak", "defense": 0.0, "res": 20.0, "skill": 2, "module": 1},
    {"operator": "Aak", "defense": 500.0, "res": 30.0, "skill": 2, "module": 1},
    {"operator": "Aak", "defense": 1000.0, "res": 50.0, "skill": 2, "module": 1},
    {"operator": "Absinthe", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Absinthe", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Absinthe", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "Absinthe", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "Absinthe", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "Absinthe", "defense": 0.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Absinthe", "defense": 300.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Absinthe", "defense": 0.0, "res": 20.0, "skill": 1, "module": 1},
    {"operator": "Absinthe", "defense": 500.0, "res": 30.0, "skill": 1, "module": 1},
    {"operator": "Absinthe", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 1},
    {"operator": "Aciddrop", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Aciddrop", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Aciddrop", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "Aciddrop", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "Aciddrop", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "Aciddrop", "defense": 0.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Aciddrop", "defense": 300.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Aciddrop", "defense": 0.0, "res": 20.0, "skill": 1, "module": 1},
    {"operator": "Aciddrop", "defense": 500.0, "res": 30.0, "skill": 1, "module": 1},
    {"operator": "Aciddrop", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 1},
    {"operator": "Adnachiel", "defense": 0.0, "res": 0.0, "skill": 0, "module": -1},
    {"operator": "Adnachiel", "defense": 300.0, "res": 0.0, "skill": 0, "module": -1},
    {"operator": "Adnachiel", "defense": 0.0, "res": 20.0, "skill": 0, "module": -1},
    {"operator": "Adnachiel", "defense": 500.0, "res": 30.0, "skill": 0, "module": -1},
    {"operator": "Adnachiel", "defense": 1000.0, "res": 50.0, "skill": 0, "module": -1},
    {"operator": "Andreana", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Andreana", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Andreana", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "Andreana", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "Andreana", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "Andreana", "defense": 0.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Andreana", "defense": 300.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Andreana", "defense": 0.0, "res": 20.0, "skill": 1, "module": 1},
    {"operator": "Andreana", "defense": 500.0, "res": 30.0, "skill": 1, "module": 1},
    {"operator": "Andreana", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 1},
    {"operator": "Angelina", "defense": 0.0, "res": 0.0, "skill": 0, "module": 2},
    {"operator": "Angelina", "defense": 300.0, "res": 0.0, "skill": 0, "module": 2},
    {"operator": "Angelina", "defense": 0.0, "res": 20.0, "skill": 0, "module": 2},
    {"operator": "Angelina", "defense": 500.0, "res": 30.0, "skill": 0, "module": 2},
    {"operator": "Angelina", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 2},
    {"operator": "Angelina", "defense": 0.0, "res": 0.0, "skill": 1, "module": 2},
    {"operator": "Angelina", "defense": 300.0, "res": 0.0, "skill": 1, "module": 2},
    {"operator": "Angelina", "defense": 0.0, "res": 20.0, "skill": 1, "module": 2},
    {"operator": "Angelina", "defense": 500.0, "res": 30.0, "skill": 1, "module": 2},
    {"operator": "Angelina", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 2},
    {"operator": "Angelina", "defense": 0.0, "res": 0.0, "skill": 2, "module": 2},
    {"operator": "Angelina", "defense": 300.0, "res": 0.0, "skill": 2, "module": 2},
    {"operator": "Angelina", "defense": 0.0, "res": 20.0, "skill": 2, "module": 2},
    {"operator": "Angelina", "defense": 500.0, "res": 30.0, "skill": 2, "module": 2},
    {"operator": "Angelina", "defense": 1000.0, "res": 50.0, "skill": 2, "module": 2},
    {"operator": "Aosta", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Aosta", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Aosta", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "Aosta", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "Aosta", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "Aosta", "defense": 0.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Aosta", "defense": 300.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Aosta", "defense": 0.0, "res": 20.0, "skill": 1, "module": 1},
    {"operator": "Aosta", "defense": 500.0, "res": 30.0, "skill": 1, "module": 1},
    {"operator": "Aosta", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 1},
    {"operator": "April", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "April", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "April", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "April", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "April", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "April", "defense": 0.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "April", "defense": 300.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "April", "defense": 0.0, "res": 20.0, "skill": 1, "module": 1},
    {"operator": "April", "defense": 500.0, "res": 30.0, "skill": 1, "module": 1},
    {"operator": "April", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 1},
    {"operator": "Archetto", "defense": 0.0, "res": 0.0, "skill": 0, "module": 2},
    {"operator": "Archetto", "defense": 300.0, "res": 0.0, "skill": 0, "module": 2},
    {"operator": "Archetto", "defense": 0.0, "res": 20.0, "skill": 0, "module": 2},
    {"operator": "Archetto", "defense": 500.0, "res": 30.0, "skill": 0, "module": 2},
    {"operator": "Archetto", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 2},
    {"operator": "Archetto", "defense": 0.0, "res": 0.0, "skill": 1, "module": 2},
    {"operator": "Archetto", "defense": 300.0, "res": 0.0, "skill": 1, "module": 2},
    {"operator": "Archetto", "defense": 0.0, "res": 20.0, "skill": 1, "module": 2},
    {"operator": "Archetto", "defense": 500.0, "res": 30.0, "skill": 1, "module": 2},
    {"operator": "Archetto", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 2},
    {"operator": "Archetto", "defense": 0.0, "res": 0.0, "skill": 2, "module": 2},
    {"operator": "Archetto", "defense": 300.0, "res": 0.0, "skill": 2, "module": 2},
    {"operator": "Archetto", "defense": 0.0, "res": 20.0, "skill": 2, "module": 2},
    {"operator": "Archetto", "defense": 500.0, "res": 30.0, "skill": 2, "module": 2},
    {"operator": "Archetto", "defense": 1000.0, "res": 50.0, "skill": 2, "module": 2},
    {"operator": "Arene", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Arene", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Arene", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "Arene", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "Arene", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "Arene", "defense": 0.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Arene", "defense": 300.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Arene", "defense": 0.0, "res": 20.0, "skill": 1, "module": 1},
    {"operator": "Arene", "defense": 500.0, "res": 30.0, "skill": 1, "module": 1},
    {"operator": "Arene", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 1},
    {"operator": "Asbestos", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Asbestos", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Asbestos", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "Asbestos", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "Asbestos", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "Asbestos", "defense": 0.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Asbestos", "defense": 300.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Asbestos", "defense": 0.0, "res": 20.0, "skill": 1, "module": 1},
    {"operator": "Asbestos", "defense": 500.0, "res": 30.0, "skill": 1, "module": 1},
    {"operator": "Asbestos", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 1},
    {"operator": "Ascalon", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Ascalon", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Ascalon", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "Ascalon", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "Ascalon", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "Ascalon", "defense": 0.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Ascalon", "defense": 300.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Ascalon", "defense": 0.0, "res": 20.0, "skill": 1, "module": 1},
    {"operator": "Ascalon", "defense": 500.0, "res": 30.0, "skill": 1, "module": 1},
    {"operator": "Ascalon", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 1},
    {"operator": "Ascalon", "defense": 0.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Ascalon", "defense": 300.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Ascalon", "defense": 0.0, "res": 20.0, "skill": 2, "module": 1},
    {"operator": "Ascalon", "defense": 500.0, "res": 30.0, "skill": 2, "module": 1},
    {"operator": "Ascalon", "defense": 1000.0, "res": 50.0, "skill": 2, "module": 1},
    {"operator": "Ash", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Ash", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Ash", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "Ash", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "Ash", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "Ash", "defense": 0.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Ash", "defense": 300.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Ash", "defense": 0.0, "res": 20.0, "skill": 1, "module": 1},
    {"operator": "Ash", "defense": 500.0, "res": 30.0, "skill": 1, "module": 1},
    {"operator": "Ash", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 1},
    {"operator": "Ash", "defense": 0.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Ash", "defense": 300.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Ash", "defense": 0.0, "res": 20.0, "skill": 2, "module": 1},
    {"operator": "Ash", "defense": 500.0, "res": 30.0, "skill": 2, "module": 1},
    {"operator": "Ash", "defense": 1000.0, "res": 50.0, "skill": 2, "module": 1},
    {"operator": "Ashlock", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Ashlock", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Ashlock", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "Ashlock", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "Ashlock", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "Ashlock", "defense": 0.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Ashlock", "defense": 300.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Ashlock", "defense": 0.0, "res": 20.0, "skill": 1, "module": 1},
    {"operator": "Ashlock", "defense": 500.0, "res": 30.0, "skill": 1, "module": 1},
    {"operator": "Ashlock", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 1},
    {"operator": "Bagpipe", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Bagpipe", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Bagpipe", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "Bagpipe", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "Bagpipe", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "Bagpipe", "defense": 0.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Bagpipe", "defense": 300.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Bagpipe", "defense": 0.0, "res": 20.0, "skill": 1, "module": 1},
    {"operator": "Bagpipe", "defense": 500.0, "res": 30.0, "skill": 1, "module": 1},
    {"operator": "Bagpipe", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 1},
    {"operator": "Bagpipe", "defense": 0.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Bagpipe", "defense": 300.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Bagpipe", "defense": 0.0, "res": 20.0, "skill": 2, "module": 1},
    {"operator": "Bagpipe", "defense": 500.0, "res": 30.0, "skill": 2, "module": 1},
    {"operator": "Bagpipe", "defense": 1000.0, "res": 50.0, "skill": 2, "module": 1},
    {"operator": "Blaze", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Blaze", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Blaze", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "Blaze", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "Blaze", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "Blaze", "defense": 0.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Blaze", "defense": 300.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Blaze", "defense": 0.0, "res": 20.0, "skill": 1, "module": 1},
    {"operator": "Blaze", "defense": 500.0, "res": 30.0, "skill": 1, "module": 1},
    {"operator": "Blaze", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 1},
    {"operator": "BluePoison", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "BluePoison", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "BluePoison", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "BluePoison", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "BluePoison", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "BluePoison", "defense": 0.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "BluePoison", "defense": 300.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "BluePoison", "defense": 0.0, "res": 20.0, "skill": 1, "module": 1},
    {"operator": "BluePoison", "defense": 500.0, "res": 30.0, "skill": 1, "module": 1},
    {"operator": "BluePoison", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 1},
    {"operator": "Ceobe", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Ceobe", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Ceobe", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "Ceobe", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "Ceobe", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "Ceobe", "defense": 0.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Ceobe", "defense": 300.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Ceobe", "defense": 0.0, "res": 20.0, "skill": 1, "module": 1},
    {"operator": "Ceobe", "defense": 500.0, "res": 30.0, "skill": 1, "module": 1},
    {"operator": "Ceobe", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 1},
    {"operator": "Ceobe", "defense": 0.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Ceobe", "defense": 300.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Ceobe", "defense": 0.0, "res": 20.0, "skill": 2, "module": 1},
    {"operator": "Ceobe", "defense": 500.0, "res": 30.0, "skill": 2, "module": 1},
    {"operator": "Ceobe", "defense": 1000.0, "res": 50.0, "skill": 2, "module": 1},
    {"operator": "Chen", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Chen", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Chen", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "Chen", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "Chen", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "Chen", "defense": 0.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Chen", "defense": 300.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Chen", "defense": 0.0, "res": 20.0, "skill": 1, "module": 1},
    {"operator": "Chen", "defense": 500.0, "res": 30.0, "skill": 1, "module": 1},
    {"operator": "Chen", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 1},
    {"operator": "Chen", "defense": 0.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Chen", "defense": 300.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Chen", "defense": 0.0, "res": 20.0, "skill": 2, "module": 1},
    {"operator": "Chen", "defense": 500.0, "res": 30.0, "skill": 2, "module": 1},
    {"operator": "Chen", "defense": 1000.0, "res": 50.0, "skill": 2, "module": 1},
    {"operator": "Exusiai", "defense": 0.0, "res": 0.0, "skill": 0, "module": 2},
    {"operator": "Exusiai", "defense": 300.0, "res": 0.0, "skill": 0, "module": 2},
    {"operator": "Exusiai", "defense": 0.0, "res": 20.0, "skill": 0, "module": 2},
    {"operator": "Exusiai", "defense": 500.0, "res": 30.0, "skill": 0, "module": 2},
    {"operator": "Exusiai", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 2},
    {"operator": "Exusiai", "defense": 0.0, "res": 0.0, "skill": 1, "module": 2},
    {"operator": "Exusiai", "defense": 300.0, "res": 0.0, "skill": 1, "module": 2},
    {"operator": "Exusiai", "defense": 0.0, "res": 20.0, "skill": 1, "module": 2},
    {"operator": "Exusiai", "defense": 500.0, "res": 30.0, "skill": 1, "module": 2},
    {"operator": "Exusiai", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 2},
    {"operator": "Exusiai", "defense": 0.0, "res": 0.0, "skill": 2, "module": 2},
    {"operator": "Exusiai", "defense": 300.0, "res": 0.0, "skill": 2, "module": 2},
    {"operator": "Exusiai", "defense": 0.0, "res": 20.0, "skill": 2, "module": 2},
    {"operator": "Exusiai", "defense": 500.0, "res": 30.0, "skill": 2, "module": 2},
    {"operator": "Exusiai", "defense": 1000.0, "res": 50.0, "skill": 2, "module": 2},
    {"operator": "Eyjafjalla", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Eyjafjalla", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Eyjafjalla", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "Eyjafjalla", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "Eyjafjalla", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "Eyjafjalla", "defense": 0.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Eyjafjalla", "defense": 300.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Eyjafjalla", "defense": 0.0, "res": 20.0, "skill": 1, "module": 1},
    {"operator": "Eyjafjalla", "defense": 500.0, "res": 30.0, "skill": 1, "module": 1},
    {"operator": "Eyjafjalla", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 1},
    {"operator": "Eyjafjalla", "defense": 0.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Eyjafjalla", "defense": 300.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Eyjafjalla", "defense": 0.0, "res": 20.0, "skill": 2, "module": 1},
    {"operator": "Eyjafjalla", "defense": 500.0, "res": 30.0, "skill": 2, "module": 1},
    {"operator": "Eyjafjalla", "defense": 1000.0, "res": 50.0, "skill": 2, "module": 1},
    {"operator": "Ifrit", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Ifrit", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Ifrit", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "Ifrit", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "Ifrit", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "Ifrit", "defense": 0.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Ifrit", "defense": 300.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Ifrit", "defense": 0.0, "res": 20.0, "skill": 1, "module": 1},
    {"operator": "Ifrit", "defense": 500.0, "res": 30.0, "skill": 1, "module": 1},
    {"operator": "Ifrit", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 1},
    {"operator": "Ifrit", "defense": 0.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Ifrit", "defense": 300.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Ifrit", "defense": 0.0, "res": 20.0, "skill": 2, "module": 1},
    {"operator": "Ifrit", "defense": 500.0, "res": 30.0, "skill": 2, "module": 1},
    {"operator": "Ifrit", "defense": 1000.0, "res": 50.0, "skill": 2, "module": 1},
    {"operator": "Mlynar", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Mlynar", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Mlynar", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "Mlynar", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "Mlynar", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "Mlynar", "defense": 0.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Mlynar", "defense": 300.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Mlynar", "defense": 0.0, "res": 20.0, "skill": 1, "module": 1},
    {"operator": "Mlynar", "defense": 500.0, "res": 30.0, "skill": 1, "module": 1},
    {"operator": "Mlynar", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 1},
    {"operator": "Mlynar", "defense": 0.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Mlynar", "defense": 300.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Mlynar", "defense": 0.0, "res": 20.0, "skill": 2, "module": 1},
    {"operator": "Mlynar", "defense": 500.0, "res": 30.0, "skill": 2, "module": 1},
    {"operator": "Mlynar", "defense": 1000.0, "res": 50.0, "skill": 2, "module": 1},
    {"operator": "Mountain", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Mountain", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Mountain", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "Mountain", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "Mountain", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "Mountain", "defense": 0.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Mountain", "defense": 300.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Mountain", "defense": 0.0, "res": 20.0, "skill": 1, "module": 1},
    {"operator": "Mountain", "defense": 500.0, "res": 30.0, "skill": 1, "module": 1},
    {"operator": "Mountain", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 1},
    {"operator": "Mountain", "defense": 0.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Mountain", "defense": 300.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Mountain", "defense": 0.0, "res": 20.0, "skill": 2, "module": 1},
    {"operator": "Mountain", "defense": 500.0, "res": 30.0, "skill": 2, "module": 1},
    {"operator": "Mountain", "defense": 1000.0, "res": 50.0, "skill": 2, "module": 1},
    {"operator": "Mudrock", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Mudrock", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Mudrock", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "Mudrock", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "Mudrock", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "Mudrock", "defense": 0.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Mudrock", "defense": 300.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Mudrock", "defense": 0.0, "res": 20.0, "skill": 1, "module": 1},
    {"operator": "Mudrock", "defense": 500.0, "res": 30.0, "skill": 1, "module": 1},
    {"operator": "Mudrock", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 1},
    {"operator": "Mudrock", "defense": 0.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Mudrock", "defense": 300.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Mudrock", "defense": 0.0, "res": 20.0, "skill": 2, "module": 1},
    {"operator": "Mudrock", "defense": 500.0, "res": 30.0, "skill": 2, "module": 1},
    {"operator": "Mudrock", "defense": 1000.0, "res": 50.0, "skill": 2, "module": 1},
    {"operator": "Rosa", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Rosa", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Rosa", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "Rosa", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "Rosa", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "Rosa", "defense": 0.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Rosa", "defense": 300.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Rosa", "defense": 0.0, "res": 20.0, "skill": 1, "module": 1},
    {"operator": "Rosa", "defense": 500.0, "res": 30.0, "skill": 1, "module": 1},
    {"operator": "Rosa", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 1},
    {"operator": "Rosa", "defense": 0.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Rosa", "defense": 300.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Rosa", "defense": 0.0, "res": 20.0, "skill": 2, "module": 1},
    {"operator": "Rosa", "defense": 500.0, "res": 30.0, "skill": 2, "module": 1},
    {"operator": "Rosa", "defense": 1000.0, "res": 50.0, "skill": 2, "module": 1},
    {"operator": "Schwarz", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Schwarz", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Schwarz", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "Schwarz", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "Schwarz", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "Schwarz", "defense": 0.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Schwarz", "defense": 300.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Schwarz", "defense": 0.0, "res": 20.0, "skill": 1, "module": 1},
    {"operator": "Schwarz", "defense": 500.0, "res": 30.0, "skill": 1, "module": 1},
    {"operator": "Schwarz", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 1},
    {"operator": "Schwarz", "defense": 0.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Schwarz", "defense": 300.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Schwarz", "defense": 0.0, "res": 20.0, "skill": 2, "module": 1},
    {"operator": "Schwarz", "defense": 500.0, "res": 30.0, "skill": 2, "module": 1},
    {"operator": "Schwarz", "defense": 1000.0, "res": 50.0, "skill": 2, "module": 1},
    {"operator": "SilverAsh", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "SilverAsh", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "SilverAsh", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "SilverAsh", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "SilverAsh", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "SilverAsh", "defense": 0.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "SilverAsh", "defense": 300.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "SilverAsh", "defense": 0.0, "res": 20.0, "skill": 1, "module": 1},
    {"operator": "SilverAsh", "defense": 500.0, "res": 30.0, "skill": 1, "module": 1},
    {"operator": "SilverAsh", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 1},
    {"operator": "SilverAsh", "defense": 0.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "SilverAsh", "defense": 300.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "SilverAsh", "defense": 0.0, "res": 20.0, "skill": 2, "module": 1},
    {"operator": "SilverAsh", "defense": 500.0, "res": 30.0, "skill": 2, "module": 1},
    {"operator": "SilverAsh", "defense": 1000.0, "res": 50.0, "skill": 2, "module": 1},
    {"operator": "Surtr", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Surtr", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Surtr", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "Surtr", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "Surtr", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "Surtr", "defense": 0.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Surtr", "defense": 300.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Surtr", "defense": 0.0, "res": 20.0, "skill": 1, "module": 1},
    {"operator": "Surtr", "defense": 500.0, "res": 30.0, "skill": 1, "module": 1},
    {"operator": "Surtr", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 1},
    {"operator": "Surtr", "defense": 0.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Surtr", "defense": 300.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Surtr", "defense": 0.0, "res": 20.0, "skill": 2, "module": 1},
    {"operator": "Surtr", "defense": 500.0, "res": 30.0, "skill": 2, "module": 1},
    {"operator": "Surtr", "defense": 1000.0, "res": 50.0, "skill": 2, "module": 1},
    {"operator": "Thorns", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Thorns", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "Thorns", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "Thorns", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "Thorns", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "Thorns", "defense": 0.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Thorns", "defense": 300.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "Thorns", "defense": 0.0, "res": 20.0, "skill": 1, "module": 1},
    {"operator": "Thorns", "defense": 500.0, "res": 30.0, "skill": 1, "module": 1},
    {"operator": "Thorns", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 1},
    {"operator": "Thorns", "defense": 0.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Thorns", "defense": 300.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "Thorns", "defense": 0.0, "res": 20.0, "skill": 2, "module": 1},
    {"operator": "Thorns", "defense": 500.0, "res": 30.0, "skill": 2, "module": 1},
    {"operator": "Thorns", "defense": 1000.0, "res": 50.0, "skill": 2, "module": 1},
    {"operator": "W", "defense": 0.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "W", "defense": 300.0, "res": 0.0, "skill": 0, "module": 1},
    {"operator": "W", "defense": 0.0, "res": 20.0, "skill": 0, "module": 1},
    {"operator": "W", "defense": 500.0, "res": 30.0, "skill": 0, "module": 1},
    {"operator": "W", "defense": 1000.0, "res": 50.0, "skill": 0, "module": 1},
    {"operator": "W", "defense": 0.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "W", "defense": 300.0, "res": 0.0, "skill": 1, "module": 1},
    {"operator": "W", "defense": 0.0, "res": 20.0, "skill": 1, "module": 1},
    {"operator": "W", "defense": 500.0, "res": 30.0, "skill": 1, "module": 1},
    {"operator": "W", "defense": 1000.0, "res": 50.0, "skill": 1, "module": 1},
    {"operator": "W", "defense": 0.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "W", "defense": 300.0, "res": 0.0, "skill": 2, "module": 1},
    {"operator": "W", "defense": 0.0, "res": 20.0, "skill": 2, "module": 1},
    {"operator": "W", "defense": 500.0, "res": 30.0, "skill": 2, "module": 1},
    {"operator": "W", "defense": 1000.0, "res": 50.0, "skill": 2, "module": 1},
]


def run_all_tests(output_file=None):
    """Run all test cases and collect results."""
    results = []
    errors = []

    print(f"Running {len(TEST_CASES)} test cases...")

    for i, tc in enumerate(TEST_CASES):
        result = calculate_dps(
            operator_name=tc['operator'],
            defense=tc['defense'],
            res=tc['res'],
            skill=tc['skill'],
            module=tc['module'],
        )

        if 'error' in result:
            errors.append(result)
            print(f"  [{i+1}/{len(TEST_CASES)}] {tc['operator']} S{tc['skill']+1} - ERROR: {result['error']}")
        else:
            results.append(result)
            print(f"  [{i+1}/{len(TEST_CASES)}] {tc['operator']} S{tc['skill']+1} def={tc['defense']:.0f} res={tc['res']:.0f} -> DPS: {result['dps']:.2f}")

    print()
    print(f"Completed: {len(results)} successful, {len(errors)} errors")

    if output_file:
        with open(output_file, 'w') as f:
            json.dump({
                'results': results,
                'errors': errors,
            }, f, indent=2)
        print(f"Results saved to {output_file}")

    return results, errors


def generate_rust_expected_values(results):
    """Generate Rust code with expected values from Python results."""
    print("\n// Expected DPS values from Python reference implementation")
    print("// Copy these into your Rust tests\n")

    for r in results:
        skill_name = f"s{r.get('skill', 0) + 1}" if r.get('skill', -1) >= 0 else "base"
        print(f"// {r['operator']} {skill_name} def={r['defense']:.0f} res={r['res']:.0f}")
        print(f"// Expected DPS: {r['dps']:.2f}")
        print()


def main():
    parser = argparse.ArgumentParser(description='Run DPS comparison tests')
    parser.add_argument('--output', '-o', help='Output JSON file for results')
    parser.add_argument('--rust-values', action='store_true', help='Generate Rust expected values')
    args = parser.parse_args()

    results, errors = run_all_tests(args.output)

    if args.rust_values:
        generate_rust_expected_values(results)

    sys.exit(0 if len(errors) == 0 else 1)


if __name__ == '__main__':
    main()
