import { ModulesSkinsCard } from "frontend";

interface IGapOp {
    id: string;
    operatorId: string;
    name: string;
    charId: string;
    rarity: number;
    sub?: string;
}

const gapOp = (charId: string, name: string, rarity: number, sub: string): IGapOp => ({ id: `${charId}-${sub}`, operatorId: charId, charId, name, rarity, sub });

const LOCKED = [gapOp("char_4087_ines", "Ines", 6, "ARC-Y"), gapOp("char_1013_chen2", "Ch'en the Holungday", 6, "SWD-Y"), gapOp("char_017_huang", "Blaze", 5, "CEN-X"), gapOp("char_4045_heidi", "Heidi", 5, "MSC-X")];

const BELOW_MAX = [gapOp("char_263_skadi", "Skadi", 6, "Lv 1 / 3"), gapOp("char_102_texas", "Texas", 5, "Lv 2 / 3"), gapOp("char_350_surtr", "Surtr", 6, "Lv 2 / 3")];

// A slice of the /skins/index projection — the shape the Stats tab passes down.
const skin = (skinId: string, charId: string, skinName: string, skinGroupName: string, skinGroupId: string, skinGroupSortIndex: number, displayTagId: string | null, getTime: number, sortId: number) => ({
    skinId,
    charId,
    displaySkin: { skinName, skinGroupId, skinGroupName, skinGroupSortIndex, displayTagId, getTime, sortId, description: null, content: "", dialog: null, usage: null, obtainApproach: null, designerList: null, drawerList: [] },
});

const SKIN_LIST = [
    skin("char_4064_mlynar@epoque#28", "char_4064_mlynar", "W Dali", "EPOQUE/XXVIII", "2023#epoque#10", 48, null, 1714496400, 93),
    skin("char_263_skadi@marthe#5", "char_263_skadi", "The Next Afternoon Tea", "MARTHE/V", "2023#marthe", 130, null, 1701190800, 237),
    skin("char_102_texas@winter#1", "char_102_texas", "Winter Messenger", "Cambrian/I", "2018#winter", 143, null, 1580943600, 256),
    skin("char_180_amgoat@sanrio#2", "char_180_amgoat", "Fluffy Little Witch", "Sanrio characters/II", "2025#sanrio", 227, "From collabs", 1772809200, 403),
    skin("char_1028_texas2@iteration#1", "char_1028_texas2", "Wingbreaker", "Iteration Provident", "2023#iteration", 216, null, 1714496400, 450),
    skin("char_4045_heidi@epoque#24", "char_4045_heidi", "A Thousand Correspondences", "EPOQUE/XXIV", "2023#epoque#6", 44, null, 1698148800, 87),
    skin("char_002_amiya@epoque#4", "char_002_amiya", "Fresh Fastener", "Test Collection/II", "2020#sale", 3, "Event Reward", 1609585200, 4),
    skin("char_293_thorns@boc#8", "char_293_thorns", "Blade-cleaved Tides", "Bloodline of Combat/VIII", "2024#boc", 177, null, 1730394000, 326),
    skin("char_350_surtr@summer#9", "char_350_surtr", "Colorful Wonderland CW03", "Coral Coast/IX", "2022#summer#2", 113, null, 1673611200, 206),
    skin("char_4087_ines@boc#8", "char_4087_ines", "Under the Flaming Dome", "Bloodline of Combat/VIII", "2024#boc", 177, null, 1730394000, 325),
    skin("char_003_kalts@boc#6", "char_003_kalts", "Remnant", "Bloodline of Combat/VI", "2023#boc", 175, null, 1699376400, 318),
    skin("char_017_huang@witch#5", "char_017_huang", "Explosive Blue Flame", "Witch Feast/V", "2024#witch", 142, null, 1744113600, 447),
];

const CHAR_SKINS = Object.fromEntries(SKIN_LIST.map((s) => [s.skinId, s]));

/** Real `/api/operators/index` entries (fetched 2026-10-08), the shape `operatorsIndex` takes. */
const OPERATORS = [
    {"id": "char_4064_mlynar", "name": "Młynar", "appellation": " ", "rarity": 6, "profession": "WARRIOR", "subProfessionId": "librator", "position": "MELEE", "tagList": ["DPS", "Nuker"], "nationId": "kazimierz", "isNotObtainable": false, "groupId": null, "teamId": null, "professionName": "Guard", "subProfessionName": "Liberator", "nationName": "Kazimierz", "groupName": null, "teamName": null, "obtainChannel": "headhunting", "artists": ["竜崎いち"], "portrait": "/portraits/char_4064_mlynar_2.png", "gender": "Male", "race": "Kuranta", "placeOfBirth": "Kazimierz", "stats": {"hp": 3906, "atk": 355, "def": 502, "res": 15.0, "cost": 12, "block": 3}, "hasOffensiveRecovery": false, "hasDefensiveRecovery": false, "allSkillsManual": true, "voiceActors": ["Yuhang Wang", "Anthony Howell", "Rikiya Koyama", "Choi Hyun-su"], "phaseMaxLevels": [50, 80, 90], "skillCount": 3, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_mlynar", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_mlynar", "typeName1": "LIB", "typeName2": "X", "type": "ADVANCED"}], "dateOfBirth": "Dec 3"},
    {"id": "char_263_skadi", "name": "Skadi", "appellation": " ", "rarity": 6, "profession": "WARRIOR", "subProfessionId": "fearless", "position": "MELEE", "tagList": ["DPS", "Survival"], "nationId": "egir", "isNotObtainable": false, "groupId": "abyssal", "teamId": null, "professionName": "Guard", "subProfessionName": "Dreadnought", "nationName": "Ægir", "groupName": "Abyssal Hunters", "teamName": null, "obtainChannel": "headhunting", "artists": ["alchemaniac"], "portrait": "/portraits/char_263_skadi_2.png", "gender": "Female", "race": "Unknown", "placeOfBirth": "Ægir", "stats": {"hp": 3866, "atk": 1015, "def": 263, "res": 0.0, "cost": 19, "block": 1}, "hasOffensiveRecovery": false, "hasDefensiveRecovery": false, "allSkillsManual": false, "voiceActors": ["Kiiki", "Cristina Vee", "Rina Sato", "Kim Na-yul"], "phaseMaxLevels": [50, 80, 90], "skillCount": 3, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_skadi", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_skadi", "typeName1": "DRE", "typeName2": "Y", "type": "ADVANCED"}, {"uniEquipId": "uniequip_003_skadi", "typeName1": "DRE", "typeName2": "X", "type": "ADVANCED"}], "dateOfBirth": "Mar. 7"},
    {"id": "char_102_texas", "name": "Texas", "appellation": " ", "rarity": 5, "profession": "PIONEER", "subProfessionId": "pioneer", "position": "MELEE", "tagList": ["DP-Recovery", "Crowd-Control"], "nationId": "lungmen", "isNotObtainable": false, "groupId": "penguin", "teamId": null, "professionName": "Vanguard", "subProfessionName": "Pioneer", "nationName": "Yan-Lungmen", "groupName": "Penguin Logistics", "teamName": null, "obtainChannel": "headhunting", "artists": ["幻象黑兔"], "portrait": "/portraits/char_102_texas_2.png", "gender": "Female", "race": "Lupo", "placeOfBirth": "Columbia", "stats": {"hp": 1950, "atk": 500, "def": 343, "res": 0.0, "cost": 13, "block": 2}, "hasOffensiveRecovery": false, "hasDefensiveRecovery": false, "allSkillsManual": false, "voiceActors": ["Menglu Yang", "Jessica Preddy", "Ilaria Silvestri", "Azusa Tadokoro", "Kim Chae-ha"], "phaseMaxLevels": [50, 70, 80], "skillCount": 2, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_texas", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_texas", "typeName1": "SOL", "typeName2": "Y", "type": "ADVANCED"}], "dateOfBirth": "Jun. 1"},
    {"id": "char_180_amgoat", "name": "Eyjafjalla", "appellation": " ", "rarity": 6, "profession": "CASTER", "subProfessionId": "corecaster", "position": "RANGED", "tagList": ["DPS", "Debuff"], "nationId": "leithanien", "isNotObtainable": false, "groupId": null, "teamId": null, "professionName": "Caster", "subProfessionName": "Core Caster", "nationName": "Leithanien", "groupName": null, "teamName": null, "obtainChannel": "headhunting", "artists": ["Anmi"], "portrait": "/portraits/char_180_amgoat_2.png", "gender": "Female", "race": "Caprinae", "placeOfBirth": "Leithanien", "stats": {"hp": 1743, "atk": 645, "def": 122, "res": 20.0, "cost": 21, "block": 1}, "hasOffensiveRecovery": false, "hasDefensiveRecovery": false, "allSkillsManual": false, "voiceActors": ["Cool", "Hollie Taylor", "Risa Taneda", "Kim Ha-ru"], "phaseMaxLevels": [50, 80, 90], "skillCount": 3, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_amgoat", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_amgoat", "typeName1": "CCR", "typeName2": "X", "type": "ADVANCED"}, {"uniEquipId": "uniequip_003_amgoat", "typeName1": "CCR", "typeName2": "Y", "type": "ADVANCED"}], "dateOfBirth": "Oct. 18"},
    {"id": "char_1028_texas2", "name": "Texas the Omertosa", "appellation": " ", "rarity": 6, "profession": "SPECIAL", "subProfessionId": "executor", "position": "MELEE", "tagList": ["Fast-Redeploy", "DPS"], "nationId": "lungmen", "isNotObtainable": false, "groupId": "penguin", "teamId": null, "professionName": "Specialist", "subProfessionName": "Executor", "nationName": "Yan-Lungmen", "groupName": "Penguin Logistics", "teamName": null, "obtainChannel": "headhunting", "artists": ["Studio Montagne", "幻象黑兔"], "portrait": "/portraits/char_1028_texas2_2.png", "gender": "Female", "race": "Lupo", "placeOfBirth": "Columbia", "stats": {"hp": 1598, "atk": 569, "def": 320, "res": 0.0, "cost": 10, "block": 1}, "hasOffensiveRecovery": false, "hasDefensiveRecovery": false, "allSkillsManual": false, "voiceActors": ["Menglu Yang", "Jessica Preddy", "Ilaria Silvestri", "Azusa Tadokoro", "Kim Chae-ha"], "phaseMaxLevels": [50, 80, 90], "skillCount": 3, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_texas2", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_texas2", "typeName1": "EXE", "typeName2": "Y", "type": "ADVANCED"}], "dateOfBirth": "Jun 1"},
    {"id": "char_4045_heidi", "name": "Heidi", "appellation": " ", "rarity": 5, "profession": "SUPPORT", "subProfessionId": "bard", "position": "RANGED", "tagList": ["Support", "Healing"], "nationId": "victoria", "isNotObtainable": false, "groupId": null, "teamId": null, "professionName": "Supporter", "subProfessionName": "Bard", "nationName": "Victoria", "groupName": null, "teamName": null, "obtainChannel": "event", "artists": ["熊太"], "portrait": "/portraits/char_4045_heidi_2.png", "gender": "Female", "race": "Feline", "placeOfBirth": "Victoria", "stats": {"hp": 1260, "atk": 320, "def": 268, "res": 0.0, "cost": 9, "block": 1}, "hasOffensiveRecovery": false, "hasDefensiveRecovery": false, "allSkillsManual": true, "voiceActors": ["Ying Xie", "Sophie Shad", "Akira Sekine", "Sung Ye-won"], "phaseMaxLevels": [50, 70, 80], "skillCount": 2, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_heidi", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_heidi", "typeName1": "BAR", "typeName2": "X", "type": "ADVANCED"}], "dateOfBirth": "Mar 26"},
    {"id": "char_002_amiya", "name": "Amiya", "appellation": " ", "rarity": 5, "profession": "CASTER", "subProfessionId": "corecaster", "position": "RANGED", "tagList": ["DPS"], "nationId": "rhodes", "isNotObtainable": false, "groupId": null, "teamId": null, "professionName": "Caster", "subProfessionName": "Core Caster", "nationName": "Rhodes Island", "groupName": null, "teamName": null, "obtainChannel": "other", "artists": ["唯@W"], "portrait": "/portraits/char_002_amiya_2.png", "gender": "Female", "race": "Cautus/Chimera", "placeOfBirth": "Rim Billiton", "stats": {"hp": 1480, "atk": 612, "def": 121, "res": 20.0, "cost": 20, "block": 1}, "hasOffensiveRecovery": false, "hasDefensiveRecovery": false, "allSkillsManual": false, "voiceActors": ["Dian Tao", "Emma Ballantine", "Tomoyo Kurosawa", "Lee Ji-hyun"], "phaseMaxLevels": [50, 70, 80], "skillCount": 3, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_amiya", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_amiya", "typeName1": "CCR", "typeName2": "Y", "type": "ADVANCED"}], "dateOfBirth": "Dec. 23"},
    {"id": "char_293_thorns", "name": "Thorns", "appellation": " ", "rarity": 6, "profession": "WARRIOR", "subProfessionId": "lord", "position": "MELEE", "tagList": ["DPS", "Defense"], "nationId": "iberia", "isNotObtainable": false, "groupId": null, "teamId": null, "professionName": "Guard", "subProfessionName": "Lord", "nationName": "Iberia", "groupName": null, "teamName": null, "obtainChannel": "headhunting", "artists": ["Studio Montagne", "幻象黑兔"], "portrait": "/portraits/char_293_thorns_2.png", "gender": "Male", "race": "Ægir", "placeOfBirth": "Iberia", "stats": {"hp": 2612, "atk": 711, "def": 402, "res": 10.0, "cost": 20, "block": 2}, "hasOffensiveRecovery": true, "hasDefensiveRecovery": false, "allSkillsManual": true, "voiceActors": ["Ethan", "Javier Bañas", "Kaito Ishikawa", "Hong Bum-ki"], "phaseMaxLevels": [50, 80, 90], "skillCount": 3, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_thorns", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_thorns", "typeName1": "LOR", "typeName2": "X", "type": "ADVANCED"}, {"uniEquipId": "uniequip_003_thorns", "typeName1": "LOR", "typeName2": "D", "type": "ADVANCED"}], "dateOfBirth": "Mar 17"},
    {"id": "char_350_surtr", "name": "Surtr", "appellation": " ", "rarity": 6, "profession": "WARRIOR", "subProfessionId": "artsfghter", "position": "MELEE", "tagList": ["DPS"], "nationId": "rhodes", "isNotObtainable": false, "groupId": null, "teamId": null, "professionName": "Guard", "subProfessionName": "Arts Fighter", "nationName": "Rhodes Island", "groupName": null, "teamName": null, "obtainChannel": "headhunting", "artists": ["Ask"], "portrait": "/portraits/char_350_surtr_2.png", "gender": "Female", "race": "Sarkaz", "placeOfBirth": "Unknown", "stats": {"hp": 2916, "atk": 672, "def": 414, "res": 15.0, "cost": 21, "block": 1}, "hasOffensiveRecovery": true, "hasDefensiveRecovery": false, "allSkillsManual": false, "voiceActors": ["Yi Zhu", "Kira Buckland", "Yui Horie", "Seo Yu-ri"], "phaseMaxLevels": [50, 80, 90], "skillCount": 3, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_surtr", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_surtr", "typeName1": "AFT", "typeName2": "X", "type": "ADVANCED"}, {"uniEquipId": "uniequip_003_surtr", "typeName1": "AFT", "typeName2": "Y", "type": "ADVANCED"}], "dateOfBirth": "Jan 22"},
    {"id": "char_4087_ines", "name": "Ines", "appellation": " ", "rarity": 6, "profession": "PIONEER", "subProfessionId": "agent", "position": "MELEE", "tagList": ["DP-Recovery", "Fast-Redeploy"], "nationId": "", "isNotObtainable": false, "groupId": "babel", "teamId": null, "professionName": "Vanguard", "subProfessionName": "Agent", "nationName": null, "groupName": "Babel", "teamName": null, "obtainChannel": "headhunting", "artists": ["板板"], "portrait": "/portraits/char_4087_ines_2.png", "gender": "Female", "race": "Undisclosed", "placeOfBirth": "Kazdel", "stats": {"hp": 2121, "atk": 589, "def": 281, "res": 0.0, "cost": 11, "block": 1}, "hasOffensiveRecovery": true, "hasDefensiveRecovery": false, "allSkillsManual": false, "voiceActors": ["Ruoyu Zhang", "Erica Lindbeck", "Ayumi Tsunematsu", "Shin Na-ri"], "phaseMaxLevels": [50, 80, 90], "skillCount": 3, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_ines", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_ines", "typeName1": "AGE", "typeName2": "Y", "type": "ADVANCED"}], "dateOfBirth": "Feb 19"},
    {"id": "char_003_kalts", "name": "Kal'tsit", "appellation": " ", "rarity": 6, "profession": "MEDIC", "subProfessionId": "physician", "position": "RANGED", "tagList": ["Summon", "Healing"], "nationId": "rhodes", "isNotObtainable": false, "groupId": null, "teamId": null, "professionName": "Medic", "subProfessionName": "Medic", "nationName": "Rhodes Island", "groupName": null, "teamName": null, "obtainChannel": "headhunting", "artists": ["红色彗星", "唯@W", "伍秋秋秋秋"], "portrait": "/portraits/char_003_kalts_2.png", "gender": "Female", "race": "Feline", "placeOfBirth": "Rhodes Island", "stats": {"hp": 1633, "atk": 490, "def": 215, "res": 0.0, "cost": 20, "block": 1}, "hasOffensiveRecovery": false, "hasDefensiveRecovery": false, "allSkillsManual": true, "voiceActors": ["Xue Liu", "Sura Siu", "Yoko Hikasa", "Han Chae-eon"], "phaseMaxLevels": [50, 80, 90], "skillCount": 3, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_kalts", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_kalts", "typeName1": "PHY", "typeName2": "X", "type": "ADVANCED"}, {"uniEquipId": "uniequip_003_kalts", "typeName1": "PHY", "typeName2": "Y", "type": "ADVANCED"}, {"uniEquipId": "uniequip_004_kalts", "typeName1": "ISW", "typeName2": "A", "type": "ADVANCED"}], "dateOfBirth": "Undisclosed"},
    {"id": "char_017_huang", "name": "Blaze", "appellation": " ", "rarity": 6, "profession": "WARRIOR", "subProfessionId": "centurion", "position": "MELEE", "tagList": ["DPS", "Survival"], "nationId": "rhodes", "isNotObtainable": false, "groupId": "elite", "teamId": null, "professionName": "Guard", "subProfessionName": "Centurion", "nationName": "Rhodes Island", "groupName": "Rhodes Island-Elite Operator", "teamName": null, "obtainChannel": "headhunting", "artists": ["唯@W", "Mag42"], "portrait": "/portraits/char_017_huang_2.png", "gender": "Female", "race": "Feline", "placeOfBirth": "Victoria", "stats": {"hp": 2821, "atk": 765, "def": 370, "res": 0.0, "cost": 24, "block": 3}, "hasOffensiveRecovery": true, "hasDefensiveRecovery": false, "allSkillsManual": false, "voiceActors": ["Atom", "Cristina Vee", "Mai Nakahara", "Kim Yeon-woo"], "phaseMaxLevels": [50, 80, 90], "skillCount": 3, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_huang", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_huang", "typeName1": "CEN", "typeName2": "X", "type": "ADVANCED"}, {"uniEquipId": "uniequip_003_huang", "typeName1": "CEN", "typeName2": "Y", "type": "ADVANCED"}], "dateOfBirth": "Undisclosed"},
];

const OWNED = new Set(["char_263_skadi@marthe#5", "char_102_texas@winter#1", "char_293_thorns@boc#8", "char_350_surtr@summer#9", "char_017_huang@witch#5"]);

export const Veteran = () => (
    <div className="w-full max-w-md">
        <ModulesSkinsCard
            charSkins={CHAR_SKINS}
            modules={{ unlocked: 117, atMax: 94, totalAvailable: 211, details: { locked: LOCKED, belowMax: BELOW_MAX } }}
            operatorsIndex={OPERATORS}
            ownedSkinIds={OWNED}
            skins={{ totalOwned: 63, totalAvailable: 472, percentage: 13.3 }}
        />
    </div>
);

export const EarlyAccount = () => (
    <div className="w-full max-w-md">
        <ModulesSkinsCard
            charSkins={CHAR_SKINS}
            modules={{ unlocked: 6, atMax: 1, totalAvailable: 38, details: { locked: LOCKED, belowMax: BELOW_MAX } }}
            operatorsIndex={OPERATORS}
            ownedSkinIds={new Set()}
            skins={{ totalOwned: 2, totalAvailable: 472, percentage: 0.4 }}
        />
    </div>
);

export const ModulesMaxed = () => (
    <div className="w-full max-w-md">
        <ModulesSkinsCard
            charSkins={CHAR_SKINS}
            modules={{ unlocked: 211, atMax: 211, totalAvailable: 211, details: { locked: [], belowMax: [] } }}
            operatorsIndex={OPERATORS}
            ownedSkinIds={OWNED}
            skins={{ totalOwned: 472, totalAvailable: 472, percentage: 100 }}
        />
    </div>
);
