import { ProfileStatsTab } from "frontend";

// StatsTab is data-coupled: it reads the skins index, the user's owned skins
// and the check-in record through TanStack Query, and renders StatsTabSkeleton
// until the skins index resolves. Preview server functions are stubbed, so the
// honest card for this container is its loading state — the roster and static
// operator props below are real-shaped so the memoized stats still compute.
const entry = (operatorId: string, elite: number, level: number, mastery: number, moduleLevel: number) => ({
    user_id: "1000123456",
    operator_id: operatorId,
    elite,
    level,
    exp: 0,
    potential: 1,
    skill_level: 7,
    favor_point: 25_570,
    skin_id: null,
    default_skill: 0,
    voice_lan: "JP",
    current_equip: null,
    current_tmpl: null,
    obtained_at: 1_690_000_000,
    masteries: [0, 1, 2].map((index) => ({ index, mastery })),
    modules: [{ id: `uniequip_002_${operatorId.split("_").slice(2).join("_")}`, level: moduleLevel, locked: false }],
});

/** Real `/api/operators/index` entries (fetched 2026-10-08), the shape `operatorsIndex` takes. */
const OPERATORS = [
    {"id": "char_4064_mlynar", "name": "Młynar", "appellation": " ", "rarity": 6, "profession": "WARRIOR", "subProfessionId": "librator", "position": "MELEE", "tagList": ["DPS", "Nuker"], "nationId": "kazimierz", "isNotObtainable": false, "groupId": null, "teamId": null, "professionName": "Guard", "subProfessionName": "Liberator", "nationName": "Kazimierz", "groupName": null, "teamName": null, "obtainChannel": "headhunting", "artists": ["竜崎いち"], "portrait": "/portraits/char_4064_mlynar_2.png", "gender": "Male", "race": "Kuranta", "placeOfBirth": "Kazimierz", "stats": {"hp": 3906, "atk": 355, "def": 502, "res": 15.0, "cost": 12, "block": 3}, "hasOffensiveRecovery": false, "hasDefensiveRecovery": false, "allSkillsManual": true, "voiceActors": ["Yuhang Wang", "Anthony Howell", "Rikiya Koyama", "Choi Hyun-su"], "phaseMaxLevels": [50, 80, 90], "skillCount": 3, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_mlynar", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_mlynar", "typeName1": "LIB", "typeName2": "X", "type": "ADVANCED"}], "dateOfBirth": "Dec 3"},
    {"id": "char_293_thorns", "name": "Thorns", "appellation": " ", "rarity": 6, "profession": "WARRIOR", "subProfessionId": "lord", "position": "MELEE", "tagList": ["DPS", "Defense"], "nationId": "iberia", "isNotObtainable": false, "groupId": null, "teamId": null, "professionName": "Guard", "subProfessionName": "Lord", "nationName": "Iberia", "groupName": null, "teamName": null, "obtainChannel": "headhunting", "artists": ["Studio Montagne", "幻象黑兔"], "portrait": "/portraits/char_293_thorns_2.png", "gender": "Male", "race": "Ægir", "placeOfBirth": "Iberia", "stats": {"hp": 2612, "atk": 711, "def": 402, "res": 10.0, "cost": 20, "block": 2}, "hasOffensiveRecovery": true, "hasDefensiveRecovery": false, "allSkillsManual": true, "voiceActors": ["Ethan", "Javier Bañas", "Kaito Ishikawa", "Hong Bum-ki"], "phaseMaxLevels": [50, 80, 90], "skillCount": 3, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_thorns", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_thorns", "typeName1": "LOR", "typeName2": "X", "type": "ADVANCED"}, {"uniEquipId": "uniequip_003_thorns", "typeName1": "LOR", "typeName2": "D", "type": "ADVANCED"}], "dateOfBirth": "Mar 17"},
    {"id": "char_350_surtr", "name": "Surtr", "appellation": " ", "rarity": 6, "profession": "WARRIOR", "subProfessionId": "artsfghter", "position": "MELEE", "tagList": ["DPS"], "nationId": "rhodes", "isNotObtainable": false, "groupId": null, "teamId": null, "professionName": "Guard", "subProfessionName": "Arts Fighter", "nationName": "Rhodes Island", "groupName": null, "teamName": null, "obtainChannel": "headhunting", "artists": ["Ask"], "portrait": "/portraits/char_350_surtr_2.png", "gender": "Female", "race": "Sarkaz", "placeOfBirth": "Unknown", "stats": {"hp": 2916, "atk": 672, "def": 414, "res": 15.0, "cost": 21, "block": 1}, "hasOffensiveRecovery": true, "hasDefensiveRecovery": false, "allSkillsManual": false, "voiceActors": ["Yi Zhu", "Kira Buckland", "Yui Horie", "Seo Yu-ri"], "phaseMaxLevels": [50, 80, 90], "skillCount": 3, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_surtr", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_surtr", "typeName1": "AFT", "typeName2": "X", "type": "ADVANCED"}, {"uniEquipId": "uniequip_003_surtr", "typeName1": "AFT", "typeName2": "Y", "type": "ADVANCED"}], "dateOfBirth": "Jan 22"},
    {"id": "char_4087_ines", "name": "Ines", "appellation": " ", "rarity": 6, "profession": "PIONEER", "subProfessionId": "agent", "position": "MELEE", "tagList": ["DP-Recovery", "Fast-Redeploy"], "nationId": "", "isNotObtainable": false, "groupId": "babel", "teamId": null, "professionName": "Vanguard", "subProfessionName": "Agent", "nationName": null, "groupName": "Babel", "teamName": null, "obtainChannel": "headhunting", "artists": ["板板"], "portrait": "/portraits/char_4087_ines_2.png", "gender": "Female", "race": "Undisclosed", "placeOfBirth": "Kazdel", "stats": {"hp": 2121, "atk": 589, "def": 281, "res": 0.0, "cost": 11, "block": 1}, "hasOffensiveRecovery": true, "hasDefensiveRecovery": false, "allSkillsManual": false, "voiceActors": ["Ruoyu Zhang", "Erica Lindbeck", "Ayumi Tsunematsu", "Shin Na-ri"], "phaseMaxLevels": [50, 80, 90], "skillCount": 3, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_ines", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_ines", "typeName1": "AGE", "typeName2": "Y", "type": "ADVANCED"}], "dateOfBirth": "Feb 19"},
    {"id": "char_003_kalts", "name": "Kal'tsit", "appellation": " ", "rarity": 6, "profession": "MEDIC", "subProfessionId": "physician", "position": "RANGED", "tagList": ["Summon", "Healing"], "nationId": "rhodes", "isNotObtainable": false, "groupId": null, "teamId": null, "professionName": "Medic", "subProfessionName": "Medic", "nationName": "Rhodes Island", "groupName": null, "teamName": null, "obtainChannel": "headhunting", "artists": ["红色彗星", "唯@W", "伍秋秋秋秋"], "portrait": "/portraits/char_003_kalts_2.png", "gender": "Female", "race": "Feline", "placeOfBirth": "Rhodes Island", "stats": {"hp": 1633, "atk": 490, "def": 215, "res": 0.0, "cost": 20, "block": 1}, "hasOffensiveRecovery": false, "hasDefensiveRecovery": false, "allSkillsManual": true, "voiceActors": ["Xue Liu", "Sura Siu", "Yoko Hikasa", "Han Chae-eon"], "phaseMaxLevels": [50, 80, 90], "skillCount": 3, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_kalts", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_kalts", "typeName1": "PHY", "typeName2": "X", "type": "ADVANCED"}, {"uniEquipId": "uniequip_003_kalts", "typeName1": "PHY", "typeName2": "Y", "type": "ADVANCED"}, {"uniEquipId": "uniequip_004_kalts", "typeName1": "ISW", "typeName2": "A", "type": "ADVANCED"}], "dateOfBirth": "Undisclosed"},
    {"id": "char_2015_dusk", "name": "Dusk", "appellation": " ", "rarity": 6, "profession": "CASTER", "subProfessionId": "splashcaster", "position": "RANGED", "tagList": ["AoE", "DPS", "Crowd-Control"], "nationId": "yan", "isNotObtainable": false, "groupId": "sui", "teamId": null, "professionName": "Caster", "subProfessionName": "Splash Caster", "nationName": "Yan", "groupName": "Yan-Sui", "teamName": null, "obtainChannel": "headhunting", "artists": ["幻象黑兔", "Studio Montagne"], "portrait": "/portraits/char_2015_dusk_2.png", "gender": "Female", "race": "Undisclosed", "placeOfBirth": "Yan", "stats": {"hp": 1801, "atk": 918, "def": 127, "res": 20.0, "cost": 34, "block": 1}, "hasOffensiveRecovery": false, "hasDefensiveRecovery": false, "allSkillsManual": false, "voiceActors": ["Blank", "Aileen Mythen", "yukana", "Bae Jeong-mi"], "phaseMaxLevels": [50, 80, 90], "skillCount": 3, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_dusk", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_dusk", "typeName1": "SPC", "typeName2": "X", "type": "ADVANCED"}, {"uniEquipId": "uniequip_003_dusk", "typeName1": "SPC", "typeName2": "Y", "type": "ADVANCED"}, {"uniEquipId": "uniequip_004_dusk", "typeName1": "ISW", "typeName2": "A", "type": "ADVANCED"}], "dateOfBirth": "November 11"},
];

const ROSTER = [entry("char_4064_mlynar", 2, 90, 3, 3), entry("char_293_thorns", 2, 90, 3, 2), entry("char_350_surtr", 2, 88, 2, 3), entry("char_4087_ines", 2, 84, 1, 1), entry("char_003_kalts", 1, 70, 0, 0), entry("char_2015_dusk", 2, 90, 3, 3)];

export const LoadingSkinsIndex = () => <ProfileStatsTab nonDefaultSkinCount={63} operatorsIndex={OPERATORS} roster={ROSTER} server="en" uid="1000123456" />;
