import { TopOperatorsCard } from "frontend";

/** One row of the imported roster table. */
const entry = (operatorId: string, elite: number, level: number, masteries: number[], modules: { id: string; level: number }[], potential: number, favorPoint: number, skinId: string | null = null) => ({
    user_id: "1000123456",
    operator_id: operatorId,
    elite,
    level,
    exp: 0,
    potential,
    skill_level: 7,
    favor_point: favorPoint,
    skin_id: skinId,
    default_skill: 0,
    voice_lan: "JP",
    current_equip: modules[0]?.id ?? null,
    current_tmpl: null,
    obtained_at: 1_690_000_000,
    masteries: masteries.map((mastery, index) => ({ index, mastery })),
    modules: modules.map((m) => ({ ...m, locked: false })),
});

/** Real `/api/operators/index` entries (fetched 2026-10-08), the shape `operatorsIndex` takes. */
const OPERATORS = [
    {"id": "char_4064_mlynar", "name": "Młynar", "appellation": " ", "rarity": 6, "profession": "WARRIOR", "subProfessionId": "librator", "position": "MELEE", "tagList": ["DPS", "Nuker"], "nationId": "kazimierz", "isNotObtainable": false, "groupId": null, "teamId": null, "professionName": "Guard", "subProfessionName": "Liberator", "nationName": "Kazimierz", "groupName": null, "teamName": null, "obtainChannel": "headhunting", "artists": ["竜崎いち"], "portrait": "/portraits/char_4064_mlynar_2.png", "gender": "Male", "race": "Kuranta", "placeOfBirth": "Kazimierz", "stats": {"hp": 3906, "atk": 355, "def": 502, "res": 15.0, "cost": 12, "block": 3}, "hasOffensiveRecovery": false, "hasDefensiveRecovery": false, "allSkillsManual": true, "voiceActors": ["Yuhang Wang", "Anthony Howell", "Rikiya Koyama", "Choi Hyun-su"], "phaseMaxLevels": [50, 80, 90], "skillCount": 3, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_mlynar", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_mlynar", "typeName1": "LIB", "typeName2": "X", "type": "ADVANCED"}], "dateOfBirth": "Dec 3"},
    {"id": "char_1028_texas2", "name": "Texas the Omertosa", "appellation": " ", "rarity": 6, "profession": "SPECIAL", "subProfessionId": "executor", "position": "MELEE", "tagList": ["Fast-Redeploy", "DPS"], "nationId": "lungmen", "isNotObtainable": false, "groupId": "penguin", "teamId": null, "professionName": "Specialist", "subProfessionName": "Executor", "nationName": "Yan-Lungmen", "groupName": "Penguin Logistics", "teamName": null, "obtainChannel": "headhunting", "artists": ["Studio Montagne", "幻象黑兔"], "portrait": "/portraits/char_1028_texas2_2.png", "gender": "Female", "race": "Lupo", "placeOfBirth": "Columbia", "stats": {"hp": 1598, "atk": 569, "def": 320, "res": 0.0, "cost": 10, "block": 1}, "hasOffensiveRecovery": false, "hasDefensiveRecovery": false, "allSkillsManual": false, "voiceActors": ["Menglu Yang", "Jessica Preddy", "Ilaria Silvestri", "Azusa Tadokoro", "Kim Chae-ha"], "phaseMaxLevels": [50, 80, 90], "skillCount": 3, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_texas2", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_texas2", "typeName1": "EXE", "typeName2": "Y", "type": "ADVANCED"}], "dateOfBirth": "Jun 1"},
    {"id": "char_2015_dusk", "name": "Dusk", "appellation": " ", "rarity": 6, "profession": "CASTER", "subProfessionId": "splashcaster", "position": "RANGED", "tagList": ["AoE", "DPS", "Crowd-Control"], "nationId": "yan", "isNotObtainable": false, "groupId": "sui", "teamId": null, "professionName": "Caster", "subProfessionName": "Splash Caster", "nationName": "Yan", "groupName": "Yan-Sui", "teamName": null, "obtainChannel": "headhunting", "artists": ["幻象黑兔", "Studio Montagne"], "portrait": "/portraits/char_2015_dusk_2.png", "gender": "Female", "race": "Undisclosed", "placeOfBirth": "Yan", "stats": {"hp": 1801, "atk": 918, "def": 127, "res": 20.0, "cost": 34, "block": 1}, "hasOffensiveRecovery": false, "hasDefensiveRecovery": false, "allSkillsManual": false, "voiceActors": ["Blank", "Aileen Mythen", "yukana", "Bae Jeong-mi"], "phaseMaxLevels": [50, 80, 90], "skillCount": 3, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_dusk", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_dusk", "typeName1": "SPC", "typeName2": "X", "type": "ADVANCED"}, {"uniEquipId": "uniequip_003_dusk", "typeName1": "SPC", "typeName2": "Y", "type": "ADVANCED"}, {"uniEquipId": "uniequip_004_dusk", "typeName1": "ISW", "typeName2": "A", "type": "ADVANCED"}], "dateOfBirth": "November 11"},
    {"id": "char_293_thorns", "name": "Thorns", "appellation": " ", "rarity": 6, "profession": "WARRIOR", "subProfessionId": "lord", "position": "MELEE", "tagList": ["DPS", "Defense"], "nationId": "iberia", "isNotObtainable": false, "groupId": null, "teamId": null, "professionName": "Guard", "subProfessionName": "Lord", "nationName": "Iberia", "groupName": null, "teamName": null, "obtainChannel": "headhunting", "artists": ["Studio Montagne", "幻象黑兔"], "portrait": "/portraits/char_293_thorns_2.png", "gender": "Male", "race": "Ægir", "placeOfBirth": "Iberia", "stats": {"hp": 2612, "atk": 711, "def": 402, "res": 10.0, "cost": 20, "block": 2}, "hasOffensiveRecovery": true, "hasDefensiveRecovery": false, "allSkillsManual": true, "voiceActors": ["Ethan", "Javier Bañas", "Kaito Ishikawa", "Hong Bum-ki"], "phaseMaxLevels": [50, 80, 90], "skillCount": 3, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_thorns", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_thorns", "typeName1": "LOR", "typeName2": "X", "type": "ADVANCED"}, {"uniEquipId": "uniequip_003_thorns", "typeName1": "LOR", "typeName2": "D", "type": "ADVANCED"}], "dateOfBirth": "Mar 17"},
    {"id": "char_350_surtr", "name": "Surtr", "appellation": " ", "rarity": 6, "profession": "WARRIOR", "subProfessionId": "artsfghter", "position": "MELEE", "tagList": ["DPS"], "nationId": "rhodes", "isNotObtainable": false, "groupId": null, "teamId": null, "professionName": "Guard", "subProfessionName": "Arts Fighter", "nationName": "Rhodes Island", "groupName": null, "teamName": null, "obtainChannel": "headhunting", "artists": ["Ask"], "portrait": "/portraits/char_350_surtr_2.png", "gender": "Female", "race": "Sarkaz", "placeOfBirth": "Unknown", "stats": {"hp": 2916, "atk": 672, "def": 414, "res": 15.0, "cost": 21, "block": 1}, "hasOffensiveRecovery": true, "hasDefensiveRecovery": false, "allSkillsManual": false, "voiceActors": ["Yi Zhu", "Kira Buckland", "Yui Horie", "Seo Yu-ri"], "phaseMaxLevels": [50, 80, 90], "skillCount": 3, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_surtr", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_surtr", "typeName1": "AFT", "typeName2": "X", "type": "ADVANCED"}, {"uniEquipId": "uniequip_003_surtr", "typeName1": "AFT", "typeName2": "Y", "type": "ADVANCED"}], "dateOfBirth": "Jan 22"},
    {"id": "char_4087_ines", "name": "Ines", "appellation": " ", "rarity": 6, "profession": "PIONEER", "subProfessionId": "agent", "position": "MELEE", "tagList": ["DP-Recovery", "Fast-Redeploy"], "nationId": "", "isNotObtainable": false, "groupId": "babel", "teamId": null, "professionName": "Vanguard", "subProfessionName": "Agent", "nationName": null, "groupName": "Babel", "teamName": null, "obtainChannel": "headhunting", "artists": ["板板"], "portrait": "/portraits/char_4087_ines_2.png", "gender": "Female", "race": "Undisclosed", "placeOfBirth": "Kazdel", "stats": {"hp": 2121, "atk": 589, "def": 281, "res": 0.0, "cost": 11, "block": 1}, "hasOffensiveRecovery": true, "hasDefensiveRecovery": false, "allSkillsManual": false, "voiceActors": ["Ruoyu Zhang", "Erica Lindbeck", "Ayumi Tsunematsu", "Shin Na-ri"], "phaseMaxLevels": [50, 80, 90], "skillCount": 3, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_ines", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_ines", "typeName1": "AGE", "typeName2": "Y", "type": "ADVANCED"}], "dateOfBirth": "Feb 19"},
    {"id": "char_003_kalts", "name": "Kal'tsit", "appellation": " ", "rarity": 6, "profession": "MEDIC", "subProfessionId": "physician", "position": "RANGED", "tagList": ["Summon", "Healing"], "nationId": "rhodes", "isNotObtainable": false, "groupId": null, "teamId": null, "professionName": "Medic", "subProfessionName": "Medic", "nationName": "Rhodes Island", "groupName": null, "teamName": null, "obtainChannel": "headhunting", "artists": ["红色彗星", "唯@W", "伍秋秋秋秋"], "portrait": "/portraits/char_003_kalts_2.png", "gender": "Female", "race": "Feline", "placeOfBirth": "Rhodes Island", "stats": {"hp": 1633, "atk": 490, "def": 215, "res": 0.0, "cost": 20, "block": 1}, "hasOffensiveRecovery": false, "hasDefensiveRecovery": false, "allSkillsManual": true, "voiceActors": ["Xue Liu", "Sura Siu", "Yoko Hikasa", "Han Chae-eon"], "phaseMaxLevels": [50, 80, 90], "skillCount": 3, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_kalts", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_kalts", "typeName1": "PHY", "typeName2": "X", "type": "ADVANCED"}, {"uniEquipId": "uniequip_003_kalts", "typeName1": "PHY", "typeName2": "Y", "type": "ADVANCED"}, {"uniEquipId": "uniequip_004_kalts", "typeName1": "ISW", "typeName2": "A", "type": "ADVANCED"}], "dateOfBirth": "Undisclosed"},
    {"id": "char_1013_chen2", "name": "Ch'en the Holungday", "appellation": " ", "rarity": 6, "profession": "SNIPER", "subProfessionId": "reaperrange", "position": "RANGED", "tagList": ["DPS", "AoE"], "nationId": "rhodes", "isNotObtainable": false, "groupId": null, "teamId": null, "professionName": "Sniper", "subProfessionName": "Spreadshooter", "nationName": "Rhodes Island", "groupName": null, "teamName": null, "obtainChannel": "headhunting", "artists": ["唯@W", "三目YYB"], "portrait": "/portraits/char_1013_chen2_2.png", "gender": "Female", "race": "Lung", "placeOfBirth": "Lungmen", "stats": {"hp": 2501, "atk": 773, "def": 203, "res": 0.0, "cost": 32, "block": 1}, "hasOffensiveRecovery": true, "hasDefensiveRecovery": false, "allSkillsManual": false, "voiceActors": ["Jen Zhang", "Sunny So", "Amy Lennox", "Shizuka Ishigami", "Chung Yu-joung"], "phaseMaxLevels": [50, 80, 90], "skillCount": 3, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_chen2", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_chen2", "typeName1": "RPR", "typeName2": "X", "type": "ADVANCED"}, {"uniEquipId": "uniequip_003_chen2", "typeName1": "RPR", "typeName2": "Y", "type": "ADVANCED"}], "dateOfBirth": "Jul 7"},
    {"id": "char_263_skadi", "name": "Skadi", "appellation": " ", "rarity": 6, "profession": "WARRIOR", "subProfessionId": "fearless", "position": "MELEE", "tagList": ["DPS", "Survival"], "nationId": "egir", "isNotObtainable": false, "groupId": "abyssal", "teamId": null, "professionName": "Guard", "subProfessionName": "Dreadnought", "nationName": "Ægir", "groupName": "Abyssal Hunters", "teamName": null, "obtainChannel": "headhunting", "artists": ["alchemaniac"], "portrait": "/portraits/char_263_skadi_2.png", "gender": "Female", "race": "Unknown", "placeOfBirth": "Ægir", "stats": {"hp": 3866, "atk": 1015, "def": 263, "res": 0.0, "cost": 19, "block": 1}, "hasOffensiveRecovery": false, "hasDefensiveRecovery": false, "allSkillsManual": false, "voiceActors": ["Kiiki", "Cristina Vee", "Rina Sato", "Kim Na-yul"], "phaseMaxLevels": [50, 80, 90], "skillCount": 3, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_skadi", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_skadi", "typeName1": "DRE", "typeName2": "Y", "type": "ADVANCED"}, {"uniEquipId": "uniequip_003_skadi", "typeName1": "DRE", "typeName2": "X", "type": "ADVANCED"}], "dateOfBirth": "Mar. 7"},
    {"id": "char_102_texas", "name": "Texas", "appellation": " ", "rarity": 5, "profession": "PIONEER", "subProfessionId": "pioneer", "position": "MELEE", "tagList": ["DP-Recovery", "Crowd-Control"], "nationId": "lungmen", "isNotObtainable": false, "groupId": "penguin", "teamId": null, "professionName": "Vanguard", "subProfessionName": "Pioneer", "nationName": "Yan-Lungmen", "groupName": "Penguin Logistics", "teamName": null, "obtainChannel": "headhunting", "artists": ["幻象黑兔"], "portrait": "/portraits/char_102_texas_2.png", "gender": "Female", "race": "Lupo", "placeOfBirth": "Columbia", "stats": {"hp": 1950, "atk": 500, "def": 343, "res": 0.0, "cost": 13, "block": 2}, "hasOffensiveRecovery": false, "hasDefensiveRecovery": false, "allSkillsManual": false, "voiceActors": ["Menglu Yang", "Jessica Preddy", "Ilaria Silvestri", "Azusa Tadokoro", "Kim Chae-ha"], "phaseMaxLevels": [50, 70, 80], "skillCount": 2, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_texas", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_texas", "typeName1": "SOL", "typeName2": "Y", "type": "ADVANCED"}], "dateOfBirth": "Jun. 1"},
    {"id": "char_017_huang", "name": "Blaze", "appellation": " ", "rarity": 6, "profession": "WARRIOR", "subProfessionId": "centurion", "position": "MELEE", "tagList": ["DPS", "Survival"], "nationId": "rhodes", "isNotObtainable": false, "groupId": "elite", "teamId": null, "professionName": "Guard", "subProfessionName": "Centurion", "nationName": "Rhodes Island", "groupName": "Rhodes Island-Elite Operator", "teamName": null, "obtainChannel": "headhunting", "artists": ["唯@W", "Mag42"], "portrait": "/portraits/char_017_huang_2.png", "gender": "Female", "race": "Feline", "placeOfBirth": "Victoria", "stats": {"hp": 2821, "atk": 765, "def": 370, "res": 0.0, "cost": 24, "block": 3}, "hasOffensiveRecovery": true, "hasDefensiveRecovery": false, "allSkillsManual": false, "voiceActors": ["Atom", "Cristina Vee", "Mai Nakahara", "Kim Yeon-woo"], "phaseMaxLevels": [50, 80, 90], "skillCount": 3, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_huang", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_huang", "typeName1": "CEN", "typeName2": "X", "type": "ADVANCED"}, {"uniEquipId": "uniequip_003_huang", "typeName1": "CEN", "typeName2": "Y", "type": "ADVANCED"}], "dateOfBirth": "Undisclosed"},
    {"id": "char_4045_heidi", "name": "Heidi", "appellation": " ", "rarity": 5, "profession": "SUPPORT", "subProfessionId": "bard", "position": "RANGED", "tagList": ["Support", "Healing"], "nationId": "victoria", "isNotObtainable": false, "groupId": null, "teamId": null, "professionName": "Supporter", "subProfessionName": "Bard", "nationName": "Victoria", "groupName": null, "teamName": null, "obtainChannel": "event", "artists": ["熊太"], "portrait": "/portraits/char_4045_heidi_2.png", "gender": "Female", "race": "Feline", "placeOfBirth": "Victoria", "stats": {"hp": 1260, "atk": 320, "def": 268, "res": 0.0, "cost": 9, "block": 1}, "hasOffensiveRecovery": false, "hasDefensiveRecovery": false, "allSkillsManual": true, "voiceActors": ["Ying Xie", "Sophie Shad", "Akira Sekine", "Sung Ye-won"], "phaseMaxLevels": [50, 70, 80], "skillCount": 2, "potentialRankCount": 5, "modules": [{"uniEquipId": "uniequip_001_heidi", "typeName1": "ORIGINAL", "typeName2": null, "type": "INITIAL"}, {"uniEquipId": "uniequip_002_heidi", "typeName1": "BAR", "typeName2": "X", "type": "ADVANCED"}], "dateOfBirth": "Mar 26"},
];

const ROSTER = [
    entry("char_4064_mlynar", 2, 90, [3, 3, 3], [{ id: "uniequip_002_mlynar", level: 3 }], 5, 25_570, "char_4064_mlynar@epoque#28"),
    entry("char_1028_texas2", 2, 90, [3, 3, 3], [{ id: "uniequip_002_texas2", level: 3 }], 5, 25_570, "char_1028_texas2@iteration#1"),
    entry("char_2015_dusk", 2, 90, [3, 3, 2], [{ id: "uniequip_002_dusk", level: 3 }], 4, 25_570),
    entry("char_293_thorns", 2, 90, [3, 3, 3], [{ id: "uniequip_002_thorns", level: 2 }], 3, 24_100),
    entry("char_350_surtr", 2, 88, [3, 2, 3], [{ id: "uniequip_002_surtr", level: 3 }], 2, 22_800),
    entry("char_4087_ines", 2, 90, [3, 3, 1], [{ id: "uniequip_002_ines", level: 2 }], 1, 19_400),
    entry("char_003_kalts", 2, 80, [3, 1, 0], [{ id: "uniequip_002_kalts", level: 1 }], 2, 17_200, "char_003_kalts@boc#6"),
    entry("char_1013_chen2", 2, 76, [3, 0, 0], [{ id: "uniequip_002_chen2", level: 1 }], 1, 12_600),
    entry("char_263_skadi", 1, 62, [0, 0, 0], [], 1, 8_400),
    entry("char_102_texas", 2, 80, [3, 3, 3], [{ id: "uniequip_002_texas", level: 3 }], 5, 25_570, "char_102_texas@winter#1"),
    entry("char_017_huang", 2, 70, [2, 1, 0], [{ id: "uniequip_002_huang", level: 1 }], 3, 14_300),
    entry("char_4045_heidi", 1, 55, [0, 0, 0], [], 1, 6_100),
];

const EARLY_ROSTER = [entry("char_102_texas", 1, 55, [0, 0, 0], [], 2, 7_400), entry("char_017_huang", 1, 48, [0, 0, 0], [], 1, 5_200), entry("char_4045_heidi", 0, 42, [0, 0, 0], [], 1, 2_900), entry("char_263_skadi", 0, 36, [0, 0, 0], [], 1, 1_800)];

const MAXED_ROSTER = ROSTER.slice(0, 4).map((e) => ({ ...e, elite: 2, level: 90, potential: 5, favor_point: 25_570, masteries: [0, 1, 2].map((index) => ({ index, mastery: 3 })), modules: OPERATORS.find((o) => o.id === e.operator_id)!.modules.filter((m) => m.type === "ADVANCED").map((m) => ({ id: m.uniEquipId, level: 3, locked: false })) }));

export const DeepRoster = () => (
    <div className="w-full max-w-3xl">
        <TopOperatorsCard operatorsIndex={OPERATORS} roster={ROSTER} />
    </div>
);

export const EarlyAccount = () => (
    <div className="w-full max-w-3xl">
        <TopOperatorsCard operatorsIndex={OPERATORS} roster={EARLY_ROSTER} />
    </div>
);

export const FullyBuilt = () => (
    <div className="w-full max-w-3xl">
        <TopOperatorsCard operatorsIndex={OPERATORS} roster={MAXED_ROSTER} />
    </div>
);
