import Head from "next/head";
import { BentoGrid, MainContent } from "~/components/home";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta content="Generated by create-t3-app" name="description" />
                <link href="/favicon.ico" rel="icon" />
            </Head>
            <MainContent />
            <BentoGrid />
        </>
    );
}
