/// Unity TextureFormat enumeration
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u32)]
pub enum TextureFormat {
    /// Alpha8 variant
    Alpha8 = 1,
    /// ARGB4444 variant
    ARGB4444 = 2,
    /// RGB24 variant
    RGB24 = 3,
    /// RGBA32 variant
    RGBA32 = 4,
    /// ARGB32 variant
    ARGB32 = 5,
    /// ARGBFloat variant
    ARGBFloat = 6,
    /// RGB565 variant
    RGB565 = 7,
    /// BGR24 variant
    BGR24 = 8,
    /// R16 variant
    R16 = 9,
    /// DXT1 variant
    DXT1 = 10,
    /// DXT3 variant
    DXT3 = 11,
    /// DXT5 variant
    DXT5 = 12,
    /// RGBA4444 variant
    RGBA4444 = 13,
    /// BGRA32 variant
    BGRA32 = 14,
    /// RHalf variant
    RHalf = 15,
    /// RGHalf variant
    RGHalf = 16,
    /// RGBAHalf variant
    RGBAHalf = 17,
    /// RFloat variant
    RFloat = 18,
    /// RGFloat variant
    RGFloat = 19,
    /// RGBAFloat variant
    RGBAFloat = 20,
    /// YUY2 variant
    YUY2 = 21,
    /// RGB9e5Float variant
    RGB9e5Float = 22,
    /// RGBFloat variant
    RGBFloat = 23,
    /// BC6H variant
    BC6H = 24,
    /// BC7 variant
    BC7 = 25,
    /// BC4 variant
    BC4 = 26,
    /// BC5 variant
    BC5 = 27,
    /// DXT1Crunched variant
    DXT1Crunched = 28,
    /// DXT5Crunched variant
    DXT5Crunched = 29,
    /// PVRTC_RGB2 variant
    PVRTC_RGB2 = 30,
    /// PVRTC_RGBA2 variant
    PVRTC_RGBA2 = 31,
    /// PVRTC_RGB4 variant
    PVRTC_RGB4 = 32,
    /// PVRTC_RGBA4 variant
    PVRTC_RGBA4 = 33,
    /// ETC_RGB4 variant
    ETC_RGB4 = 34,
    /// ATC_RGB4 variant
    ATC_RGB4 = 35,
    /// ATC_RGBA8 variant
    ATC_RGBA8 = 36,
    /// EAC_R variant
    EAC_R = 41,
    /// EAC_R_SIGNED variant
    EAC_R_SIGNED = 42,
    /// EAC_RG variant
    EAC_RG = 43,
    /// EAC_RG_SIGNED variant
    EAC_RG_SIGNED = 44,
    /// ETC2_RGB variant
    ETC2_RGB = 45,
    /// ETC2_RGBA1 variant
    ETC2_RGBA1 = 46,
    /// ETC2_RGBA8 variant
    ETC2_RGBA8 = 47,
    /// ASTC_RGB_4x4 variant
    ASTC_RGB_4x4 = 48,
    /// ASTC_RGB_5x5 variant
    ASTC_RGB_5x5 = 49,
    /// ASTC_RGB_6x6 variant
    ASTC_RGB_6x6 = 50,
    /// ASTC_RGB_8x8 variant
    ASTC_RGB_8x8 = 51,
    /// ASTC_RGB_10x10 variant
    ASTC_RGB_10x10 = 52,
    /// ASTC_RGB_12x12 variant
    ASTC_RGB_12x12 = 53,
    /// ASTC_RGBA_4x4 variant
    ASTC_RGBA_4x4 = 54,
    /// ASTC_RGBA_5x5 variant
    ASTC_RGBA_5x5 = 55,
    /// ASTC_RGBA_6x6 variant
    ASTC_RGBA_6x6 = 56,
    /// ASTC_RGBA_8x8 variant
    ASTC_RGBA_8x8 = 57,
    /// ASTC_RGBA_10x10 variant
    ASTC_RGBA_10x10 = 58,
    /// ASTC_RGBA_12x12 variant
    ASTC_RGBA_12x12 = 59,
    /// ETC_RGB4_3DS variant
    ETC_RGB4_3DS = 60,
    /// ETC_RGBA8_3DS variant
    ETC_RGBA8_3DS = 61,
    /// RG16 variant
    RG16 = 62,
    /// R8 variant
    R8 = 63,
    /// ETC_RGB4Crunched variant
    ETC_RGB4Crunched = 64,
    /// ETC2_RGBA8Crunched variant
    ETC2_RGBA8Crunched = 65,
    /// ASTC_HDR_4x4 variant
    ASTC_HDR_4x4 = 66,
    /// ASTC_HDR_5x5 variant
    ASTC_HDR_5x5 = 67,
    /// ASTC_HDR_6x6 variant
    ASTC_HDR_6x6 = 68,
    /// ASTC_HDR_8x8 variant
    ASTC_HDR_8x8 = 69,
    /// ASTC_HDR_10x10 variant
    ASTC_HDR_10x10 = 70,
    /// ASTC_HDR_12x12 variant
    ASTC_HDR_12x12 = 71,
    /// RG32 variant
    RG32 = 72,
    /// RGB48 variant
    RGB48 = 73,
    /// RGBA64 variant
    RGBA64 = 74,
    /// R8_SIGNED variant
    R8_SIGNED = 75,
    /// RG16_SIGNED variant
    RG16_SIGNED = 76,
    /// RGB24_SIGNED variant
    RGB24_SIGNED = 77,
    /// RGBA32_SIGNED variant
    RGBA32_SIGNED = 78,
    /// R16_SIGNED variant
    R16_SIGNED = 79,
    /// RG32_SIGNED variant
    RG32_SIGNED = 80,
    /// RGB48_SIGNED variant
    RGB48_SIGNED = 81,
    /// RGBA64_SIGNED variant
    RGBA64_SIGNED = 82,
    /// Unknown or unsupported variant
    Unknown(u32),
}

impl TextureFormat {
    /// Creates a TextureFormat from a u32 value
    pub fn from_u32(value: u32) -> Self {
        match value {
            1 => TextureFormat::Alpha8,
            2 => TextureFormat::ARGB4444,
            3 => TextureFormat::RGB24,
            4 => TextureFormat::RGBA32,
            5 => TextureFormat::ARGB32,
            6 => TextureFormat::ARGBFloat,
            7 => TextureFormat::RGB565,
            8 => TextureFormat::BGR24,
            9 => TextureFormat::R16,
            10 => TextureFormat::DXT1,
            11 => TextureFormat::DXT3,
            12 => TextureFormat::DXT5,
            13 => TextureFormat::RGBA4444,
            14 => TextureFormat::BGRA32,
            15 => TextureFormat::RHalf,
            16 => TextureFormat::RGHalf,
            17 => TextureFormat::RGBAHalf,
            18 => TextureFormat::RFloat,
            19 => TextureFormat::RGFloat,
            20 => TextureFormat::RGBAFloat,
            21 => TextureFormat::YUY2,
            22 => TextureFormat::RGB9e5Float,
            23 => TextureFormat::RGBFloat,
            24 => TextureFormat::BC6H,
            25 => TextureFormat::BC7,
            26 => TextureFormat::BC4,
            27 => TextureFormat::BC5,
            28 => TextureFormat::DXT1Crunched,
            29 => TextureFormat::DXT5Crunched,
            30 => TextureFormat::PVRTC_RGB2,
            31 => TextureFormat::PVRTC_RGBA2,
            32 => TextureFormat::PVRTC_RGB4,
            33 => TextureFormat::PVRTC_RGBA4,
            34 => TextureFormat::ETC_RGB4,
            35 => TextureFormat::ATC_RGB4,
            36 => TextureFormat::ATC_RGBA8,
            41 => TextureFormat::EAC_R,
            42 => TextureFormat::EAC_R_SIGNED,
            43 => TextureFormat::EAC_RG,
            44 => TextureFormat::EAC_RG_SIGNED,
            45 => TextureFormat::ETC2_RGB,
            46 => TextureFormat::ETC2_RGBA1,
            47 => TextureFormat::ETC2_RGBA8,
            48 => TextureFormat::ASTC_RGB_4x4,
            49 => TextureFormat::ASTC_RGB_5x5,
            50 => TextureFormat::ASTC_RGB_6x6,
            51 => TextureFormat::ASTC_RGB_8x8,
            52 => TextureFormat::ASTC_RGB_10x10,
            53 => TextureFormat::ASTC_RGB_12x12,
            54 => TextureFormat::ASTC_RGBA_4x4,
            55 => TextureFormat::ASTC_RGBA_5x5,
            56 => TextureFormat::ASTC_RGBA_6x6,
            57 => TextureFormat::ASTC_RGBA_8x8,
            58 => TextureFormat::ASTC_RGBA_10x10,
            59 => TextureFormat::ASTC_RGBA_12x12,
            60 => TextureFormat::ETC_RGB4_3DS,
            61 => TextureFormat::ETC_RGBA8_3DS,
            62 => TextureFormat::RG16,
            63 => TextureFormat::R8,
            64 => TextureFormat::ETC_RGB4Crunched,
            65 => TextureFormat::ETC2_RGBA8Crunched,
            66 => TextureFormat::ASTC_HDR_4x4,
            67 => TextureFormat::ASTC_HDR_5x5,
            68 => TextureFormat::ASTC_HDR_6x6,
            69 => TextureFormat::ASTC_HDR_8x8,
            70 => TextureFormat::ASTC_HDR_10x10,
            71 => TextureFormat::ASTC_HDR_12x12,
            72 => TextureFormat::RG32,
            73 => TextureFormat::RGB48,
            74 => TextureFormat::RGBA64,
            75 => TextureFormat::R8_SIGNED,
            76 => TextureFormat::RG16_SIGNED,
            77 => TextureFormat::RGB24_SIGNED,
            78 => TextureFormat::RGBA32_SIGNED,
            79 => TextureFormat::R16_SIGNED,
            80 => TextureFormat::RG32_SIGNED,
            81 => TextureFormat::RGB48_SIGNED,
            82 => TextureFormat::RGBA64_SIGNED,
            _ => TextureFormat::Unknown(value),
        }
    }

    /// Converts the TextureFormat to its u32 representation
    pub fn to_u32(&self) -> u32 {
        match self {
            TextureFormat::Alpha8 => 1,
            TextureFormat::ARGB4444 => 2,
            TextureFormat::RGB24 => 3,
            TextureFormat::RGBA32 => 4,
            TextureFormat::ARGB32 => 5,
            TextureFormat::ARGBFloat => 6,
            TextureFormat::RGB565 => 7,
            TextureFormat::BGR24 => 8,
            TextureFormat::R16 => 9,
            TextureFormat::DXT1 => 10,
            TextureFormat::DXT3 => 11,
            TextureFormat::DXT5 => 12,
            TextureFormat::RGBA4444 => 13,
            TextureFormat::BGRA32 => 14,
            TextureFormat::RHalf => 15,
            TextureFormat::RGHalf => 16,
            TextureFormat::RGBAHalf => 17,
            TextureFormat::RFloat => 18,
            TextureFormat::RGFloat => 19,
            TextureFormat::RGBAFloat => 20,
            TextureFormat::YUY2 => 21,
            TextureFormat::RGB9e5Float => 22,
            TextureFormat::RGBFloat => 23,
            TextureFormat::BC6H => 24,
            TextureFormat::BC7 => 25,
            TextureFormat::BC4 => 26,
            TextureFormat::BC5 => 27,
            TextureFormat::DXT1Crunched => 28,
            TextureFormat::DXT5Crunched => 29,
            TextureFormat::PVRTC_RGB2 => 30,
            TextureFormat::PVRTC_RGBA2 => 31,
            TextureFormat::PVRTC_RGB4 => 32,
            TextureFormat::PVRTC_RGBA4 => 33,
            TextureFormat::ETC_RGB4 => 34,
            TextureFormat::ATC_RGB4 => 35,
            TextureFormat::ATC_RGBA8 => 36,
            TextureFormat::EAC_R => 41,
            TextureFormat::EAC_R_SIGNED => 42,
            TextureFormat::EAC_RG => 43,
            TextureFormat::EAC_RG_SIGNED => 44,
            TextureFormat::ETC2_RGB => 45,
            TextureFormat::ETC2_RGBA1 => 46,
            TextureFormat::ETC2_RGBA8 => 47,
            TextureFormat::ASTC_RGB_4x4 => 48,
            TextureFormat::ASTC_RGB_5x5 => 49,
            TextureFormat::ASTC_RGB_6x6 => 50,
            TextureFormat::ASTC_RGB_8x8 => 51,
            TextureFormat::ASTC_RGB_10x10 => 52,
            TextureFormat::ASTC_RGB_12x12 => 53,
            TextureFormat::ASTC_RGBA_4x4 => 54,
            TextureFormat::ASTC_RGBA_5x5 => 55,
            TextureFormat::ASTC_RGBA_6x6 => 56,
            TextureFormat::ASTC_RGBA_8x8 => 57,
            TextureFormat::ASTC_RGBA_10x10 => 58,
            TextureFormat::ASTC_RGBA_12x12 => 59,
            TextureFormat::ETC_RGB4_3DS => 60,
            TextureFormat::ETC_RGBA8_3DS => 61,
            TextureFormat::RG16 => 62,
            TextureFormat::R8 => 63,
            TextureFormat::ETC_RGB4Crunched => 64,
            TextureFormat::ETC2_RGBA8Crunched => 65,
            TextureFormat::ASTC_HDR_4x4 => 66,
            TextureFormat::ASTC_HDR_5x5 => 67,
            TextureFormat::ASTC_HDR_6x6 => 68,
            TextureFormat::ASTC_HDR_8x8 => 69,
            TextureFormat::ASTC_HDR_10x10 => 70,
            TextureFormat::ASTC_HDR_12x12 => 71,
            TextureFormat::RG32 => 72,
            TextureFormat::RGB48 => 73,
            TextureFormat::RGBA64 => 74,
            TextureFormat::R8_SIGNED => 75,
            TextureFormat::RG16_SIGNED => 76,
            TextureFormat::RGB24_SIGNED => 77,
            TextureFormat::RGBA32_SIGNED => 78,
            TextureFormat::R16_SIGNED => 79,
            TextureFormat::RG32_SIGNED => 80,
            TextureFormat::RGB48_SIGNED => 81,
            TextureFormat::RGBA64_SIGNED => 82,
            TextureFormat::Unknown(value) => *value,
        }
    }
}

impl From<u32> for TextureFormat {
    fn from(value: u32) -> Self {
        Self::from_u32(value)
    }
}

impl From<TextureFormat> for u32 {
    fn from(value: TextureFormat) -> Self {
        value.to_u32()
    }
}
