//! Auto-generated operator implementations
//!
//! Each operator is organized into alphabetical subfolders.

use super::operator_data::OperatorData;
use super::operator_unit::{DpsCalculator, OperatorParams};

/// Metadata about an operator's available configuration options
#[derive(Debug, Clone)]
pub struct OperatorMetadata {
    /// Available skill indices (e.g., [1, 2] or [1, 2, 3])
    pub available_skills: Vec<i32>,
    /// Available module indices (e.g., [1, 2] or [])
    pub available_modules: Vec<i32>,
    /// Default skill index for this operator
    pub default_skill_index: i32,
    /// Default potential for this operator
    pub default_potential: i32,
    /// Default module index for this operator
    pub default_module_index: i32,
}

pub mod a;
pub mod b;
pub mod c;
pub mod d;
pub mod e;
pub mod f;
pub mod g;
pub mod h;
pub mod i;
pub mod j;
pub mod k;
pub mod l;
pub mod m;
pub mod n;
pub mod o;
pub mod p;
pub mod q;
pub mod r;
pub mod s;
pub mod t;
pub mod u;
pub mod v;
pub mod w;
pub mod y;
pub mod z;

pub use a::*;
pub use b::*;
pub use c::*;
pub use d::*;
pub use e::*;
pub use f::*;
pub use g::*;
pub use h::*;
pub use i::*;
pub use j::*;
pub use k::*;
pub use l::*;
pub use m::*;
pub use n::*;
pub use o::*;
pub use p::*;
pub use q::*;
pub use r::*;
pub use s::*;
pub use t::*;
pub use u::*;
pub use v::*;
pub use w::*;
pub use y::*;
pub use z::*;

/// Creates an operator by name, returning a boxed DpsCalculator trait object
///
/// # Arguments
/// * `name` - The operator name (e.g., "Blaze", "ExusiaiAlter")
/// * `operator_data` - The operator's base data from JSON
/// * `params` - The operator configuration parameters
///
/// # Returns
/// Some(Box<dyn DpsCalculator>) if the operator is found, None otherwise
pub fn create_operator(
    name: &str,
    operator_data: OperatorData,
    params: OperatorParams,
) -> Option<Box<dyn DpsCalculator + Send + Sync>> {
    match name {
        "Aak" => Some(Box::new(Aak::new(operator_data, params))),
        "Absinthe" => Some(Box::new(Absinthe::new(operator_data, params))),
        "Aciddrop" => Some(Box::new(Aciddrop::new(operator_data, params))),
        "Adnachiel" => Some(Box::new(Adnachiel::new(operator_data, params))),
        "Amiya" => Some(Box::new(Amiya::new(operator_data, params))),
        "AmiyaGuard" => Some(Box::new(AmiyaGuard::new(operator_data, params))),
        "AmiyaMedic" => Some(Box::new(AmiyaMedic::new(operator_data, params))),
        "Andreana" => Some(Box::new(Andreana::new(operator_data, params))),
        "Angelina" => Some(Box::new(Angelina::new(operator_data, params))),
        "Aosta" => Some(Box::new(Aosta::new(operator_data, params))),
        "April" => Some(Box::new(April::new(operator_data, params))),
        "Archetto" => Some(Box::new(Archetto::new(operator_data, params))),
        "Arene" => Some(Box::new(Arene::new(operator_data, params))),
        "Asbestos" => Some(Box::new(Asbestos::new(operator_data, params))),
        "Ascalon" => Some(Box::new(Ascalon::new(operator_data, params))),
        "Ash" => Some(Box::new(Ash::new(operator_data, params))),
        "Ashlock" => Some(Box::new(Ashlock::new(operator_data, params))),
        "Astesia" => Some(Box::new(Astesia::new(operator_data, params))),
        "Astgenne" => Some(Box::new(Astgenne::new(operator_data, params))),
        "Aurora" => Some(Box::new(Aurora::new(operator_data, params))),
        "Ayerscarpe" => Some(Box::new(Ayerscarpe::new(operator_data, params))),
        "Bagpipe" => Some(Box::new(Bagpipe::new(operator_data, params))),
        "Beehunter" => Some(Box::new(Beehunter::new(operator_data, params))),
        "Beeswax" => Some(Box::new(Beeswax::new(operator_data, params))),
        "Bibeak" => Some(Box::new(Bibeak::new(operator_data, params))),
        "Blaze" => Some(Box::new(Blaze::new(operator_data, params))),
        "BlazeAlter" => Some(Box::new(BlazeAlter::new(operator_data, params))),
        "Blemishine" => Some(Box::new(Blemishine::new(operator_data, params))),
        "Blitz" => Some(Box::new(Blitz::new(operator_data, params))),
        "BluePoison" => Some(Box::new(BluePoison::new(operator_data, params))),
        "Broca" => Some(Box::new(Broca::new(operator_data, params))),
        "Bryophyta" => Some(Box::new(Bryophyta::new(operator_data, params))),
        "Cantabile" => Some(Box::new(Cantabile::new(operator_data, params))),
        "Caper" => Some(Box::new(Caper::new(operator_data, params))),
        "Carnelian" => Some(Box::new(Carnelian::new(operator_data, params))),
        "Castle3" => Some(Box::new(Castle3::new(operator_data, params))),
        "Catapult" => Some(Box::new(Catapult::new(operator_data, params))),
        "Ceobe" => Some(Box::new(Ceobe::new(operator_data, params))),
        "Chen" => Some(Box::new(Chen::new(operator_data, params))),
        "ChenAlter" => Some(Box::new(ChenAlter::new(operator_data, params))),
        "Chongyue" => Some(Box::new(Chongyue::new(operator_data, params))),
        "CivilightEterna" => Some(Box::new(CivilightEterna::new(operator_data, params))),
        "Click" => Some(Box::new(Click::new(operator_data, params))),
        "Coldshot" => Some(Box::new(Coldshot::new(operator_data, params))),
        "Contrail" => Some(Box::new(Contrail::new(operator_data, params))),
        "Conviction" => Some(Box::new(Conviction::new(operator_data, params))),
        "Crownslayer" => Some(Box::new(Crownslayer::new(operator_data, params))),
        "Dagda" => Some(Box::new(Dagda::new(operator_data, params))),
        "Degenbrecher" => Some(Box::new(Degenbrecher::new(operator_data, params))),
        "Diamante" => Some(Box::new(Diamante::new(operator_data, params))),
        "Dobermann" => Some(Box::new(Dobermann::new(operator_data, params))),
        "Doc" => Some(Box::new(Doc::new(operator_data, params))),
        "Dorothy" => Some(Box::new(Dorothy::new(operator_data, params))),
        "Durin" => Some(Box::new(Durin::new(operator_data, params))),
        "Durnar" => Some(Box::new(Durnar::new(operator_data, params))),
        "Dusk" => Some(Box::new(Dusk::new(operator_data, params))),
        "Ebenholz" => Some(Box::new(Ebenholz::new(operator_data, params))),
        "Ela" => Some(Box::new(Ela::new(operator_data, params))),
        "Entelechia" => Some(Box::new(Entelechia::new(operator_data, params))),
        "Erato" => Some(Box::new(Erato::new(operator_data, params))),
        "Estelle" => Some(Box::new(Estelle::new(operator_data, params))),
        "Ethan" => Some(Box::new(Ethan::new(operator_data, params))),
        "Eunectes" => Some(Box::new(Eunectes::new(operator_data, params))),
        "ExecutorAlter" => Some(Box::new(ExecutorAlter::new(operator_data, params))),
        "Exusiai" => Some(Box::new(Exusiai::new(operator_data, params))),
        "ExusiaiAlter" => Some(Box::new(ExusiaiAlter::new(operator_data, params))),
        "Eyjafjalla" => Some(Box::new(Eyjafjalla::new(operator_data, params))),
        "FangAlter" => Some(Box::new(FangAlter::new(operator_data, params))),
        "Fartooth" => Some(Box::new(Fartooth::new(operator_data, params))),
        "Fiammetta" => Some(Box::new(Fiammetta::new(operator_data, params))),
        "Figurino" => Some(Box::new(Figurino::new(operator_data, params))),
        "Firewhistle" => Some(Box::new(Firewhistle::new(operator_data, params))),
        "Flamebringer" => Some(Box::new(Flamebringer::new(operator_data, params))),
        "Flametail" => Some(Box::new(Flametail::new(operator_data, params))),
        "Flint" => Some(Box::new(Flint::new(operator_data, params))),
        "Folinic" => Some(Box::new(Folinic::new(operator_data, params))),
        "Franka" => Some(Box::new(Franka::new(operator_data, params))),
        "Frost" => Some(Box::new(Frost::new(operator_data, params))),
        "Frostleaf" => Some(Box::new(Frostleaf::new(operator_data, params))),
        "Fuze" => Some(Box::new(Fuze::new(operator_data, params))),
        "GavialAlter" => Some(Box::new(GavialAlter::new(operator_data, params))),
        "Gladiia" => Some(Box::new(Gladiia::new(operator_data, params))),
        "Gnosis" => Some(Box::new(Gnosis::new(operator_data, params))),
        "Goldenglow" => Some(Box::new(Goldenglow::new(operator_data, params))),
        "Gracebearer" => Some(Box::new(Gracebearer::new(operator_data, params))),
        "Grani" => Some(Box::new(Grani::new(operator_data, params))),
        "GreyThroat" => Some(Box::new(GreyThroat::new(operator_data, params))),
        "GreyyAlter" => Some(Box::new(GreyyAlter::new(operator_data, params))),
        "Hadiya" => Some(Box::new(Hadiya::new(operator_data, params))),
        "Harmonie" => Some(Box::new(Harmonie::new(operator_data, params))),
        "Haze" => Some(Box::new(Haze::new(operator_data, params))),
        "Hellagur" => Some(Box::new(Hellagur::new(operator_data, params))),
        "Hibiscus" => Some(Box::new(Hibiscus::new(operator_data, params))),
        "Highmore" => Some(Box::new(Highmore::new(operator_data, params))),
        "Hoederer" => Some(Box::new(Hoederer::new(operator_data, params))),
        "Hoolheyak" => Some(Box::new(Hoolheyak::new(operator_data, params))),
        "Horn" => Some(Box::new(Horn::new(operator_data, params))),
        "Hoshiguma" => Some(Box::new(Hoshiguma::new(operator_data, params))),
        "HoshigumaAlter" => Some(Box::new(HoshigumaAlter::new(operator_data, params))),
        "Humus" => Some(Box::new(Humus::new(operator_data, params))),
        "Iana" => Some(Box::new(Iana::new(operator_data, params))),
        "Ifrit" => Some(Box::new(Ifrit::new(operator_data, params))),
        "Indra" => Some(Box::new(Indra::new(operator_data, params))),
        "Ines" => Some(Box::new(Ines::new(operator_data, params))),
        "Insider" => Some(Box::new(Insider::new(operator_data, params))),
        "Irene" => Some(Box::new(Irene::new(operator_data, params))),
        "Jackie" => Some(Box::new(Jackie::new(operator_data, params))),
        "Jaye" => Some(Box::new(Jaye::new(operator_data, params))),
        "Jessica" => Some(Box::new(Jessica::new(operator_data, params))),
        "JessicaAlter" => Some(Box::new(JessicaAlter::new(operator_data, params))),
        "JusticeKnight" => Some(Box::new(JusticeKnight::new(operator_data, params))),
        "Kafka" => Some(Box::new(Kafka::new(operator_data, params))),
        "Kaltsit" => Some(Box::new(Kaltsit::new(operator_data, params))),
        "Kazemaru" => Some(Box::new(Kazemaru::new(operator_data, params))),
        "Kirara" => Some(Box::new(Kirara::new(operator_data, params))),
        "Kjera" => Some(Box::new(Kjera::new(operator_data, params))),
        "Kroos" => Some(Box::new(Kroos::new(operator_data, params))),
        "KroosAlter" => Some(Box::new(KroosAlter::new(operator_data, params))),
        "LaPluma" => Some(Box::new(LaPluma::new(operator_data, params))),
        "Laios" => Some(Box::new(Laios::new(operator_data, params))),
        "Lappland" => Some(Box::new(Lappland::new(operator_data, params))),
        "LapplandAlter" => Some(Box::new(LapplandAlter::new(operator_data, params))),
        "Lava3star" => Some(Box::new(Lava3star::new(operator_data, params))),
        "Lavaalt" => Some(Box::new(Lavaalt::new(operator_data, params))),
        "Lee" => Some(Box::new(Lee::new(operator_data, params))),
        "LeiziAlter" => Some(Box::new(LeiziAlter::new(operator_data, params))),
        "Lemuen" => Some(Box::new(Lemuen::new(operator_data, params))),
        "Lessing" => Some(Box::new(Lessing::new(operator_data, params))),
        "Leto" => Some(Box::new(Leto::new(operator_data, params))),
        "Lin" => Some(Box::new(Lin::new(operator_data, params))),
        "Ling" => Some(Box::new(Ling::new(operator_data, params))),
        "Logos" => Some(Box::new(Logos::new(operator_data, params))),
        "Lucilla" => Some(Box::new(Lucilla::new(operator_data, params))),
        "Lunacub" => Some(Box::new(Lunacub::new(operator_data, params))),
        "LuoXiaohei" => Some(Box::new(LuoXiaohei::new(operator_data, params))),
        "Lutonada" => Some(Box::new(Lutonada::new(operator_data, params))),
        "Magallan" => Some(Box::new(Magallan::new(operator_data, params))),
        "Manticore" => Some(Box::new(Manticore::new(operator_data, params))),
        "Marcille" => Some(Box::new(Marcille::new(operator_data, params))),
        "Matoimaru" => Some(Box::new(Matoimaru::new(operator_data, params))),
        "May" => Some(Box::new(May::new(operator_data, params))),
        "Melantha" => Some(Box::new(Melantha::new(operator_data, params))),
        "Meteor" => Some(Box::new(Meteor::new(operator_data, params))),
        "Meteorite" => Some(Box::new(Meteorite::new(operator_data, params))),
        "Midnight" => Some(Box::new(Midnight::new(operator_data, params))),
        "Minimalist" => Some(Box::new(Minimalist::new(operator_data, params))),
        "Mint" => Some(Box::new(Mint::new(operator_data, params))),
        "MissChristine" => Some(Box::new(MissChristine::new(operator_data, params))),
        "MisumiUika" => Some(Box::new(MisumiUika::new(operator_data, params))),
        "Mizuki" => Some(Box::new(Mizuki::new(operator_data, params))),
        "Mlynar" => Some(Box::new(Mlynar::new(operator_data, params))),
        "Mon3tr" => Some(Box::new(Mon3tr::new(operator_data, params))),
        "Morgan" => Some(Box::new(Morgan::new(operator_data, params))),
        "Mostima" => Some(Box::new(Mostima::new(operator_data, params))),
        "Mountain" => Some(Box::new(Mountain::new(operator_data, params))),
        "Mousse" => Some(Box::new(Mousse::new(operator_data, params))),
        "MrNothing" => Some(Box::new(MrNothing::new(operator_data, params))),
        "Mudrock" => Some(Box::new(Mudrock::new(operator_data, params))),
        "Muelsyse" => Some(Box::new(Muelsyse::new(operator_data, params))),
        "Narantuya" => Some(Box::new(Narantuya::new(operator_data, params))),
        "NearlAlter" => Some(Box::new(NearlAlter::new(operator_data, params))),
        "Necrass" => Some(Box::new(Necrass::new(operator_data, params))),
        "Nian" => Some(Box::new(Nian::new(operator_data, params))),
        "Nymph" => Some(Box::new(Nymph::new(operator_data, params))),
        "Odda" => Some(Box::new(Odda::new(operator_data, params))),
        "Pallas" => Some(Box::new(Pallas::new(operator_data, params))),
        "Passenger" => Some(Box::new(Passenger::new(operator_data, params))),
        "Penance" => Some(Box::new(Penance::new(operator_data, params))),
        "Pepe" => Some(Box::new(Pepe::new(operator_data, params))),
        "Phantom" => Some(Box::new(Phantom::new(operator_data, params))),
        "Pinecone" => Some(Box::new(Pinecone::new(operator_data, params))),
        "Pith" => Some(Box::new(Pith::new(operator_data, params))),
        "Platinum" => Some(Box::new(Platinum::new(operator_data, params))),
        "Plume" => Some(Box::new(Plume::new(operator_data, params))),
        "Popukar" => Some(Box::new(Popukar::new(operator_data, params))),
        "Pozemka" => Some(Box::new(Pozemka::new(operator_data, params))),
        "PramanixAlter" => Some(Box::new(PramanixAlter::new(operator_data, params))),
        "ProjektRed" => Some(Box::new(ProjektRed::new(operator_data, params))),
        "Provence" => Some(Box::new(Provence::new(operator_data, params))),
        "Pudding" => Some(Box::new(Pudding::new(operator_data, params))),
        "Qiubai" => Some(Box::new(Qiubai::new(operator_data, params))),
        "Quartz" => Some(Box::new(Quartz::new(operator_data, params))),
        "Raidian" => Some(Box::new(Raidian::new(operator_data, params))),
        "Rangers" => Some(Box::new(Rangers::new(operator_data, params))),
        "Ray" => Some(Box::new(Ray::new(operator_data, params))),
        "ReedAlter" => Some(Box::new(ReedAlter::new(operator_data, params))),
        "Rockrock" => Some(Box::new(Rockrock::new(operator_data, params))),
        "Rosa" => Some(Box::new(Rosa::new(operator_data, params))),
        "Rosmontis" => Some(Box::new(Rosmontis::new(operator_data, params))),
        "Saga" => Some(Box::new(Saga::new(operator_data, params))),
        "SandReckoner" => Some(Box::new(SandReckoner::new(operator_data, params))),
        "SanktaMiksaparato" => Some(Box::new(SanktaMiksaparato::new(operator_data, params))),
        "Savage" => Some(Box::new(Savage::new(operator_data, params))),
        "Scavenger" => Some(Box::new(Scavenger::new(operator_data, params))),
        "Scene" => Some(Box::new(Scene::new(operator_data, params))),
        "Schwarz" => Some(Box::new(Schwarz::new(operator_data, params))),
        "Shalem" => Some(Box::new(Shalem::new(operator_data, params))),
        "Sharp" => Some(Box::new(Sharp::new(operator_data, params))),
        "Sideroca" => Some(Box::new(Sideroca::new(operator_data, params))),
        "Siege" => Some(Box::new(Siege::new(operator_data, params))),
        "SilverAsh" => Some(Box::new(SilverAsh::new(operator_data, params))),
        "Skadi" => Some(Box::new(Skadi::new(operator_data, params))),
        "Skalter" => Some(Box::new(Skalter::new(operator_data, params))),
        "Snegurochka" => Some(Box::new(Snegurochka::new(operator_data, params))),
        "Specter" => Some(Box::new(Specter::new(operator_data, params))),
        "SpecterAlter" => Some(Box::new(SpecterAlter::new(operator_data, params))),
        "Stainless" => Some(Box::new(Stainless::new(operator_data, params))),
        "Steward" => Some(Box::new(Steward::new(operator_data, params))),
        "Stormeye" => Some(Box::new(Stormeye::new(operator_data, params))),
        "Surfer" => Some(Box::new(Surfer::new(operator_data, params))),
        "Surtr" => Some(Box::new(Surtr::new(operator_data, params))),
        "Suzuran" => Some(Box::new(Suzuran::new(operator_data, params))),
        "SwireAlt" => Some(Box::new(SwireAlt::new(operator_data, params))),
        "Tachanka" => Some(Box::new(Tachanka::new(operator_data, params))),
        "Tecno" => Some(Box::new(Tecno::new(operator_data, params))),
        "Tequila" => Some(Box::new(Tequila::new(operator_data, params))),
        "TerraResearchCommission" => Some(Box::new(TerraResearchCommission::new(
            operator_data,
            params,
        ))),
        "TexasAlter" => Some(Box::new(TexasAlter::new(operator_data, params))),
        "Thorns" => Some(Box::new(Thorns::new(operator_data, params))),
        "ThornsAlter" => Some(Box::new(ThornsAlter::new(operator_data, params))),
        "TinMan" => Some(Box::new(TinMan::new(operator_data, params))),
        "Tippi" => Some(Box::new(Tippi::new(operator_data, params))),
        "Toddifons" => Some(Box::new(Toddifons::new(operator_data, params))),
        "TogawaSakiko" => Some(Box::new(TogawaSakiko::new(operator_data, params))),
        "Tomimi" => Some(Box::new(Tomimi::new(operator_data, params))),
        "Totter" => Some(Box::new(Totter::new(operator_data, params))),
        "Tragodia" => Some(Box::new(Tragodia::new(operator_data, params))),
        "Typhon" => Some(Box::new(Typhon::new(operator_data, params))),
        "Ulpianus" => Some(Box::new(Ulpianus::new(operator_data, params))),
        "Underflow" => Some(Box::new(Underflow::new(operator_data, params))),
        "Utage" => Some(Box::new(Utage::new(operator_data, params))),
        "Vanilla" => Some(Box::new(Vanilla::new(operator_data, params))),
        "Vendela" => Some(Box::new(Vendela::new(operator_data, params))),
        "Vermeil" => Some(Box::new(Vermeil::new(operator_data, params))),
        "Vetochki" => Some(Box::new(Vetochki::new(operator_data, params))),
        "Vigil" => Some(Box::new(Vigil::new(operator_data, params))),
        "Vigna" => Some(Box::new(Vigna::new(operator_data, params))),
        "Vina" => Some(Box::new(Vina::new(operator_data, params))),
        "Virtuosa" => Some(Box::new(Virtuosa::new(operator_data, params))),
        "Viviana" => Some(Box::new(Viviana::new(operator_data, params))),
        "Vulcan" => Some(Box::new(Vulcan::new(operator_data, params))),
        "Vulpisfoglia" => Some(Box::new(Vulpisfoglia::new(operator_data, params))),
        "W" => Some(Box::new(W::new(operator_data, params))),
        "WakabaMutsumi" => Some(Box::new(WakabaMutsumi::new(operator_data, params))),
        "Walter" => Some(Box::new(Walter::new(operator_data, params))),
        "Warmy" => Some(Box::new(Warmy::new(operator_data, params))),
        "Weedy" => Some(Box::new(Weedy::new(operator_data, params))),
        "Whislash" => Some(Box::new(Whislash::new(operator_data, params))),
        "Wildmane" => Some(Box::new(Wildmane::new(operator_data, params))),
        "Windscoot" => Some(Box::new(Windscoot::new(operator_data, params))),
        "YahataUmiri" => Some(Box::new(YahataUmiri::new(operator_data, params))),
        "YatoAlter" => Some(Box::new(YatoAlter::new(operator_data, params))),
        "Yu" => Some(Box::new(Yu::new(operator_data, params))),
        "YutenjiNyamu" => Some(Box::new(YutenjiNyamu::new(operator_data, params))),
        "ZuoLe" => Some(Box::new(ZuoLe::new(operator_data, params))),
        "TwelveF" => Some(Box::new(TwelveF::new(operator_data, params))),
        _ => None,
    }
}

/// Returns a list of all operator names that have DPS calculator implementations
///
/// # Returns
/// A static slice of operator names that can be passed to `create_operator()`
pub fn get_supported_operator_names() -> &'static [&'static str] {
    &[
        "Aak",
        "Absinthe",
        "Aciddrop",
        "Adnachiel",
        "Amiya",
        "AmiyaGuard",
        "AmiyaMedic",
        "Andreana",
        "Angelina",
        "Aosta",
        "April",
        "Archetto",
        "Arene",
        "Asbestos",
        "Ascalon",
        "Ash",
        "Ashlock",
        "Astesia",
        "Astgenne",
        "Aurora",
        "Ayerscarpe",
        "Bagpipe",
        "Beehunter",
        "Beeswax",
        "Bibeak",
        "Blaze",
        "BlazeAlter",
        "Blemishine",
        "Blitz",
        "BluePoison",
        "Broca",
        "Bryophyta",
        "Cantabile",
        "Caper",
        "Carnelian",
        "Castle3",
        "Catapult",
        "Ceobe",
        "Chen",
        "ChenAlter",
        "Chongyue",
        "CivilightEterna",
        "Click",
        "Coldshot",
        "Contrail",
        "Conviction",
        "Crownslayer",
        "Dagda",
        "Degenbrecher",
        "Diamante",
        "Dobermann",
        "Doc",
        "Dorothy",
        "Durin",
        "Durnar",
        "Dusk",
        "Ebenholz",
        "Ela",
        "Entelechia",
        "Erato",
        "Estelle",
        "Ethan",
        "Eunectes",
        "ExecutorAlter",
        "Exusiai",
        "ExusiaiAlter",
        "Eyjafjalla",
        "FangAlter",
        "Fartooth",
        "Fiammetta",
        "Figurino",
        "Firewhistle",
        "Flamebringer",
        "Flametail",
        "Flint",
        "Folinic",
        "Franka",
        "Frost",
        "Frostleaf",
        "Fuze",
        "GavialAlter",
        "Gladiia",
        "Gnosis",
        "Goldenglow",
        "Gracebearer",
        "Grani",
        "GreyThroat",
        "GreyyAlter",
        "Hadiya",
        "Harmonie",
        "Haze",
        "Hellagur",
        "Hibiscus",
        "Highmore",
        "Hoederer",
        "Hoolheyak",
        "Horn",
        "Hoshiguma",
        "HoshigumaAlter",
        "Humus",
        "Iana",
        "Ifrit",
        "Indra",
        "Ines",
        "Insider",
        "Irene",
        "Jackie",
        "Jaye",
        "Jessica",
        "JessicaAlter",
        "JusticeKnight",
        "Kafka",
        "Kaltsit",
        "Kazemaru",
        "Kirara",
        "Kjera",
        "Kroos",
        "KroosAlter",
        "LaPluma",
        "Laios",
        "Lappland",
        "LapplandAlter",
        "Lava3star",
        "Lavaalt",
        "Lee",
        "LeiziAlter",
        "Lemuen",
        "Lessing",
        "Leto",
        "Lin",
        "Ling",
        "Logos",
        "Lucilla",
        "Lunacub",
        "LuoXiaohei",
        "Lutonada",
        "Magallan",
        "Manticore",
        "Marcille",
        "Matoimaru",
        "May",
        "Melantha",
        "Meteor",
        "Meteorite",
        "Midnight",
        "Minimalist",
        "Mint",
        "MissChristine",
        "MisumiUika",
        "Mizuki",
        "Mlynar",
        "Mon3tr",
        "Morgan",
        "Mostima",
        "Mountain",
        "Mousse",
        "MrNothing",
        "Mudrock",
        "Muelsyse",
        "Narantuya",
        "NearlAlter",
        "Necrass",
        "Nian",
        "Nymph",
        "Odda",
        "Pallas",
        "Passenger",
        "Penance",
        "Pepe",
        "Phantom",
        "Pinecone",
        "Pith",
        "Platinum",
        "Plume",
        "Popukar",
        "Pozemka",
        "PramanixAlter",
        "ProjektRed",
        "Provence",
        "Pudding",
        "Qiubai",
        "Quartz",
        "Raidian",
        "Rangers",
        "Ray",
        "ReedAlter",
        "Rockrock",
        "Rosa",
        "Rosmontis",
        "Saga",
        "SandReckoner",
        "SanktaMiksaparato",
        "Savage",
        "Scavenger",
        "Scene",
        "Schwarz",
        "Shalem",
        "Sharp",
        "Sideroca",
        "Siege",
        "SilverAsh",
        "Skadi",
        "Skalter",
        "Snegurochka",
        "Specter",
        "SpecterAlter",
        "Stainless",
        "Steward",
        "Stormeye",
        "Surfer",
        "Surtr",
        "Suzuran",
        "SwireAlt",
        "Tachanka",
        "Tecno",
        "Tequila",
        "TerraResearchCommission",
        "TexasAlter",
        "Thorns",
        "ThornsAlter",
        "TinMan",
        "Tippi",
        "Toddifons",
        "TogawaSakiko",
        "Tomimi",
        "Totter",
        "Tragodia",
        "Typhon",
        "Ulpianus",
        "Underflow",
        "Utage",
        "Vanilla",
        "Vendela",
        "Vermeil",
        "Vetochki",
        "Vigil",
        "Vigna",
        "Vina",
        "Virtuosa",
        "Viviana",
        "Vulcan",
        "Vulpisfoglia",
        "W",
        "WakabaMutsumi",
        "Walter",
        "Warmy",
        "Weedy",
        "Whislash",
        "Wildmane",
        "Windscoot",
        "YahataUmiri",
        "YatoAlter",
        "Yu",
        "YutenjiNyamu",
        "ZuoLe",
        "TwelveF",
    ]
}

/// Returns metadata about an operator's available configuration options
///
/// # Arguments
/// * `name` - The operator name (e.g., "Blaze", "ExusiaiAlter")
///
/// # Returns
/// Some(OperatorMetadata) if the operator is found, None otherwise
pub fn get_operator_metadata(name: &str) -> Option<OperatorMetadata> {
    match name {
        "Aak" => Some(OperatorMetadata {
            available_skills: vec![1, 3],
            available_modules: vec![1],
            default_skill_index: 1,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Absinthe" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Aciddrop" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Adnachiel" => Some(OperatorMetadata {
            available_skills: vec![1],
            available_modules: vec![],
            default_skill_index: 1,
            default_potential: 6,
            default_module_index: 0,
        }),
        "Amiya" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![2],
            default_skill_index: 3,
            default_potential: 6,
            default_module_index: 2,
        }),
        "AmiyaGuard" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 1,
            default_potential: 6,
            default_module_index: 1,
        }),
        "AmiyaMedic" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Andreana" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Angelina" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![2, 1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Aosta" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "April" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 2,
        }),
        "Archetto" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![2, 1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Arene" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 2,
        }),
        "Asbestos" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Ascalon" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Ash" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2, 1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Ashlock" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Astesia" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 2,
        }),
        "Astgenne" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 2,
        }),
        "Aurora" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Ayerscarpe" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Bagpipe" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Beehunter" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Beeswax" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Bibeak" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 1,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Blaze" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1, 2],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "BlazeAlter" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Blemishine" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![2, 1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Blitz" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "BluePoison" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 1,
            default_potential: 1,
            default_module_index: 2,
        }),
        "Broca" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Bryophyta" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Cantabile" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 2,
        }),
        "Caper" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Carnelian" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Castle3" => Some(OperatorMetadata {
            available_skills: vec![],
            available_modules: vec![],
            default_skill_index: 0,
            default_potential: 6,
            default_module_index: 0,
        }),
        "Catapult" => Some(OperatorMetadata {
            available_skills: vec![1],
            available_modules: vec![],
            default_skill_index: 1,
            default_potential: 6,
            default_module_index: 0,
        }),
        "Ceobe" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Chen" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "ChenAlter" => Some(OperatorMetadata {
            available_skills: vec![1, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 2,
        }),
        "Chongyue" => Some(OperatorMetadata {
            available_skills: vec![1, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 2,
        }),
        "CivilightEterna" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Click" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 2,
        }),
        "Coldshot" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Contrail" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 0,
        }),
        "Conviction" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 1,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Crownslayer" => Some(OperatorMetadata {
            available_skills: vec![1, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Dagda" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Degenbrecher" => Some(OperatorMetadata {
            available_skills: vec![1, 3],
            available_modules: vec![1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Diamante" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Dobermann" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 2,
        }),
        "Doc" => Some(OperatorMetadata {
            available_skills: vec![1],
            available_modules: vec![2],
            default_skill_index: 1,
            default_potential: 1,
            default_module_index: 2,
        }),
        "Dorothy" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![2, 1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 2,
        }),
        "Durin" => Some(OperatorMetadata {
            available_skills: vec![],
            available_modules: vec![],
            default_skill_index: 0,
            default_potential: 6,
            default_module_index: 0,
        }),
        "Durnar" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Dusk" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2, 3],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Ebenholz" => Some(OperatorMetadata {
            available_skills: vec![1, 3],
            available_modules: vec![1, 2, 3],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 3,
        }),
        "Ela" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![3],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 3,
        }),
        "Entelechia" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Erato" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Estelle" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 2,
        }),
        "Ethan" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Eunectes" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2, 3],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "ExecutorAlter" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Exusiai" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 2,
        }),
        "ExusiaiAlter" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Eyjafjalla" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "FangAlter" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Fartooth" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Fiammetta" => Some(OperatorMetadata {
            available_skills: vec![1, 3],
            available_modules: vec![2, 1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Figurino" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 1,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Firewhistle" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Flamebringer" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 2,
        }),
        "Flametail" => Some(OperatorMetadata {
            available_skills: vec![1, 3],
            available_modules: vec![2, 1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Flint" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Folinic" => Some(OperatorMetadata {
            available_skills: vec![2],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 2,
        }),
        "Franka" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Frost" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 2,
        }),
        "Frostleaf" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 1,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Fuze" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 1,
            default_potential: 6,
            default_module_index: 2,
        }),
        "GavialAlter" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Gladiia" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Gnosis" => Some(OperatorMetadata {
            available_skills: vec![1, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Goldenglow" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Gracebearer" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![],
            default_skill_index: 1,
            default_potential: 1,
            default_module_index: 0,
        }),
        "Grani" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "GreyThroat" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 2,
        }),
        "GreyyAlter" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 1,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Hadiya" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 0,
        }),
        "Harmonie" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Haze" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Hellagur" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Hibiscus" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Highmore" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 1,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Hoederer" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Hoolheyak" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2, 3],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Horn" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Hoshiguma" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![2, 1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 2,
        }),
        "HoshigumaAlter" => Some(OperatorMetadata {
            available_skills: vec![1, 3],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Humus" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Iana" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Ifrit" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 3],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Indra" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Ines" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 2,
        }),
        "Insider" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Irene" => Some(OperatorMetadata {
            available_skills: vec![1, 3],
            available_modules: vec![2, 1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 2,
        }),
        "Jackie" => Some(OperatorMetadata {
            available_skills: vec![],
            available_modules: vec![],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Jaye" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Jessica" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 1,
            default_potential: 6,
            default_module_index: 2,
        }),
        "JessicaAlter" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "JusticeKnight" => Some(OperatorMetadata {
            available_skills: vec![],
            available_modules: vec![],
            default_skill_index: 0,
            default_potential: 6,
            default_module_index: 0,
        }),
        "Kafka" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 2,
        }),
        "Kaltsit" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2, 3],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 2,
        }),
        "Kazemaru" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Kirara" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Kjera" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 2,
        }),
        "Kroos" => Some(OperatorMetadata {
            available_skills: vec![1],
            available_modules: vec![],
            default_skill_index: 1,
            default_potential: 6,
            default_module_index: 0,
        }),
        "KroosAlter" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "LaPluma" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 1,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Laios" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 1,
            default_potential: 1,
            default_module_index: 2,
        }),
        "Lappland" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "LapplandAlter" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Lava3star" => Some(OperatorMetadata {
            available_skills: vec![1],
            available_modules: vec![],
            default_skill_index: 1,
            default_potential: 6,
            default_module_index: 0,
        }),
        "Lavaalt" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Lee" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "LeiziAlter" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Lemuen" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 2,
        }),
        "Lessing" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Leto" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 2,
        }),
        "Lin" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Ling" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 2,
        }),
        "Logos" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![3, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 3,
        }),
        "Lucilla" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Lunacub" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 2,
        }),
        "LuoXiaohei" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 2,
        }),
        "Lutonada" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Magallan" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 2,
        }),
        "Manticore" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Marcille" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 2,
        }),
        "Matoimaru" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 2,
        }),
        "May" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 1,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Melantha" => Some(OperatorMetadata {
            available_skills: vec![1],
            available_modules: vec![],
            default_skill_index: 1,
            default_potential: 6,
            default_module_index: 0,
        }),
        "Meteor" => Some(OperatorMetadata {
            available_skills: vec![1],
            available_modules: vec![1],
            default_skill_index: 1,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Meteorite" => Some(OperatorMetadata {
            available_skills: vec![1],
            available_modules: vec![2],
            default_skill_index: 1,
            default_potential: 1,
            default_module_index: 2,
        }),
        "Midnight" => Some(OperatorMetadata {
            available_skills: vec![1],
            available_modules: vec![],
            default_skill_index: 1,
            default_potential: 6,
            default_module_index: 0,
        }),
        "Minimalist" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 2,
        }),
        "Mint" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "MissChristine" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "MisumiUika" => Some(OperatorMetadata {
            available_skills: vec![2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Mizuki" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2, 3],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Mlynar" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Mon3tr" => Some(OperatorMetadata {
            available_skills: vec![3],
            available_modules: vec![],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 0,
        }),
        "Morgan" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Mostima" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![2, 1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 2,
        }),
        "Mountain" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![2, 1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Mousse" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 1,
            default_potential: 6,
            default_module_index: 1,
        }),
        "MrNothing" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Mudrock" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Muelsyse" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Narantuya" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "NearlAlter" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Necrass" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Nian" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Nymph" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Odda" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Pallas" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 1,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Passenger" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Penance" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Pepe" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 3],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Phantom" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2, 3],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 2,
        }),
        "Pinecone" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 1,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Pith" => Some(OperatorMetadata {
            available_skills: vec![1],
            available_modules: vec![],
            default_skill_index: 1,
            default_potential: 1,
            default_module_index: 0,
        }),
        "Platinum" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Plume" => Some(OperatorMetadata {
            available_skills: vec![1],
            available_modules: vec![],
            default_skill_index: 1,
            default_potential: 6,
            default_module_index: 0,
        }),
        "Popukar" => Some(OperatorMetadata {
            available_skills: vec![1],
            available_modules: vec![],
            default_skill_index: 1,
            default_potential: 6,
            default_module_index: 0,
        }),
        "Pozemka" => Some(OperatorMetadata {
            available_skills: vec![1, 3],
            available_modules: vec![2, 1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 2,
        }),
        "PramanixAlter" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 2,
        }),
        "ProjektRed" => Some(OperatorMetadata {
            available_skills: vec![1],
            available_modules: vec![2],
            default_skill_index: 1,
            default_potential: 1,
            default_module_index: 2,
        }),
        "Provence" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Pudding" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 2,
        }),
        "Qiubai" => Some(OperatorMetadata {
            available_skills: vec![1, 3],
            available_modules: vec![1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Quartz" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 1,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Raidian" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![3, 2],
            default_skill_index: 3,
            default_potential: 6,
            default_module_index: 3,
        }),
        "Rangers" => Some(OperatorMetadata {
            available_skills: vec![],
            available_modules: vec![],
            default_skill_index: 0,
            default_potential: 6,
            default_module_index: 0,
        }),
        "Ray" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "ReedAlter" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Rockrock" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Rosa" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Rosmontis" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 3],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Saga" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![2, 1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "SandReckoner" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "SanktaMiksaparato" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Savage" => Some(OperatorMetadata {
            available_skills: vec![1],
            available_modules: vec![1],
            default_skill_index: 1,
            default_potential: 5,
            default_module_index: 1,
        }),
        "Scavenger" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Scene" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Schwarz" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Shalem" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Sharp" => Some(OperatorMetadata {
            available_skills: vec![1],
            available_modules: vec![],
            default_skill_index: 1,
            default_potential: 1,
            default_module_index: 0,
        }),
        "Sideroca" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 2,
        }),
        "Siege" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "SilverAsh" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Skadi" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![2, 1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Skalter" => Some(OperatorMetadata {
            available_skills: vec![1, 3],
            available_modules: vec![1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Snegurochka" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 1,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Specter" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "SpecterAlter" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Stainless" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Steward" => Some(OperatorMetadata {
            available_skills: vec![1],
            available_modules: vec![],
            default_skill_index: 1,
            default_potential: 6,
            default_module_index: 0,
        }),
        "Stormeye" => Some(OperatorMetadata {
            available_skills: vec![1],
            available_modules: vec![],
            default_skill_index: 1,
            default_potential: 1,
            default_module_index: 0,
        }),
        "Surfer" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 0,
        }),
        "Surtr" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Suzuran" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "SwireAlt" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2, 3],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Tachanka" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Tecno" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 2,
        }),
        "Tequila" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "TerraResearchCommission" => Some(OperatorMetadata {
            available_skills: vec![],
            available_modules: vec![],
            default_skill_index: 0,
            default_potential: 6,
            default_module_index: 0,
        }),
        "TexasAlter" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 2,
        }),
        "Thorns" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 3],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "ThornsAlter" => Some(OperatorMetadata {
            available_skills: vec![2, 3],
            available_modules: vec![1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "TinMan" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 1,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Tippi" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 0,
        }),
        "Toddifons" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "TogawaSakiko" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 2,
        }),
        "Tomimi" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 2,
        }),
        "Totter" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Tragodia" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Typhon" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Ulpianus" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Underflow" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Utage" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Vanilla" => Some(OperatorMetadata {
            available_skills: vec![1],
            available_modules: vec![],
            default_skill_index: 1,
            default_potential: 6,
            default_module_index: 0,
        }),
        "Vendela" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Vermeil" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Vetochki" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Vigil" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 6,
            default_module_index: 2,
        }),
        "Vigna" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 2,
        }),
        "Vina" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Virtuosa" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Viviana" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![3],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 3,
        }),
        "Vulcan" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Vulpisfoglia" => Some(OperatorMetadata {
            available_skills: vec![1, 3],
            available_modules: vec![1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "W" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 2,
        }),
        "WakabaMutsumi" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![2],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 2,
        }),
        "Walter" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Warmy" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Weedy" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1, 2],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Whislash" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Wildmane" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 1,
            default_potential: 6,
            default_module_index: 1,
        }),
        "Windscoot" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "YahataUmiri" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![2],
            default_skill_index: 1,
            default_potential: 6,
            default_module_index: 2,
        }),
        "YatoAlter" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1],
            default_skill_index: 1,
            default_potential: 1,
            default_module_index: 1,
        }),
        "Yu" => Some(OperatorMetadata {
            available_skills: vec![2],
            available_modules: vec![],
            default_skill_index: 2,
            default_potential: 1,
            default_module_index: 0,
        }),
        "YutenjiNyamu" => Some(OperatorMetadata {
            available_skills: vec![1, 2],
            available_modules: vec![1],
            default_skill_index: 2,
            default_potential: 6,
            default_module_index: 1,
        }),
        "ZuoLe" => Some(OperatorMetadata {
            available_skills: vec![1, 2, 3],
            available_modules: vec![1, 2],
            default_skill_index: 3,
            default_potential: 1,
            default_module_index: 1,
        }),
        "TwelveF" => Some(OperatorMetadata {
            available_skills: vec![],
            available_modules: vec![],
            default_skill_index: 0,
            default_potential: 6,
            default_module_index: 0,
        }),
        _ => None,
    }
}
