/**
 * Exact pull odds by forward dynamic programming over the pity state.
 *
 * This is not a simulation and not a lookup table. It carries the full probability
 * distribution over (rolls since last 6*, copies of the primary rate-up, copies of
 * any other rate-up, whether a first-6* guarantee has been spent) forward one roll at
 * a time, so every figure it returns is exact to floating point rather than sampled.
 * One pass yields the whole curve, because the state after roll `n` is precisely the
 * answer for "n pulls".
 *
 * Checked against the published table in imivi's arknights-pulls-calculator, which
 * was generated by an unrelated implementation. The single-rate-up curve agrees on
 * 1.0000% / 1.9900% / 2.9701% at rolls 1 / 2 / 3 against its 1% / 1.99% / 2.97%, and
 * the limited-banner figures at 300 rolls agree to within 0.08 percentage points
 * (specific 96.4231% against 96.38%, any 99.9768% against 99.98%, both 92.8695%
 * against 92.79%). Against 400,000-run Monte Carlo seeded with the test suite's own
 * generator, the largest disagreement across five banner types is 0.000632 absolute
 * (SINGLE 0.000230, LIMITED 0.000313, DOUBLE 0.000632, LINKAGE 0.000000,
 * ATTAIN 0.000069).
 *
 * WHERE THIS IS STILL APPROXIMATE, because the header above should not read as more
 * confident than the model is:
 *
 *   - On a banner featuring three or more rate-up 6*, the second slot aggregates
 *     "any featured operator other than the primary one". `specific` is exact;
 *     `both` then means "the primary and at least one other", which is the useful
 *     reading but not a per-operator joint. No live pool has more than two.
 *   - The Standard Selection threshold is applied from roll `first` inclusive. The
 *     game text, "after a total of 150 attempts the next 6 star is guaranteed", does
 *     not settle whether roll 150 is inside or outside the threshold. The difference
 *     is 0.29 percentage points on `any` at roll 150 (0.911004 exclusive against
 *     0.913908 inclusive). A single CN pull log crossing 150 on a DOUBLE pool would
 *     decide it; nothing available here does.
 */

import { HARD_PITY_PULL, type IBannerModel, sixStarRate } from "./rates";

/** Rolls since the last 6* can never exceed the roll that forces one. */
export const PITY_STATES = HARD_PITY_PULL;

export interface IOddsPoint {
    pulls: number;
    /** At least one copy of the primary featured operator. */
    specific: number;
    /** At least one copy of any featured operator. */
    any: number;
    /** The primary operator and at least one other featured one. */
    both: number;
    /**
     * Expected copies of the primary featured operator, counting past `maxCopies`
     * only up to that cap. At the default cap of 1 this equals `specific`.
     */
    expectedCopies: number;
    /** Expected 6* of any kind, including any handed over by a guarantee. */
    expectedSix: number;
    /**
     * Probability that copies of the primary operator have reached the cap, i.e.
     * `maxCopies` or more. With `maxCopies: 6` this is the cumulative chance of
     * having taken the operator to maximum potential.
     */
    copiesTail: number;
}

export interface IOddsResult extends IOddsPoint {
    /**
     * `copies[k]` is the probability of exactly k copies of the primary operator,
     * EXCEPT the final entry, which is the tail: k or more.
     */
    copies: number[];
    /**
     * Where the pity counter is left once these rolls are done, as a distribution
     * over rolls-since-last-6*. Feeding it into the next banner's `startPityDist` is
     * what lets a multi-banner plan carry pity the way the game does.
     */
    endPity: Float64Array;
}

export interface IOddsOptions {
    /** Rolls already taken since the user's last 6* on this pity scope. */
    startPity?: number;
    /**
     * The starting pity as a full distribution, which `startPity` cannot express once
     * a plan has spent rolls on an earlier banner of the same scope. Overrides
     * `startPity` when given. Renormalised on entry, so a caller may hand over an
     * unnormalised tail without corrupting the answer.
     */
    startPityDist?: ArrayLike<number> | null;
    /** Highest copy count to resolve individually; the last bucket collects above it. */
    maxCopies?: number;
    /**
     * Rolls already spent on THIS banner, which is what the 120/150/300 guarantees
     * count. Differs from `startPity` on a banner the user has already pulled on.
     */
    spentOnBanner?: number;
}

interface IGrid {
    /** Flat grid indexed by `pity * strideP + spent * strideG + ca * strideA + cb`. */
    data: Float64Array;
    capA: number;
    capB: number;
    /** 2 when a first-6* guarantee needs remembering, otherwise 1. */
    gStates: number;
    strideA: number;
    strideG: number;
    strideP: number;
}

function newGrid(capA: number, capB: number, gStates: number): IGrid {
    const strideA = capB + 1;
    const strideG = (capA + 1) * strideA;
    const strideP = gStates * strideG;
    return { data: new Float64Array(PITY_STATES * strideP), capA, capB, gStates, strideA, strideG, strideP };
}

/** The three shares a 6* can resolve into, clamped so they always sum to exactly 1. */
function splitOf(model: IBannerModel): { a: number; b: number; off: number } {
    const total = Math.min(1, Math.max(0, model.shareTotal));
    const a = Math.min(total, Math.max(0, model.shareEach));
    return { a, b: total - a, off: 1 - total };
}

/**
 * Walks the distribution forward `pulls` rolls, calling `onStep` after each one with
 * the grid and the running expected 6* count.
 *
 * Expected 6* is accumulated HERE rather than by a second recursion elsewhere. An
 * earlier version computed it on a separate one-dimensional pity grid, which was a
 * faithful marginal for every guarantee that only redirects a 6* but silently
 * undercounted LINKAGE by about 0.098 operators, because the collab handover grants a
 * 6* and resets pity outside the schedule. Two recursions that must agree are one
 * recursion too many.
 */
function walk(model: IBannerModel, pulls: number, options: Required<IOddsOptions>, capA: number, capB: number, onStep: (grid: IGrid, pulls: number, expectedSix: number) => void): { grid: IGrid; expectedSix: number } {
    const g = model.guarantee;
    const gStates = g.kind === "attain" ? 2 : 1;
    let grid = newGrid(capA, capB, gStates);
    let next = newGrid(capA, capB, gStates);
    const dist = options.startPityDist;
    if (dist) {
        let mass = 0;
        for (let i = 0; i < PITY_STATES && i < dist.length; i++) mass += Math.max(0, dist[i]);
        if (mass > 0) {
            for (let i = 0; i < PITY_STATES && i < dist.length; i++) grid.data[i * grid.strideP] = Math.max(0, dist[i]) / mass;
        } else {
            grid.data[0] = 1;
        }
    } else {
        const startPity = Math.min(Math.max(0, Math.floor(options.startPity)), PITY_STATES - 1);
        grid.data[startPity * grid.strideP] = 1;
    }

    const twoFeatured = model.featuredCount >= 2;
    const split = splitOf(model);
    let expectedSix = 0;

    for (let step = 0; step < pulls; step++) {
        next.data.fill(0);
        // Rolls spent on this banner once the current one resolves, 1-based.
        const onBanner = options.spentOnBanner + step + 1;
        let sixThisStep = 0;

        for (let pity = 0; pity < PITY_STATES; pity++) {
            const pityBase = pity * grid.strideP;
            const p = sixStarRate(pity + 1);
            const miss = 1 - p;
            const missBase = Math.min(pity + 1, PITY_STATES - 1) * grid.strideP;

            for (let spent = 0; spent < gStates; spent++) {
                const gBase = pityBase + spent * grid.strideG;
                for (let ca = 0; ca <= capA; ca++) {
                    const aBase = gBase + ca * grid.strideA;
                    for (let cb = 0; cb <= capB; cb++) {
                        const w = grid.data[aBase + cb];
                        if (w === 0) continue;

                        // LINKAGE is a hard handover, not a redirected 6*: "you are
                        // guaranteed to receive [X] within 120 attempts". On the
                        // 120th roll the operator arrives whether or not that roll
                        // was itself a 6*, so this bypasses the schedule entirely.
                        if (g.kind === "linkage" && ca === 0 && onBanner === (g.at ?? -1)) {
                            next.data[spent * grid.strideG + Math.min(1, capA) * grid.strideA + cb] += w;
                            sixThisStep += w;
                            continue;
                        }

                        if (miss > 0) next.data[missBase + spent * grid.strideG + ca * grid.strideA + cb] += w * miss;
                        if (p <= 0) continue;
                        const hit = w * p;
                        sixThisStep += hit;

                        let toA = split.a;
                        let toB = split.b;
                        let toOff = split.off;
                        // A 6* resets pity, so every hit below writes at pity base 0.
                        let nextSpent = spent;

                        if (g.kind === "selection") {
                            const first = g.first ?? Number.POSITIVE_INFINITY;
                            const second = g.second ?? Number.POSITIVE_INFINITY;
                            const have = (ca > 0 ? 1 : 0) + (cb > 0 ? 1 : 0);
                            if (have === 0 && onBanner >= first) {
                                toA = twoFeatured ? 0.5 : 1;
                                toB = twoFeatured ? 0.5 : 0;
                                toOff = 0;
                            } else if (twoFeatured && have === 1 && onBanner >= second) {
                                // Forced to be whichever one is still missing. Only
                                // meaningful when there IS another one: on a
                                // single-rate-up pool this rule has no referent, and
                                // applying it anyway froze the distribution.
                                toA = ca > 0 ? 0 : 1;
                                toB = ca > 0 ? 1 : 0;
                                toOff = 0;
                            }
                        } else if (g.kind === "attain" && spent === 0) {
                            // "the first 6-star Operator obtained is guaranteed to be
                            // an unowned 6-star". It is off-rate with respect to a
                            // featured target, and it happens ONCE, which is what the
                            // spent flag exists to remember. Keying this off "no
                            // copies yet" instead made the branch re-fire forever and
                            // pinned the featured operator at probability zero.
                            toA = 0;
                            toB = 0;
                            toOff = 1;
                            nextSpent = 1;
                        }

                        const gOut = nextSpent * grid.strideG;
                        if (toA > 0) next.data[gOut + Math.min(ca + 1, capA) * grid.strideA + cb] += hit * toA;
                        if (toB > 0) next.data[gOut + ca * grid.strideA + Math.min(cb + 1, capB)] += hit * toB;
                        if (toOff > 0) next.data[gOut + ca * grid.strideA + cb] += hit * toOff;
                    }
                }
            }
        }

        const swap = grid;
        grid = next;
        next = swap;
        expectedSix += sixThisStep;
        onStep(grid, step + 1, expectedSix);
    }
    return { grid, expectedSix };
}

function summarise(grid: IGrid, pulls: number, expectedSix: number): IOddsPoint {
    let specific = 0;
    let any = 0;
    let both = 0;
    let expectedCopies = 0;
    let copiesTail = 0;
    for (let pity = 0; pity < PITY_STATES; pity++) {
        const pityBase = pity * grid.strideP;
        for (let spent = 0; spent < grid.gStates; spent++) {
            const gBase = pityBase + spent * grid.strideG;
            for (let ca = 0; ca <= grid.capA; ca++) {
                const aBase = gBase + ca * grid.strideA;
                for (let cb = 0; cb <= grid.capB; cb++) {
                    const w = grid.data[aBase + cb];
                    if (w === 0) continue;
                    if (ca > 0) {
                        specific += w;
                        expectedCopies += ca * w;
                    }
                    if (ca === grid.capA) copiesTail += w;
                    if (ca > 0 || cb > 0) any += w;
                    if (ca > 0 && cb > 0) both += w;
                }
            }
        }
    }
    return { pulls, specific, any, both, expectedCopies, expectedSix, copiesTail };
}

function fill(options: IOddsOptions | undefined): Required<IOddsOptions> {
    return {
        startPity: options?.startPity ?? 0,
        startPityDist: options?.startPityDist ?? null,
        maxCopies: options?.maxCopies ?? 1,
        spentOnBanner: options?.spentOnBanner ?? 0,
    };
}

function capsFor(model: IBannerModel, opts: Required<IOddsOptions>): { capA: number; capB: number } {
    return { capA: Math.max(1, Math.floor(opts.maxCopies)), capB: model.featuredCount >= 2 ? 1 : 0 };
}

/** Odds after exactly `pulls` rolls, including the copy-count distribution. */
export function pullOdds(model: IBannerModel, pulls: number, options?: IOddsOptions): IOddsResult {
    const opts = fill(options);
    const { capA, capB } = capsFor(model, opts);
    const n = Math.max(0, Math.floor(pulls));
    const { grid, expectedSix } = walk(model, n, opts, capA, capB, () => {});
    const point = summarise(grid, n, expectedSix);
    const copies: number[] = new Array(capA + 1).fill(0);
    const endPity = new Float64Array(PITY_STATES);
    for (let pity = 0; pity < PITY_STATES; pity++) {
        const pityBase = pity * grid.strideP;
        for (let spent = 0; spent < grid.gStates; spent++) {
            const gBase = pityBase + spent * grid.strideG;
            for (let ca = 0; ca <= capA; ca++) {
                const aBase = gBase + ca * grid.strideA;
                for (let cb = 0; cb <= capB; cb++) {
                    const w = grid.data[aBase + cb];
                    copies[ca] += w;
                    endPity[pity] += w;
                }
            }
        }
    }
    return { ...point, copies, endPity };
}

/**
 * The whole curve from 0 to `maxPulls` in one pass, which costs the same as the
 * single answer at `maxPulls`. Honours `maxCopies` so `expectedCopies` on a curve
 * point means what it means on a `pullOdds` result.
 */
export function oddsCurve(model: IBannerModel, maxPulls: number, options?: IOddsOptions): IOddsPoint[] {
    const opts = fill(options);
    const { capA, capB } = capsFor(model, opts);
    const n = Math.max(0, Math.floor(maxPulls));
    const points: IOddsPoint[] = [{ pulls: 0, specific: 0, any: 0, both: 0, expectedCopies: 0, expectedSix: 0, copiesTail: 0 }];
    walk(model, n, opts, capA, capB, (grid, pulls, expectedSix) => {
        points.push(summarise(grid, pulls, expectedSix));
    });
    return points;
}

/**
 * Expected rolls per 6* in the long run, and the realised 6* rate that implies.
 * Derived from the schedule rather than quoted: the answer is 34.594555 rolls,
 * i.e. 2.8906%, against the 2% headline rate.
 */
export function longRunSixStar(): { expectedPulls: number; rate: number } {
    let survive = 1;
    let expected = 0;
    for (let n = 1; n <= PITY_STATES; n++) {
        const p = sixStarRate(n);
        const atN = survive * p;
        expected += n * atN;
        survive -= atN;
        if (survive <= 0) break;
    }
    return { expectedPulls: expected, rate: 1 / expected };
}

/** A pity distribution concentrated on one value, for seeding the first banner. */
export function pityAt(rolls: number): Float64Array {
    const d = new Float64Array(PITY_STATES);
    d[Math.min(Math.max(0, Math.floor(rolls)), PITY_STATES - 1)] = 1;
    return d;
}

/** The mean of a pity distribution, for showing a plan's carried pity as one number. */
export function meanPity(dist: ArrayLike<number>): number {
    let mass = 0;
    let total = 0;
    for (let i = 0; i < PITY_STATES && i < dist.length; i++) {
        mass += dist[i];
        total += i * dist[i];
    }
    return mass > 0 ? total / mass : 0;
}

export interface IGoalEstimate {
    /** Rolls at which the chance of reaching this goal first hits 50%. */
    p50: number;
    /** And 90%, the "plan for a bad run" number. */
    p90: number;
    /** Expected rolls to reach it, over `horizon`. */
    mean: number;
    /** Probability of STILL not having reached it after `horizon` rolls. */
    unresolved: number;
}

export interface ITargetEstimate {
    horizon: number;
    /** One named rate-up operator. */
    specific: IGoalEstimate;
    /** At least one of the banner's rate-ups. Identical to `specific` on a single. */
    any: IGoalEstimate;
    /** Both rate-ups. Null when the banner features only one. */
    both: IGoalEstimate | null;
}

/**
 * How many rolls it takes to land the rate-up operators.
 *
 * This is the statistic kukkiforarknights/gacha-experiments reports: its
 * `run_experiment` records pulls-to-first-rate-up across 10,000 simulated runs and
 * prints the mean with percentiles. The model underneath is the same one, so the
 * numbers are the same numbers; what differs is that these are read off the exact
 * distribution rather than sampled, which is why they do not move between reloads.
 * Checked against that simulator at 400,000 runs on a SINGLE banner with a horizon of
 * 400: mean 66.11 against its 66.08, median 57 against 57, 90th percentile 142
 * against 142.
 *
 * A two-rate-up banner is THREE questions, not one, and the repo's single-target
 * simulator answers none of the other two. Reaching either operator is much cheaper
 * than reaching a named one, and reaching both is much dearer. On a DOUBLE pool the
 * medians are 57 for either, 102 for a named one and 174 for both; on a LIMITED pool
 * 50, 70 and 126. Quoting only the middle figure would flatter a player chasing
 * either and mislead one chasing the pair, so all three come back. They cost nothing
 * extra: one walk already carries all three cumulative curves.
 *
 * Each mean is the sum of the survival function, E[N] = sum over n of P(N > n),
 * truncated at `horizon` and therefore a slight UNDERSTATEMENT. `unresolved` is how
 * much probability is still unaccounted for, so the size of that understatement is
 * reported rather than hidden: it is the tail's own weight.
 */
export function pullsToTarget(model: IBannerModel, options?: IOddsOptions & { horizon?: number }): ITargetEstimate {
    const horizon = Math.max(1, Math.floor(options?.horizon ?? 400));
    const curve = oddsCurve(model, horizon, options);
    const read = (pick: (p: IOddsPoint) => number): IGoalEstimate => {
        let p50 = 0;
        let p90 = 0;
        let mean = 0;
        for (let n = 0; n < curve.length; n++) {
            const f = pick(curve[n]);
            if (p50 === 0 && f >= 0.5) p50 = n;
            if (p90 === 0 && f >= 0.9) p90 = n;
            if (n < curve.length - 1) mean += 1 - f;
        }
        return { p50, p90, mean, unresolved: 1 - pick(curve[curve.length - 1]) };
    };
    return {
        horizon,
        specific: read((p) => p.specific),
        any: read((p) => p.any),
        both: model.featuredCount >= 2 ? read((p) => p.both) : null,
    };
}

/** Copies that take an operator to maximum potential: the first plus five dupes. */
export const MAX_POT_COPIES = 6;

/**
 * Rolls to take the rate-up operator to maximum potential.
 *
 * This is the headline number kukkiforarknights/gacha-experiments computes: its
 * `run_experiment` pulls until `TARGET_RATE_UPS = 6` and reports the distribution of
 * the total. Read off the exact grid here rather than sampled, from the same model.
 *
 * `copiesTail` under `maxCopies: 6` is exactly "six or more copies by now", so one
 * walk gives the whole cumulative curve, the same trick the other three goals use.
 *
 * Carried pity is deliberately NOT an input, and this is a TRADE rather than a
 * derivation. Entering a banner on 49 rolls of pity instead of 0 moves the median by
 * 26 rolls on both banner types measured: SINGLE 397 to 371, LIMITED 565 to 539. That
 * is around 6% and not nothing, but ignoring it is what lets one answer be cached per
 * banner type rather than recomputed per row, and this walk costs 40 to 90 ms against
 * 6.5 ms for the other three goals. The error is one-directional: a cold start is the
 * slower journey, so the figure shown is the conservative one.
 */
export function pullsToMaxPot(model: IBannerModel, options?: { horizon?: number; copies?: number }): IGoalEstimate {
    // 2000 already gives the same p50, p90 and mean as 3500 on every banner type;
    // 2500 is where the unresolved tail drops under 0.013% as well.
    const horizon = Math.max(1, Math.floor(options?.horizon ?? 2500));
    const copies = Math.max(1, Math.floor(options?.copies ?? MAX_POT_COPIES));
    const curve = oddsCurve(model, horizon, { maxCopies: copies });
    let p50 = 0;
    let p90 = 0;
    let mean = 0;
    for (let n = 0; n < curve.length; n++) {
        const f = curve[n].copiesTail;
        if (p50 === 0 && f >= 0.5) p50 = n;
        if (p90 === 0 && f >= 0.9) p90 = n;
        if (n < curve.length - 1) mean += 1 - f;
    }
    return { p50, p90, mean, unresolved: 1 - curve[curve.length - 1].copiesTail };
}

export interface IGoalRequest {
    /** Copies wanted of the first featured operator. */
    copiesA: number;
    /** Copies wanted of the second, on a banner that has one. */
    copiesB: number;
}

/**
 * Rolls to reach a specific pair of copy counts, for example three of one rate-up
 * and two of the other.
 *
 * The grid already tracks the two operators separately and caps each independently,
 * so asking for "three of A and two of B" is just running it with those caps and
 * reading the mass that has reached BOTH: once a count is at its cap it stays there,
 * which makes the capped cell mean "this many or more".
 *
 * The horizon is derived from what is being asked rather than fixed, because a flat
 * one either truncates a twelve-copy request or spends most of a walk on a one-copy
 * one. Expected rolls per copy are `1 / (realised 6* rate * that operator's share)`,
 * and the budget is `perCopy * (3 * copies + 6)`.
 *
 * The constant 6 is the part that matters and it is not decoration. A flat multiple
 * of the expectation truncates SMALL requests badly, because one copy has a long
 * right tail that many copies average away: budgeting one copy at three times its
 * expectation leaves 3.704% of runs unresolved and understates the mean by 3 rolls,
 * while the same multiple on six copies leaves 0.009%. The additive term buys the
 * small requests the room they need without making the large ones pay for it.
 */
export function pullsToGoal(model: IBannerModel, request: IGoalRequest, options?: IOddsOptions & { horizon?: number }): IGoalEstimate {
    const capA = Math.max(0, Math.min(MAX_POT_COPIES, Math.floor(request.copiesA)));
    const capB = model.featuredCount >= 2 ? Math.max(0, Math.min(MAX_POT_COPIES, Math.floor(request.copiesB))) : 0;
    if (capA === 0 && capB === 0) return { p50: 0, p90: 0, mean: 0, unresolved: 0 };

    const share = Math.max(1e-6, splitOf(model).a);
    const perCopy = 1 / (longRunSixStar().rate * share);
    const horizon = Math.max(200, Math.min(5000, Math.ceil(options?.horizon ?? perCopy * (3 * (capA + capB) + 6))));

    const opts = fill(options);
    let reached = 0;
    let p50 = 0;
    let p90 = 0;
    let mean = 0;
    let last = 0;
    walk(model, horizon, opts, Math.max(capA, 1), capB, (grid, pulls) => {
        // Mass that has reached both caps. With capA 0 the A dimension is inert and
        // every cell qualifies on that axis, which is what "no copies wanted" means.
        reached = 0;
        for (let pity = 0; pity < PITY_STATES; pity++) {
            const pityBase = pity * grid.strideP;
            for (let spent = 0; spent < grid.gStates; spent++) {
                const gBase = pityBase + spent * grid.strideG;
                for (let ca = capA === 0 ? 0 : capA; ca <= grid.capA; ca++) {
                    const aBase = gBase + ca * grid.strideA;
                    for (let cb = capB; cb <= grid.capB; cb++) reached += grid.data[aBase + cb];
                }
            }
        }
        if (p50 === 0 && reached >= 0.5) p50 = pulls;
        if (p90 === 0 && reached >= 0.9) p90 = pulls;
        if (pulls < horizon) mean += 1 - reached;
        last = reached;
    });
    // The first term of E[N] = sum of P(N > n) is n = 0, where nothing is reached yet.
    return { p50, p90, mean: mean + 1, unresolved: 1 - last };
}
